### PR TITLE
Bump hco version to 1.4.1

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:
```release-note
Bump hco version to 1.4.1
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by nunnatsa** [comment]
@tiraboschi : Maybe this is a problem: https://github.com/openshift/release/blob/1f906b97772b10e026e2d3288c4e65320a5de4cd/ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.4.yaml#L109

**Comment by tiraboschi** [comment]
I'm just wondering if we should rename it as `1.4`

**Comment by tiraboschi** [comment]
/hold
wait for openshift-ci

**Comment by tiraboschi** [comment]
release automation can do it automatically, closing this

**Pull request closed without merging**
