### PR TITLE
Fix release bumper

### PR DESCRIPTION
**Pull request by nunnatsa**
**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by machadovilaca — CHANGES_REQUESTED** [review]
looks good but I see that in some places you removed the list indentation:

```
     steps:
-      - name: check for existing PR
+    - name: check for existing PR
```

but in some other places, you left indented

```
     steps:
       - name: Checkout this repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
```

maybe we should try to make it uniform

**Comment by nunnatsa** [comment]
Thanks @machadovilaca. Fixed.

**Comment by nunnatsa** [comment]
No code change.

/override coverage/coveralls

**Review by orenc1 — APPROVED** [review]
/approve
👍

**Pull request merged**
