### PR TITLE
Add OperatorConditionsUnhealthy alerts

### PR DESCRIPTION
**Pull request by machadovilaca**
**What this PR does / why we need it**:

Add alerts based on kubevirt_hco_system_health_status

The alert includes the reason of the condition that sets the health to a given status. For that, `kubevirt_hco_system_health_status` was updated to add a `reason` label, that has the value of the reason field in the underlying condition

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-48799
```

**Release note**:

```release-note
Add OperatorConditionsUnhealthy alerts
```

### CODE REVIEW

**Comment by sradco** [comment]
@machadovilaca Hi, Please add the PR of the new alert to this PR description. Thank you.

**Comment by sradco** [comment]
@machadovilaca In this PR you are adding a new alert but also updating the metrics with the reason. 
Please explain in the description how the reason is calculated.

**Comment by sradco** [comment]
@machadovilaca  can you please add an example for the metrics with the new reason label?
And explain what happens if there are a few conditions that are not healthy.

**Comment by sradco** [comment]
@avlitman please review

**Comment by nunnatsa** [comment]
@sradco - it currently does not pass CI - including sanity test.

I think it needs at least #3153

**Comment by nunnatsa** [comment]
@machadovilaca, I find the name of the alert confusing. The term `OperatorCondition` is used for something else in OLM, and it may misguide users.

**Comment by sradco** [comment]
> @machadovilaca, I find the name of the alert confusing. The term `OperatorCondition` is used for something else in OLM, and it may misguide users.

@nunnatsa how would you call this alert? It is firing based on the HCO CR conditions.

**Comment by nunnatsa** [comment]
> > @machadovilaca, I find the name of the alert confusing. The term `OperatorCondition` is used for something else in OLM, and it may misguide users.
> 
> @nunnatsa how would you call this alert? It is firing based on the HCO CR conditions.

Maybe `HCOOperatorConditionUnhealthy`?

**Comment by avlitman** [comment]
@machadovilaca need to rebase (operatorrules should be operatorRegistry) and change alert name.
other than that looks good to me

**Comment by sradco** [comment]
@nunnatsa @machadovilaca I would like to use a generic name that can be used by other operators.
That is why HCO is not in the alert name.

**Comment by nunnatsa** [comment]
@machadovilaca - the "should fired when KubeDescheduler is installed and not properly configured for KubeVirt" e2e test is failing.

The reason for that is the addition of the reason label, while in `HCOPrometheusClient::GetHCOMetric()`, we only remove the query text from the result metric line, and then trying to convert text into int, but we still have the label in the text so the conversion fails.

I suggest to change tests/func-tests/hco_prometheus_route.go:

```go
var metricValueRegex = regexp.MustCompile(` (\d+(?:\.\d+)?)$`) // <== add this

func (hcoCli HCOPrometheusClient) GetHCOMetric(ctx context.Context, query string) (float64, error) {
	req, err := http.NewRequest(http.MethodGet, hcoCli.url, nil)
	if err != nil {
		return 0, fmt.Errorf("failed to create request: %w", err)
	}

	resp, err := hcoCli.cli.Do(req.WithContext(ctx))
	if err != nil {
		return 0, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return 0, fmt.Errorf("failed to read the temp route status: %s", resp.Status)
	}

	scanner := bufio.NewScanner(resp.Body)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, query) {
			groups := metricValueRegex.FindStringSubmatch(line)  // <== add this
			if len(groups) != 2 { // <== add this
				return 0, fmt.Errorf("no numeric value in: %q", line) // <== add this
			}
			
			res, err := strconv.ParseFloat(groups[1], 64) // <== change this
			if err != nil {
				return 0, fmt.Errorf("error converting %s to int: %v\n", line, err)
			}
			return res, nil
		}
	}
	return 0, nil
}
```

**Comment by machadovilaca** [comment]
@nunnatsa since the exposition format is always in the format

`$METRIC{$LABELS} $VALUE $TIMESTAMP`

what do you think about:

```
			parts := strings.Fields(line)
			if len(parts) < 2 {
				return 0, fmt.Errorf("metric line does not contain a value")
			}
			res, err := strconv.ParseFloat(strings.TrimSpace(parts[1]), 64)
```
?

would work for every possible allowed format

ref: https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md

**Comment by nunnatsa** [comment]
your change makes sense. What I don't understand is how it's worked until now, and still working for other metrics, because we never had issues with the timestamp with the old code of
```go
res, err := strconv.ParseFloat(strings.TrimSpace(strings.TrimPrefix(line, query)), 64)
```

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-prev-operator-sdk-sno-azure lane passed
/override ci/prow/hco-e2e-upgrade-prev-operator-sdk-sno-aws

hco-e2e-operator-sdk-sno-azure lane passed
/override ci/prow/hco-e2e-operator-sdk-sno-aws

**Pull request merged**
