### PR TITLE
Add new label_test functional test

### PR DESCRIPTION
**Pull request by nunnatsa**
Also, fix some errors from ginkgo

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-30582
```

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
hco-e2e-kv-smoke-gcp lane passed
/override ci/prow/hco-e2e-kv-smoke-azure

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
