### PR TITLE
Optionally ignore relatedImages from component operators

### PR DESCRIPTION
**Pull request by tiraboschi**
Add a a flag to the csv-merger tool to optionally ignore
relatedImages from component operators generated CSV.

#fixes https://bugzilla.redhat.com/1882052

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Optionally ignore relatedImages from component operators
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-prev-aws passed
/override ci/prow/hco-e2e-upgrade-prev-azure

the image-index tests are expected to fail until the openshift/release#11838 PR will be merged
/override ci/prow/hco-e2e-image-index-aws
/override ci/prow/hco-e2e-image-index-azure
/override ci/prow/hco-e2e-image-index-gcp

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-prev-aws passed
/override ci/prow/hco-e2e-upgrade-prev-azure

**Pull request merged**
