### PR TITLE
manual bump CDI to v1.59.0

### PR DESCRIPTION
**Pull request by nunnatsa**
Also, fix a bug in node placement e2e test.

**Release note**:

```release-note
Bump CDI to v1.59.0
```

### CODE REVIEW

**Comment by orenc1** [comment]
i saw some openshift-ci build-related issues.
/retest

**Comment by nunnatsa** [comment]
hco-e2e-consecutive-operator-sdk-upgrades-azure lane passed
/override ci/prow/hco-e2e-consecutive-operator-sdk-upgrades-aws

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-operator-sdk-sno-aws lane passed
/override ci/prow/hco-e2e-upgrade-operator-sdk-sno-azure

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
