### PR TITLE
Update SSP operator to v1.0.16

### PR DESCRIPTION
**Pull request by fromanirh**
Update SSP operator to v1.0.16

### CODE REVIEW

**Comment by rthallisey** [comment]
ci test please

**Comment by djzager** [comment]
ci test please

**Comment by fromanirh** [comment]
still no luck in setting up the okd 4.1 cluster :\

**Comment by rthallisey** [comment]
4.1 setup works locally, I'm not sure what's failing.

**Comment by rthallisey** [comment]
The 4.1 job is failing to start is unrelated, merging.

**Pull request merged**
