### PR TITLE
[CNV-39949] enable nosniff for kubevirt-console-plugin nginx config

### PR DESCRIPTION
**Pull request by orenc1**
**What this PR does / why we need it**:
To increase security measures, it is advise to add the 'nosniff' Anti-MIME-Sniffing header X-Content-Type-Options in the kubevirt-console-plugin NGINX configuration. The advantages of setting it are:

- **Improved Security**: Prevents MIME type sniffing and reduces the risk of executing unintended scripts.
- **XSS Mitigation**: Decreases the chances of cross-site scripting attacks.
- **Effective CSP**: Ensures that Content Security Policies are enforced correctly.
- **Adherence to Best Practices**: Aligns with recommended security practices.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-39949
```

**Release note**:

```release-note
Enable 'nosniff' for kubevirt-console-plugin nginx webserver
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
:+1: 
/approve

**Comment by orenc1** [comment]
fixed the indentation.
@nunnatsa , could you please re-review?

**Pull request merged**
