### PR TITLE
add error handling to hack/build-manifest.sh

### PR DESCRIPTION
**Pull request by nunnatsa**
`set -e` does not stop the process if the error is happened within a command substitution. This is why the [hack/build-manifest.sh] script didn't fail in some cases, e.g. when an image was missing in the remote registry.

This PR added error handling to the script:
* Added `trap` command and the `catch` method
* command substitution inside string building didn't catch by the trap. This lines were split to make sure the trap catches any error. For example:
```bash
A_VARIABLE="Text text${VAR1}/$(failed command)"
```
was split to something like:
```bash
A_TEMP_VAR="$(failed command)"
A_VARIABLE="Text text${VAR1}/${A_TEMP_VAR}"
```
* Single line local variables with command substitution were not caught by the trap, and was also split. For example:
```bash
function foo() {
  ...
  local a_variable="$(failed command)"
  ...
```
was split to something like:
```bash
function foo() {
  ...
  local a_variable
  a_variable="$(failed command)"
  ...
```
* Add simple versifcation to the operator CSV files, by greping for their `image:` line. This check both that the file is not empty and the image makes some sense
* The csv-merger will now panic if one of the CSVs is empty
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
After rebase #827, the image-index tests are expected to fail until the https://github.com/openshift/release/pull/11838 PR will be merged

**Comment by tiraboschi** [comment]
hco-e2e-image-index-azure passed
/override ci/prow/hco-e2e-upgrade-prev-azure

the image-index tests are expected to fail until the openshift/release#11838 PR will be merged
/override ci/prow/hco-e2e-image-index-aws
/override ci/prow/hco-e2e-image-index-azure
/override ci/prow/hco-e2e-image-index-gcp

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
