### PR TITLE
Remove MRO conditions check

### PR DESCRIPTION
**Pull request by rthallisey**
Since the MRO is a new addition to the HCO and it doesn't have upgrade support, let's not block CNV's upgrade on the MRO's conditions.   If the MRO adds upgrade at a later date, we can give it the ability to block upgrade again.

### CODE REVIEW

**Comment by rthallisey** [comment]
cc @beekhof

**Comment by rthallisey** [comment]
ci test please

**Comment by beekhof** [comment]
Happy to agree to this. We can revisit upgrades once artyom is back

**Comment by rthallisey** [comment]
ci test please

**Comment by rthallisey** [comment]
ci test please

**Comment by rthallisey** [comment]
This gate error is not related to this PR. Merging.

**Pull request merged**
