### PR TITLE
docs: AAQ default namespace selector

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
Add AAQ docs regarding its default namespace selector.
This is reflecting the changes done in https://github.com/kubevirt/application-aware-quota/pull/59.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [X] PR Message
- [X] Commit Messages
- [ ] ~How to test~
- [ ] ~Unit Tests~
- [ ] ~Functional Tests~
- [X] User Documentation
- [X] Developer Documentation
- [ ] ~Upgrade Scenario~
- [ ] ~Uninstallation Scenario~
- [ ] ~Backward Compatibility~
- [ ] ~Troubleshooting Friendly~

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-39880
```

**Release note**:

```release-note
docs: AAQ default namespace selector
```

### CODE REVIEW

**Comment by iholder101** [comment]
FYI @Barakmor1 @kbidarkar @acardace

**Comment by Barakmor1** [comment]
/hold
Maybe lets mentioned the spec.nodeName limitation

Please feel free to unhlod.

**Comment by iholder101** [comment]
> /hold Maybe lets mentioned the spec.nodeName limitation
> 
> Please feel free to unhlod.

Done!
/unhold

**Pull request merged**
