### PR TITLE
test: force RollingUpgrade on all the deployments

### PR DESCRIPTION
**Pull request by tiraboschi**
test only

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zcahana** [comment]
@tiraboschi These are pretty good results for the first round of tests - the two `e2e-upgrade-` failures don't seem related to the CNAO issue we've seen. Should we /retest everything to see if this continues to pass?

**Comment by tiraboschi** [comment]
yes,
let's run again the failed ones
/retest

**Comment by tiraboschi** [comment]
still
```
Command: oc get clusterserviceversions -n kubevirt-hyperconverged
NAME                                        DISPLAY                                    VERSION   REPLACES                                  PHASE
kubevirt-hyperconverged-operator.v1.3.0     KubeVirt HyperConverged Cluster Operator   1.3.0     kubevirt-hyperconverged-operator.v1.2.0   Pending
kubevirt-hyperconverged-operator.v100.0.0   KubeVirt HyperConverged Cluster Operator   100.0.0   kubevirt-hyperconverged-operator.v1.3.0   Pending
```
probably because this is patching only the CSV we want to upgrade to, but the issue is with the CSV we start from.

**Comment by nunnatsa** [comment]
> probably because this is patching only the CSV we want to upgrade to, but the issue is with the CSV we start from.

No, in this test we're using the same CSV and only replacing the images

**Comment by tiraboschi** [comment]
Not working

**Pull request closed without merging**
