### PR TITLE
Bump version to 1.8.0

### PR DESCRIPTION
**Pull request by tiraboschi**
Apply also the fix in https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1980
to unlock CI.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by orenc1** [comment]
fails mainly on cluster bootstrap and stuck vm uptime check
/retest

**Comment by nunnatsa** [comment]
one more try:
/retest

**Comment by orenc1** [comment]
checking if okd breakage was resolved
/retest

**Comment by tiraboschi** [comment]
trying on OKD 4.10
/retest

**Review by orenc1 — APPROVED** [review]
/approve
🎉🎉🎉

**Pull request merged**
