### PR TITLE
Rebase Bot

### PR DESCRIPTION
**Pull request by orenc1**
In order to activate the bot, comment '/rebase' in an open pull request to rebase the PR branch over master.

Signed-off-by: orenc1 <ocohen@redhat.com>

**Release note**:

```release-note
Adding Rebase-Bot to HCO repository.
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
@orenc1 I'm wondering if we should eventually also try to run hack/build-manifests.sh (somehow, not sure if possible) to regenerate all the manifests on rebase

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by orenc1** [comment]
> @orenc1 I'm wondering if we should eventually also try to run hack/build-manifests.sh (somehow, not sure if possible) to regenerate all the manifests on rebase

I have a working workflow performing `build-manifests.sh` before rebasing. will update this PR shortly.

**Comment by ovirt-infra** [comment]
All tests passed

**Pull request merged**
