### PR TITLE
Consume nightly virt-operator while waiting for v0.34.0

### PR DESCRIPTION
**Pull request by tiraboschi**
Consume nightly virt-operator while waiting for v0.34.0,
to be able to consume node-placement APIs ASAP.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
@stu-gott node placement APIs are still not on virt-operator CRD, maybe in tomorrow nightly?

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
I just touched a comment, no need to wait for CI

**Comment by ovirt-infra** [comment]
All tests passed

**Review by orenc1 — APPROVED** [review]

**Pull request merged**
