### PR TITLE
Refactor reconcile

### PR DESCRIPTION
**Pull request by nunnatsa**
Refactor the Reconciler by moving all the operand handling to a new package, to make the code base more clear and robust, and to ease the integration of future operands.

This is a pretty large PR. It's trying to simplifiies the reconcile code, by moving all the operand handling to a new package named `operands`, in order to ease future operand integrations. 

The `hyperconverged_controller.go` file is now only handling the HCO itself, and all the operand handling is done by a single call to the operand package. The size of this file was dropped from +2000 lines to ~700 lines.

In the operands package, each operand has its own handler code file and a test file. Withing these files there is a new handler type for each operand. all these handlers are implementing the new `Operand` interface. The `Operand` interface contains a single function: `Ensure(req *common.HcoRequest) *EnsureResult`.

The `operands` package also contains the new `OperandHandler` type, that is kind of the package interface for the reconciler - the reconciler holds an object of this type. It has two public function - `Ensure` and `EnsureDeleted`. So the HCO handler does not know any specific operand, but only the operandHandler.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by nunnatsa** [comment]
Done in #902, #903, #905, #906, #907, #908, and #909

**Pull request closed without merging**
