### PR TITLE
bump SSP to v1.0.23

### PR DESCRIPTION
**Pull request by tiraboschi**
```release-note
bump SSP to v1.0.23
```

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

### CODE REVIEW

**Comment by tiraboschi** [comment]
from CI: hyperconverged-cluster-operator-9996cf98b-rl42h   0/1     CrashLoopBackOff   8          20m
it needs investingation

**Comment by tiraboschi** [comment]
It fails on:

{"level":"error","ts":1582282587.060049,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"KubevirtCommonTemplatesBundle.kubevirt.io","error":"no matches for kind \"KubevirtCommonTemplatesBundle\" in version \"kubevirt.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/internal.go:477"}
{"level":"error","ts":1582282587.060551,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"KubevirtCommonTemplatesBundle\" in version \"kubevirt.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/cmd/hyperconverged-cluster-operator/main.go:175\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

**Comment by tiraboschi** [comment]
PRobably we need a change here https://github.com/MarSik/kubevirt-ssp-operator/blob/master/pkg/apis/kubevirt/v1/register.go#L13 to set the group name, then a new SSP release and the we will be able to vendor in the new code fixing the group name.

**Comment by ksimon1** [comment]
PR with fix https://github.com/MarSik/kubevirt-ssp-operator/pull/147

**Comment by tiraboschi** [comment]
@ksimon1 HCO fails on
```E0224 16:40:13.759200       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.4/tools/cache/reflector.go:96: Failed to list *v1.KubevirtCommonTemplatesBundle: kubevirtcommontemplatesbundles.ssp.kubevirt.io is forbidden: User "system:serviceaccount:kubevirt-hyperconverged:hyperconverged-cluster-operator" cannot list resource "kubevirtcommontemplatesbundles" in API group "ssp.kubevirt.io" at the cluster scope
E0224 16:40:13.761556       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.4/tools/cache/reflector.go:96: Failed to list *v1.KubevirtNodeLabellerBundle: kubevirtnodelabellerbundles.ssp.kubevirt.io is forbidden: User "system:serviceaccount:kubevirt-hyperconverged:hyperconverged-cluster-operator" cannot list resource "kubevirtnodelabellerbundles" in API group "ssp.kubevirt.io" at the cluster scope
E0224 16:40:13.765181       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.4/tools/cache/reflector.go:96: Failed to list *v1.KubevirtTemplateValidator: kubevirttemplatevalidators.ssp.kubevirt.io is forbidden: User "system:serviceaccount:kubevirt-hyperconverged:hyperconverged-cluster-operator" cannot list resource "kubevirttemplatevalidators" in API group "ssp.kubevirt.io" at the cluster scope
E0224 16:40:13.768570       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.4/tools/cache/reflector.go:96: Failed to list *v1.KubevirtMetricsAggregation: kubevirtmetricsaggregations.ssp.kubevirt.io is forbidden: User "system:serviceaccount:kubevirt-hyperconverged:hyperconverged-cluster-operator" cannot list resource "kubevirtmetricsaggregations" in API group "ssp.kubevirt.io" at the cluster scope
E0224 16:40:14.765707       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.4/tools/cache/reflector.go:96: Failed to list *v1.KubevirtNodeLabellerBundle: kubevirtnodelabellerbundles.ssp.kubevirt.io is forbidden: User "system:serviceaccount:kubevirt-hyperconverged:hyperconverged-cluster-operator" cannot list resource "kubevirtnodelabellerbundles" in API group "ssp.kubevirt.io" at the cluster scope
```

**Comment by tiraboschi** [comment]
@ksimon1 this is now failing on OLM based upgrade tests; I'm wondering if we have to do something special for upgrades

**Comment by ksimon1** [comment]
i am not aware of any special treatment for ssp operator.

**Comment by fabiand** [comment]
… that can well be that we need to treat updates special after an apiVersion change

**Comment by tiraboschi** [comment]
Here we are trying to upgrade to the same API version but with a different API group.
I'll try to reproduce it locally to better check OLM behaviour.

**Comment by tiraboschi** [comment]
I tried it on a local cluster and the upgrade worked as expected for me, maybe it's something specific to our upgrade test job.

**Comment by tiraboschi** [comment]
The upgrade test is failing with:
```
{"level":"info","ts":1582732686.4785862,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"hyperconverged-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1582732686.569066,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"KubevirtCommonTemplatesBundle.kubevirt.io","error":"no matches for kind \"KubevirtCommonTemplatesBundle\" in version \"kubevirt.io/v1\"","stacktrace":"github.com/kubevirt/hyperconverged-cluster-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubevirt/hyperconverged-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/kubevirt/hyperconverged-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/hyperconverged.add\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/hyperconverged/hyperconverged_controller.go:97\ngithub.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/hyperconverged.Add\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/hyperconverged/hyperconverged_controller.go:65\ngithub.com/kubevirt/hyperconverged-cluster-operator/pkg/controller.AddToManager\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/pkg/controller/controller.go:13\nmain.main\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/cmd/hyperconverged-cluster-operator/main.go:138\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}
{"level":"error","ts":1582732686.569165,"logger":"cmd","msg":"","error":"no matches for kind \"KubevirtCommonTemplatesBundle\" in version \"kubevirt.io/v1\"","stacktrace":"github.com/kubevirt/hyperconverged-cluster-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/kubevirt/hyperconverged-cluster-operator/cmd/hyperconverged-cluster-operator/main.go:139\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}```

I fear that the issue is that we are running an upgrade starting from pre-PR code (looking for KubevirtCommonTemplatesBundle in kubevirt.io API group) deployed in a bundle with newer CRDs where KubevirtCommonTemplatesBundle is already in ssp.kubevirt.io

**Comment by tiraboschi** [comment]
This finally passed CI but I'd prefer to split this into two PRs to better track it:
1. all the upgrade suite related fixes
2. the changes required to bump SSP on top of a working upgrade test suite

**Comment by tiraboschi** [comment]
All the upgrade suite related commits have been squashed in https://github.com/kubevirt/hyperconverged-cluster-operator/pull/481

This one will be cleaned out to contain only SSP bump commits and rebased on topo of #481 once merged.

**Pull request merged**
