### PR TITLE
Update found object for PriorityClass

### PR DESCRIPTION
**Pull request by erkanerol**
We don't update PriorityClass object. We delete and
re-create. The "found" object is used for updating
object references in status of HCO. Therefore, it
must be up-to-date.

Signed-off-by: Erkan Erol <eerol@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Fix an issue in updating PriorityClass object in relatedObjects.
```

### CODE REVIEW

**Comment by erkanerol** [comment]
@nunnatsa May I get an approval?

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-prev-index-azure-sno seems still not so reliable but the issue is not related to this specific PR
/override ci/prow/hco-e2e-upgrade-prev-index-azure-sno

**Pull request merged**
