### PR TITLE
Workflow for auto-publishing tagged HCO versions to community-operators

### PR DESCRIPTION
**Pull request by orenc1**
- On every tag in HCO Repo, the workflow will create a pull request in https://github.com/operator-framework/community-operators with the tagged content.

- _community-operators_ requires the packaging format to be either manifest format (old), or bundle format (new). Not a mix of the two. This PR also aligns the directory structure to be bundle format only.
https://operator-framework.github.io/community-operators/packaging-operator/

- fixing the metadata description to be a one-liner, instead of the full description of the spec section.
Signed-off-by: orenc1 <ocohen@redhat.com>

**Release note**:

```release-note
auto-release to community-operators on version tag.
```

### CODE REVIEW

**Comment by orenc1** [comment]
Ready for review.
example run:

- [Tagging v1.4.1](https://github.com/orenc1/hyperconverged-cluster-operator/releases/tag/v1.4.1)
- [The triggered action](https://github.com/orenc1/hyperconverged-cluster-operator/actions/runs/632947436)
- Generated PRs in community-operators - https://github.com/operator-framework/community-operators/pull/3255 & https://github.com/operator-framework/community-operators/pull/3256

**Comment by tiraboschi** [comment]
Ignoring slightly decreased coverage
/override coverage/coveralls

**Comment by orenc1** [comment]
closing and reopening due to a stuck kubevirt-ci lane.
/close

**Pull request merged**
