### PR TITLE
Update MRO to v0.3.12

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by rthallisey** [comment]
@cynepco3hahue is this for cnv 2.1? If it is, add "/cherrypick release-2.1"

Also, create a new PR that changes to version MRO in the 0.0.3 CSV to v0.3.11.

**Comment by cynepco3hahue** [comment]
@rthallisey yep it should be, by the way what the point to update it upstream if under the d/s we use d/s images from errata?

**Comment by rthallisey** [comment]
Upstream has all the CI right now and d/s downstream doesn't.  In addition, you can consume from operatorhub.

**Comment by cynepco3hahue** [comment]
> @cynepco3hahue is this for cnv 2.1? If it is, add "/cherrypick release-2.1"
> 
> Also, create a new PR that changes to version MRO in the 0.0.3 CSV to v0.3.11.

Done

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
@rthallisey Can you please merge it?

**Comment by rthallisey** [comment]
@cynepco3hahue the 0.0.2 changes will need to be backported to release-2.1 branch

**Pull request merged**
