### PR TITLE
Move golden image test to golang

### PR DESCRIPTION
**Pull request by nunnatsa**
**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-26496
```

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
/test pull-hyperconverged-cluster-operator-e2e-k8s-1.26-centos9

no code or unit-test changes
/override coverage/coveralls

**Comment by nunnatsa** [comment]
/test pull-hyperconverged-cluster-operator-e2e-k8s-1.26-centos9

no code or unit-test changes
/override coverage/coveralls

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
