### PR TITLE
Bump VM_IMPORT to v0.0.3

### PR DESCRIPTION
**Pull request by pkliczewski**
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
Signed-off-by: hco_bump_bot <hco_bump_bot@redhat.com>

```release-note
Bump VM_IMPORT to v0.0.3
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by pkliczewski** [comment]
@tiraboschi FYI

**Comment by masayag** [comment]
@pkliczewski seems like a duplication of https://github.com/kubevirt/hyperconverged-cluster-operator/pull/630

**Comment by pkliczewski** [comment]
@tiraboschi Should I close this PR? We have already https://github.com/kubevirt/hyperconverged-cluster-operator/pull/630

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by nunnatsa** [comment]
duplicate of #630

**Pull request closed without merging**
