### PR TITLE
Add component graphs

### PR DESCRIPTION
**Pull request by tiraboschi**
Add component graphs and add
automation to automatically keep them up to date from
the nightly jobs.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Add component graphs
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
ignoring slightly decreased coverage
/ovveride coverage/coveralls

**Comment by tiraboschi** [comment]
ignoring slightly decreased coverage
/override coverage/coveralls

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
