### PR TITLE
Bump PROJECT to kubebuilder go/v4

### PR DESCRIPTION
**Pull request by nunnatsa**
### Bump PROJECT to kubebuilder go/v4
operator-sdk, from verstion v1.38.0, does not support kubebuilder go/v3 anymore. Any attempt to run the new operator-sdk in the HCO repo, fails even if the request is not related to the code, e.g. to install olm.

This PR bumps the kubebuilder go version to go/v4, to allow running the newest operator-sdk in the hco repo, e.g. for deploying HCO in tests.

### use the latest operator-sdk in the nightly test
After bumping the PROJECT file to go/v4, it is now possible to use the latest operator-sdk.

### [DEV] allow running locally w/ prometheous
Currently, if prometheous is deployed on the cluster, HCO fails to start when running from an IDE against the cluster.

This commit fixes the issue and now it is possible.

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
/hold

Need to bump operator-sdk in openshiftci.

**Comment by nunnatsa** [comment]
needs https://github.com/openshift/release/pull/59241

After this PR will be merge, need to retest

**Comment by nunnatsa** [comment]
openshift/release#59241 merged

/unhold

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-operator-sdk-sno-aws lane succeeded
/override ci/prow/hco-e2e-upgrade-operator-sdk-sno-azure

**Pull request merged**
