### PR TITLE
Switch to use the new SSP operator [release-1.3]

### PR DESCRIPTION
**Pull request by zcahana**
This PR mirrors #966 but is targeted at the `release-1.3` branch.

```release-note
Switch to use the new SSP operator.
```

### CODE REVIEW

**Comment by zcahana** [comment]
Cherry-picked from #1039 to speed-up testing.

**Comment by tiraboschi** [comment]
It successfully passed hco-e2e-upgrade-prev-aws and hco-e2e-image-index-aws which are the two most relevant lanes (hco-e2e-upgrade-* are not that relevant because removing the old SSP operator without really bumping the .y version is not an interesting use case) for this PR,
everything else is probably just environmental so we can safely tolerate
/override hco-e2e-upgrade-aws
/override hco-e2e-upgrade-prev-azure

**Comment by zcahana** [comment]
Per discussion with @tiraboschi and @nunnatsa, we'll override the `hco-e2e-upgrade-aws` and `hco-e2e-upgrade-azure` tests which are bound to fail in this PR, since they try to upgrade from a 1.3.0 CSV version (i.e., without old SSP CRDs) while running an HCO image that tries to create these CRDs, causing a "no such CRD" test failures.

/override hco-e2e-upgrade-aws
/override hco-e2e-upgrade-azure

**Comment by zcahana** [comment]
Retrying overrides:
/override ci/prow/hco-e2e-upgrade-aws
/override ci/prow/hco-e2e-upgrade-azure

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by nunnatsa** [comment]
/override hco-e2e-upgrade-azure

as it can't pass until the image is updated

**Comment by nunnatsa** [comment]
/override ci/prow/hco-e2e-upgrade-azure

as it can't pass until the image is updated

**Pull request merged**
