### PR TITLE
Revert TTO integration

### PR DESCRIPTION
**Pull request by tiraboschi**
Revert TTO integration till we are properly able to
rebuild it everywhere:
Revert "onboard new operator tekton-tasks-operator (#1821)"
Revert "Bump TTO to v0.2.1 (#1861)"

This reverts commits:
4494a4e5c2d6e64e128ce2013ebb1b4b6b61a4eb.
48f31ab629db80de7e5c6f1d4184f416e01bd88c.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by benukhanov — APPROVED** [review]
LGTM

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
