### PR TITLE
Bump HCO to version 1.13.0

### PR DESCRIPTION
**Pull request by nunnatsa**
**Release note**:

```release-note
Bump HCO to version 1.13.0
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
okd is broken
/override ci/prow/okd-hco-e2e-operator-sdk-aws
/override ci/prow/okd-hco-e2e-operator-sdk-gcp
/override ci/prow/okd-hco-e2e-upgrade-operator-sdk-aws
/override ci/prow/okd-hco-e2e-upgrade-operator-sdk-gcp

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
OKD lanes are broken 

/override ci/prow/okd-hco-e2e-operator-sdk-aws
/override ci/prow/okd-hco-e2e-operator-sdk-gcp
/override ci/prow/okd-hco-e2e-upgrade-operator-sdk-aws
/override ci/prow/okd-hco-e2e-upgrade-operator-sdk-gcp

**Pull request merged**
