### PR TITLE
Get ready for 1.3.0

### PR DESCRIPTION
**Pull request by tiraboschi**
Get ready for 1.3.0

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Create CSV 1.3.0 
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Review by orenc1 — APPROVED** [review]

**Review by nunnatsa — APPROVED** [review]

**Comment by tiraboschi** [comment]
hco-e2e-aws passed
/override ci/prow/hco-e2e-azure

**Comment by nunnatsa** [comment]
hco-e2e-aws passed
/override ci/prow/hco-e2e-azure

**Comment by tiraboschi** [comment]
All the index image tests are expected to fail until we will merge https://github.com/openshift/release/pull/11838
/override ci/prow/hco-e2e-image-index-aws
/override ci/prow/hco-e2e-image-index-azure
/override ci/prow/hco-e2e-image-index-gcp

**Pull request merged**
