### PR TITLE
[Release-1.10] prepare for next release

### PR DESCRIPTION
**Pull request by nunnatsa**
## What this PR does / why we need it
There is a bug in the publish job, that overrides the existing image tags, with the same tag.

This PR fix version 1.10.1 by adding a new directory for it, pointing to the new images.

It also prepare the next version, 1.10.2, by adding a new directory for it, and modify the publish job to add a new version directory after publishing.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
Prepare for version 1.10.2
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
hco-e2e-operator-sdk-sno-aws lane passed
/override ci/prow/hco-e2e-operator-sdk-sno-azure

**Comment by nunnatsa** [comment]
hco-e2e-kv-smoke-gcp lane passed
/override ci/prow/hco-e2e-kv-smoke-azure

hco-e2e-operator-sdk-gcp lane passed
/override ci/prow/hco-e2e-operator-sdk-azure

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
