### PR TITLE
Allow overriding the default golden image namespace

### PR DESCRIPTION
**Pull request by nunnatsa**
**What this PR does / why we need it**:

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-23196
```

**Release note**:

```release-note
Allow overriding the default golden image namespace
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
sonar cloud started to check the vendor directories too, creating false negative duplication error
/override SonarCloud Code Analysis

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
