### PR TITLE
Temporary avoid requiring NMO

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
OLM doesn't create any install plan:

```
============
InstallPlans
============
Command: oc get installplans -n kubevirt-hyperconverged -o yaml

apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by tiraboschi** [comment]
The issue is specific to OCP 4.6 and not related to NMO.
Not needed.

**Pull request closed without merging**
