### PR TITLE
Enable NonRoot feature gate by default

### PR DESCRIPTION
**Pull request by xpivarc**
This PR enables NonRoot feature gate by default. The feature gate is now fully tested https://github.com/kubevirt/kubevirt/pull/7469. 

HCO should enable this because it is a security feature.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

Needs https://github.com/kubevirt/kubevirt/pull/7469

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NonRoot feature gate is on by default
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
Thanks for the PR @xpivarc! It looks good to me. Please just edit the PR description with some info: what this PR changes, and why.

**Review by nunnatsa — CHANGES_REQUESTED** [review]
Looks good in general. Please add some info to the description: what this PR changes and why.

**Comment by xpivarc** [comment]
> Looks good in general. Please add some info to the description: what this PR changes and why.

@nunnatsa 
Done

**Review by nunnatsa — APPROVED** [review]

**Pull request merged**
