### PR TITLE
Update SSP RBAC rules

### PR DESCRIPTION
**Pull request by rthallisey**
fixes: #148 

We really need to merge SSP's template into the HCO @fromanirh

### CODE REVIEW

**Comment by rthallisey** [comment]
ci test please

**Comment by fromanirh** [comment]
This sounds familiar, we already had to do this fix, I thought we added it everywhere. Looks like I'm wrong, but I wonder what we missed.

**Comment by rthallisey** [comment]
@fromanirh, do you think you can look into adding SSP to the HCO's template generation?

**Comment by fromanirh** [comment]
> @fromanirh, do you think you can look into adding SSP to the HCO's template generation?

I can try to fit in this sprint. To make sure we're on the same page and we'll not miss anything more, could you please point me to the general area I need to change?

**Comment by rthallisey** [comment]
Call out to the SSP code from manifest-templator:
- https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/tools/manifest-templator/manifest-templator.go

Replace templates:
- https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/templates/olm-catalog/kubevirt-hyperconverged/VERSION/kubevirt-hyperconverged-operator.VERSION.clusterserviceversion.yaml.in
- https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/templates/cluster_role.yaml.in
- https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/templates/operator.yaml.in

If you post a WIP pr I can also point to code examples.

**Pull request merged**
