### PR TITLE
Revert an hack on upgrade lanes

### PR DESCRIPTION
**Pull request by tiraboschi**
Revert an hack on upgrade lanes introduced in #1323
to bypass a possible upgrade bug on the OLM side.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by orenc1** [comment]
We would be able to revert the workaround once https://github.com/operator-framework/operator-lifecycle-manager/pull/2382 will make its way to OLM downstream and be consumed by OCP-CI

**Comment by orenc1** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2002276 is in QA
/retest

**Comment by orenc1** [comment]
looks like now OLM bug resolved, but now failing on
```
 Not all the running VMs got upgraded 
```
/retest

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
