### PR TITLE
Change default value for completionTimeoutPerGiB to 150s

### PR DESCRIPTION
**Pull request by iholder101**
**What this PR does / why we need it**:
This is a replacement for https://github.com/kubevirt/hyperconverged-cluster-operator/pull/3164, which is aiming to address https://github.com/kubevirt/hyperconverged-cluster-operator/issues/3163. I still think removing non-essential defaulting from HCO is absolutely desired for many reasons, one of them being to remove the need of merging 2 PRs, one to Kubevirt and one to HCO, in order to change a default value. However, I don't want to block reducing the migration completion timeout until this effort is pushed forward.

Until then, this PR aligns with https://github.com/kubevirt/kubevirt/pull/12848.

**Release note**:

```release-note
Change default value for completionTimeoutPerGiB to 150s
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by nunnatsa** [comment]
@iholder101 - please rebase. You'll need #3194 for workaround the CI failures

**Comment by iholder101** [comment]
> @iholder101 - please rebase. You'll need #3194 for workaround the CI failures

Done. Thanks for your help!

**Pull request merged**
