### PR TITLE
Handle an unhandled error

### PR DESCRIPTION
**Pull request by dharmit**
**What this PR does / why we need it**:
It handles an unhandled error in the `Reconcile` function.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket

```

**Release note**:

```release-note
Handle an unhandled error in Reconcile function
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by dharmit** [comment]
@nunnatsa @tiraboschi is there something I should be doing to make CI happy here? It feels like a lot of time spent on the CI for such a small PR. 😭

**Comment by nunnatsa** [comment]
> is there something I should be doing to make CI happy here? It feels like a lot of time spent on the CI for such a small PR. :sob:

The smoke test in gcp seems to be broken, and in azure it keep failing - I don't think it's related to the change in this PR.

**Pull request merged**
