### PR TITLE
bump CNAO to 0.18.0

### PR DESCRIPTION
**Pull request by phoracek**
* Allow custom image names generated in CSV
* Add labels to kubemacpool deployments for easier filtering

Signed-off-by: Petr Horacek <phoracek@redhat.com>

### CODE REVIEW

**Comment by phoracek** [comment]
@mmirecki @rthallisey @djzager

**Comment by djzager** [comment]
@phoracek does this need backport?

**Comment by phoracek** [comment]
@djzager it doesn't

**Comment by djzager** [comment]
ci test please

**Comment by phoracek** [comment]
ci test please

**Pull request merged**
