### PR TITLE
Build manifests outside of docker.

### PR DESCRIPTION
**Pull request by maya-r**
Needed by CDI v1.23.0 which dynamically generates the CDI CRD,
which requires Go and source code.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
Related to #799

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
We run `make sanity` on Travis to validate the PR,
I don't think we can do this on Travis.

**Review by nunnatsa — CHANGES_REQUESTED** [review]
This solution does not seems like a long time solution, but a temporary fix of another component (CDI) I would prefer new fixed version of CDI instead of this fix.

**Comment by awels** [comment]
https://github.com/kubevirt/containerized-data-importer/pull/1372 fixes it for master, I have the cherry pick already lined up.

**Comment by awels** [comment]
I have release CDI 1.23.1 which includes a fix for this issue.

**Pull request closed without merging**
