### PR TITLE
Update digests of the new operator and webhook 1.3.0 images

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by zcahana — APPROVED** [review]

**Comment by tiraboschi** [comment]
ci/prow/hco-e2e-image-index-aws and ci/prow/hco-e2e-image-index-azure passed:
/override ci/prow/hco-e2e-image-index-gcp

hco-e2e-upgrade-aws passed:
/override ci/prow/hco-e2e-upgrade-azure

**Pull request merged**
