### PR TITLE
Consume kubevirt v0.41.3 to enable upgrades to OCP 4.9

### PR DESCRIPTION
**Pull request by tiraboschi**
kubevirt 0.41.0 is not working on OCP 4.9
due to deprecated APIs that got removed on
k8s 1.22.
Consume kubevirt v0.41.3 that fixes it.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:
```release-note
Consume kubevirt v0.41.3 to enable upgrades to OCP 4.9
```

### CODE REVIEW

**Comment by erkanerol** [comment]
@nunnatsa Will this work without having nmo v0.9.1 on https://quay.io/repository/kubevirt/node-maintenance-operator?tag=latest&tab=tags ?

**Comment by nunnatsa** [comment]
> @nunnatsa Will this work without having nmo v0.9.1 on https://quay.io/repository/kubevirt/node-maintenance-operator?tag=latest&tab=tags ?

not sure. The digest keep pointing to the old version, so this is what we're using. I don't know why the smoke tests fail.

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
