### PR TITLE
fix deploy/deploy.sh with the updated format of dry-run client mode

### LINKED ISSUE #2676: Fix issue in deploy/deploy.sh
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**: 
deploy/deploy.sh script dry run option needs to be fixed. 

**What you expected to happen**:
Use dry-run=client instead of dry-run=true

**How to reproduce it (as minimally and precisely as possible)**:
Run the deploy.sh script and it will report the failure.

**Anything else we need to know?**:

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`): Any version
- Kubernetes version (use `kubectl version`): Any version
- Cloud provider or hardware configuration: Cloud and Baremetal
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by sibiraja-l**
**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
None
```

Fixes #2676

### CODE REVIEW

**Comment by nunnatsa** [comment]
@sibiraja-l - thanks for your contribution!

In order for this PR to be merged, please:
1. sign the commit and re-push it; e.g.
    ```shell
    git commit -s --amend # then also add some description to the commit message
    git push -f
    ```
2. Add some content to the PR description
3. Add some text to the `release-notes` section within the PR description. In this case I think you can just write `None`.
4. add new line to the PR description with `fixes #2676`, to link the PR to the issue and auto close it when the PR is merged.

/ok-to-test

**Comment by sibiraja-l** [comment]
> @sibiraja-l - thanks for your contribution!
> 
> In order for this PR to be merged, please:
> 
> 1. sign the commit and re-push it; e.g.
>    ```shell
>    git commit -s --amend # then also add some description to the commit message
>    git push -f
>    ```
> 2. Add some content to the PR description
> 3. Add some text to the `release-notes` section within the PR description. In this case I think you can just write `None`.
> 4. add new line to the PR description with `fixes #2676`, to link the PR to the issue and auto close it when the PR is merged.
> 
> /ok-to-test

Thank you @nunnatsa I have updated the PR with the above changes. Please proceed with the review.

**Pull request merged**
