### PR TITLE
Cert config defaults

### PR DESCRIPTION
**Pull request by tiraboschi**
Use HyperConvergedCertConfig as an instance

Use HyperConvergedCertConfig as an instance
instead of a pointer to get it properly
defaulted.

Fixes: https://bugzilla.redhat.com/1943217

**Release note**:
```release-note
Use HyperConvergedCertConfig as an instance for proper defaulting
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
Ignoring decreased coverage on zz_generated.deepcopy.go
/override coverage/coveralls

**Comment by tiraboschi** [comment]
/hold
We face an issue with CDI cert on the upgrade lanes:
```
Error from server (InternalError): admission webhook "validate-hco.kubevirt.io" denied the request: Internal error occurred: failed calling webhook "cdi-validate.cdi.kubevirt.io": Post "https://cdi-api.kubevirt-hyperconverged.svc:443/cdi-validate?timeout=30s": x509: certificate has expired or is not yet valid: current time 2021-03-26T07:34:58Z is after 2021-03-26T07:34:22Z
```
let's investigate it.

**Comment by tiraboschi** [comment]
and the issue comes from:
```
spec:
  certConfig:
    ca:
      duration: 0s
      renewBefore: 0s
    server:
      duration: 0s
      renewBefore: 0s
  featureGates:
    withHostPassthroughCPU: false
  infra: {}
  liveMigrationConfig:
    bandwidthPerMigration: 64Mi
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  version: 100.0.0
  workloads: {}
  ```
after the upgrade

**Comment by tiraboschi** [comment]
ignoring reduced coverage on generated code
/override coverage/coveralls

**Review by nunnatsa — APPROVED** [review]

**Pull request merged**
