### PR TITLE
Bump ssp version

### PR DESCRIPTION
**Pull request by ksimon1**
SSP operator now contains api group change in CR and CRDS (https://github.com/MarSik/kubevirt-ssp-operator/pull/144)

```release-note
SSP operator has ssp.kubevirt.io/v1 api group
```

### CODE REVIEW

**Comment by ksimon1** [comment]
I am not sure why sanity check is failing, because i run it and it didn't find anything new:
```
[ksimon@localhost hyperconverged-cluster-operator]$ make sanity 
go fmt ./...
go mod vendor
git diff --exit-code
```

**Comment by orenc1** [comment]
Simone @tiraboschi , shouldn't the new image version of ssp be updated in `hack/build-manifests.sh` as well?
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/hack/build-manifests.sh#L44

**Comment by tiraboschi** [comment]
Closing for #466 which is less intrusive

**Pull request closed without merging**
