### PR TITLE
feat: add deploy vm-console-proxy feature gate

### PR DESCRIPTION
**Pull request by codingben**
**What this PR does / why we need it**:

Add a new feature gate to deploy VM console
proxy resources using SSP operator.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

[✓] PR Message
[✓] Commit Messages
[ ? ] How to test
[ ? ] Unit Tests
[ ? ] Functional Tests
[✓] User Documentation
[✓] Developer Documentation
[ X ] Upgrade Scenario
[ X ] Uninstallation Scenario
[ X ] Backward Compatibility
[✓] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-30283
```

**Release note**:

```release-note
Add deployVmConsoleProxy feature gate
```

### CODE REVIEW

**Comment by codingben** [comment]
> Other than that, please add unit tests and update the default functional test (in tests/func-tests/defaults_test.go).

@nunnatsa I've added functional test, thanks. Can you please tell what kind of unit test it should have? I don't see unit test to another SSP's feature gate, `DeployTektonTaskResources`.

**Comment by codingben** [comment]
@nunnatsa @orenc1 @tiraboschi Can you please review?

**Comment by nunnatsa** [comment]
Hi. Bumping SSP requires some more things. Let's let the bot do that, then add only the new FG changes.

As for the unit test - it could be very simple. Just set the FG in HCO, run NewSSP and check that it propagated to the SSP object.

**Comment by codingben** [comment]
Okay I'm waiting to https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2445 be merged, and then I'll rebase. I'll take a look on the unit tests.

**Comment by nunnatsa** [comment]
> I'll take a look on the unit tests.

See here. This test does more, but the marked line + checking the SSP objects are enough: https://github.com/kubevirt/hyperconverged-cluster-operator/blob/3e127a767232dc5e33ede1f87a3f6c4bb9298af6/controllers/operands/ssp_test.go#L89-L93

**Comment by codingben** [comment]
@nunnatsa Oh okay, thanks! done.

**Comment by nunnatsa** [comment]
@codingben - #2445 was just got merged. let's rebase this one.

**Review by nunnatsa — APPROVED** [review]

**Comment by nunnatsa** [comment]
hco-e2e-kv-smoke-gcp passed
/override ci/prow/hco-e2e-kv-smoke-azure
hco-e2e-operator-sdk-sno-aws passed
/override ci/prow/hco-e2e-operator-sdk-sno-azure
hco-e2e-upgrade-prev-operator-sdk-aws passed
/override ci/prow/hco-e2e-upgrade-prev-operator-sdk-azure

**Pull request merged**
