### PR TITLE
Bump version to 1.9.0

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/lgtm

**Comment by tiraboschi** [comment]
okd-hco-e2e-image-index-aws is green, no need to wait okd-hco-e2e-image-index-gcp.
https://github.com/openshift/release/pull/33358 should definitively help there

/override ci/prow/okd-hco-e2e-image-index-gcp

**Pull request merged**
