### PR TITLE
Update MRO version to v0.3.10

### PR DESCRIPTION
**Pull request by cynepco3hahue**

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@rthallisey  Cna you please take a look?

**Comment by djzager** [comment]
Other than needing a rebase, this LGTM.

**Comment by cynepco3hahue** [comment]
@djzager Thanks for the review, did rebase

**Comment by cynepco3hahue** [comment]
looks like some problem under OpenShift CI
```
2019/09/03 14:10:09 Pod hco-e2e-aws succeeded after 38m30s
2019/09/03 14:10:09 error: unable to signal to artifacts container to terminate in pod hco-e2e-aws, triggering deletion: could not run remote command: container artifacts is not valid for pod hco-e2e-aws
2019/09/03 14:10:09 error: unable to retrieve artifacts from pod hco-e2e-aws: could not read gzipped artifacts: container artifacts is not valid for pod hco-e2e-aws
2019/09/03 14:10:14 error: could not wait for pod 'hco-e2e-aws': it is no longer present on the cluster (usually a result of a race or resource pressure. re-running the job should help)
2019/09/03 14:10:15 Ran for 43m10s
2019/09/03 14:10:15 Submitted failure event to sentry (id=196aa78858b04b099e26342f09ad8673)
```

**Pull request merged**
