### PR TITLE
Update metrics names to meet naming conventions

### PR DESCRIPTION
**Pull request by sradco**
**What this PR does / why we need it**:
Update metrics names to meet naming conventions.
We want the metrics names to follow the naming conventions.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-27054
```

**Release note**:

```release-note
Deprecation notice for the metrics listed in the PR. Please update your systems to use the new metrics names.

kubevirt_hco_out_of_band_modifications_count | kubevirt_hco_out_of_band_modifications_total
kubevirt_hco_unsafe_modification_count | kubevirt_hco_unsafe_modifications
```

### CODE REVIEW

**Comment by avlitman** [comment]
Hi @sradco I'm not sure how it happened since I rebased few times before running the linter but my fork was not up to date so I missed some new metrics that also failing the linter.
The linter output after this changes is:
kubevirt_allocatable_nodes_count: non-histogram and non-summary metrics should not have "_count" suffix
kubevirt_kvm_available_nodes_count: non-histogram and non-summary metrics should not have "_count" suffix
kubevirt_virt_api_up_total: non-counter metrics should not have "_total" suffix
kubevirt_virt_controller_ready_total: non-counter metrics should not have "_total" suffix
kubevirt_virt_controller_up_total: non-counter metrics should not have "_total" suffix
kubevirt_virt_handler_up_total: non-counter metrics should not have "_total" suffix
kubevirt_virt_operator_leading_total: non-counter metrics should not have "_total" suffix
kubevirt_virt_operator_ready_total: non-counter metrics should not have "_total" suffix
kubevirt_virt_operator_up_total: non-counter metrics should not have "_total" suffix
kubevirt_vmi_phase_count: non-histogram and non-summary metrics should not have "_count" suffix

so needs to update this names as well:
kubevirt_allocatable_nodes_count: kubevirt_number_of_allocatable_nodes
kubevirt_kvm_available_nodes_count: kubevirt_kvm_number_of_available_nodes
not sure about this names all are Gauge's type so can't end with count/total:
kubevirt_virt_api_up_total
kubevirt_virt_controller_ready_total
kubevirt_virt_controller_up_total
kubevirt_virt_handler_up_total
kubevirt_virt_operator_leading_total
kubevirt_virt_operator_ready_total
kubevirt_virt_operator_up_total
kubevirt_vmi_phase_count: kubevirt_vmi_number_of_phases or kubevirt_vmi_number_of_phase

**Comment by tiraboschi** [comment]
it's failing on `Sanity Checks / linter Checks (pull_request)`:
```
  Running [/home/runner/golangci-lint-1.53.2-linux-amd64/golangci-lint run --out-format=github-actions --timeout=5m --out-${NO_FUTURE}format line-number] in [] ...
  Error: controllers/alerts/alerts.go:219:6: func `createOutOfBandModificationsRule` is unused (unused)
  func createOutOfBandModificationsRule() monitoringv1.Rule {
 ```

**Comment by sradco** [comment]
@orenc1 @tiraboschi Please review

**Comment by sradco** [comment]
@orenc1 @nunnatsa Can you please review this PR?

**Review by nunnatsa — APPROVED** [review]

**Pull request merged**
