### PR TITLE
[release-1.11] fix typos related to AAQ

### PR DESCRIPTION
**Pull request by nunnatsa**
## What this PR does / why we need it

Fix typos, as result of #2790 code review

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by orenc1 — APPROVED** [review]
/lgtm
/approve

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-operator-sdk-sno-aws lane passed 
/override ci/prow/hco-e2e-upgrade-operator-sdk-sno-azure

**Pull request merged**
