### PR TITLE
Bump VM_IMPORT to v0.2.2

### PR DESCRIPTION
**Pull request by pkliczewski**
Bump VM_IMPORT to v0.2.2

**Release note**:
```release-note
Bump VM_IMPORT to v0.2.2
```

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by pkliczewski** [comment]
@tiraboschi @nunnatsa This version contains import from vmware which got exception to be merged into 2.5 branch.

**Comment by pkliczewski** [comment]
@fdupont-redhat FYI

**Comment by ovirt-infra** [comment]
All tests passed

**Review by nunnatsa — CHANGES_REQUESTED** [review]
please run `make build-manifest` to re-generate the manifest files correctly.

**Comment by orenc1** [comment]
> please run `make build-manifest` to re-generate the manifest files correctly.

and update `go.mod` with the updated version for `github.com/kubevirt/vm-import-operator`, then run:
```
go mod vendor
go mod tidy
```

**Comment by pkliczewski** [comment]
> please run `make build-manifest` to re-generate the manifest files correctly.

This is exactly what I did. I wonder why the script end like this. I haven't check what was generated. It seems like I need to stop to trust those tools.

**Comment by ovirt-infra** [comment]
All tests passed

**Review by orenc1 — CHANGES_REQUESTED** [review]
please update `go.mod` with the updated version for `github.com/kubevirt/vm-import-operator`
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/go.mod#L15
then run:
```
go mod vendor
go mod tidy
```

**Comment by pkliczewski** [comment]
I opened https://github.com/kubevirt/hyperconverged-cluster-operator/issues/817 to track `build-manifest` issue.

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by pkliczewski** [comment]
> please update `go.mod` with the updated version for `github.com/kubevirt/vm-import-operator`
> https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/go.mod#L15
> then run:
> 

@orenc1 No changes to go.mod. what do you expect to see there?

**Comment by tiraboschi** [comment]
hco-e2e-azure lane succeeded.
/override ci/prow/hco-e2e-aws
hco-e2e-upgrade-aws lane succeeded.
/override ci/prow/hco-e2e-upgrade-azure

**Comment by tiraboschi** [comment]
hco-e2e-image-index-aws and hco-e2e-image-index-gcp passed CI
/override ci/prow/hco-e2e-image-index-azure

**Comment by tiraboschi** [comment]
> > please update `go.mod` with the updated version for `github.com/kubevirt/vm-import-operator`
> > https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/go.mod#L15
> > then run:
> 
> @orenc1 No changes to go.mod. what do you expect to see there?

`v0.2.1` -> `v0.2.2` on https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/go.mod#L15

/hold

**Comment by pkliczewski** [comment]
> `v0.2.1` -> `v0.2.2` on https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/go.mod#L15

@tiraboschi Done. It is interesting that I did it for the first time. Have I missed it in the past or is it something new?

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by pkliczewski** [comment]
@tiraboschi I still see the same job failure issue as before the rebase:

> error: error executing jsonpath "{range .status.conditions[*]}{.type}{'\\t'}{.status}{'\\t'}{.message}{'\\n'}{end}": Error executing template: not in range, nothing to end.

Is this still expected?

**Comment by orenc1** [comment]
@pkliczewski , please rebase to consume the CI upgrade test unlock that was merged in #820 
your PR can't be rebased by us, since you used a master branch.

Thanks

**Comment by ovirt-infra** [comment]
All tests passed

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
