### PR TITLE
[release-1.4] Bump KUBEVIRT to v0.41.0

### PR DESCRIPTION
**Pull request by nunnatsa**
Bump KUBEVIRT to v0.41.0
Executed by HCO Release-Bumper Bot.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Reviewer Checklist**

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Bump KUBEVIRT to v0.41.0
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
Something is not working. Closing and reopening.

**Comment by tiraboschi** [comment]
/hold
on all the upgrade lanes HCO is constantly stuck with:
```                   
INFO[2021-05-14T09:59:57Z]   - lastHeartbeatTime: "2021-05-14T09:59:11Z" 
INFO[2021-05-14T09:59:57Z]     lastTransitionTime: "2021-05-14T09:38:46Z" 
INFO[2021-05-14T09:59:57Z]     message: HCO is now upgrading to version 100.0.0 
INFO[2021-05-14T09:59:57Z]     reason: HCOUpgrading                     
INFO[2021-05-14T09:59:57Z]     status: "True"                           
INFO[2021-05-14T09:59:57Z]     type: Progressing 
```

**Comment by tiraboschi** [comment]
On HCO pod logs for the upgrade timeframe we see in a loop (155 instance in 4 minutes):
`Reconciling an externally updated KubeVirt's Spec to its opinionated values`

This smells like an upgrade bug.

**Comment by tiraboschi** [comment]
Still trying to investigate the upgrade failures

**Comment by tiraboschi** [comment]
deploy/images.csv and deploy/images.env contain outdated images, regenerating all the manifests with the right ones.

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
