### PR TITLE
Build unstable index image from prev unstable index image

### PR DESCRIPTION
**Pull request by tiraboschi**
`Build and Push Images` post-submit action
is currently failing on:
```
+ /home/runner/work/hyperconverged-cluster-operator/hyperconverged-cluster-operator/linux-amd64-opm index add --bundles quay.io/kubevirt/hyperconverged-cluster-bundle@sha256:0f70f15e60216f264cc563293c42d524f98096763bcdb8c9dc619c7c4ed66ce2 --from-index=quay.io/kubevirt/hyperconverged-cluster-index:1.7.0 --tag quay.io/kubevirt/hyperconverged-cluster-index:1.8.0-unstable -u podman --mode semver
time="2022-06-03T11:53:31Z" level=info msg="building the index" bundles="[quay.io/kubevirt/hyperconverged-cluster-bundle@sha256:0f70f15e60216f264cc563293c42d524f98096763bcdb8c9dc619c7c4ed66ce2]"
time="2022-06-03T11:53:31Z" level=info msg="Pulling previous image quay.io/kubevirt/hyperconverged-cluster-index:1.7.0 to get metadata" bundles="[quay.io/kubevirt/hyperconverged-cluster-bundle@sha256:0f70f15e60216f264cc563293c42d524f98096763bcdb8c9dc619c7c4ed66ce2]"
Error: error resolving name : quay.io/kubevirt/hyperconverged-cluster-index:1.7.0: not found
```
See: https://github.com/kubevirt/hyperconverged-cluster-operator/runs/6725113703?check_suite_focus=true
because we still have to tag 1.7.0

Fix it.

Consume up to date version of opm tool

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
ignoring false positive on coverage
/override coverage/coveralls

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
