### PR TITLE
Report unit test coverage using goveralls

### PR DESCRIPTION
**Pull request by rwsu**

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by rwsu** [comment]
This PR will require someone with admin permissions to this repository to enable the repo in coveralls.io for it to start reporting the code coverage statistics. The build is failing because the repo isn't enabled in coveralls.io.

**Comment by rthallisey** [comment]
Can you add the coverage report to the README? For example: https://github.com/kubevirt/kubevirt/blob/master/README.md#kubevirt

**Comment by rwsu** [comment]
@rthallisey added coverage, build status, and go report to the README. The build status and coverage badges are based on information gathered from master builds, if there are no builds on the master branch in travis-ci, it will display "unknown" for those badges. 

I don't have pemissions to see whether we have master builds in travis-ci. To activate master builds I think all that needs to be done is click on the badge and activate the repo in travis-ci. I tried in on my fork of the repo, and although pull request builds are active without repo activation, I think the master builds are not without activation.

**Pull request merged**
