### PR TITLE
add new app for webhook

### PR DESCRIPTION
**Pull request by nunnatsa**
Copy the webhook code from the operator into a new app for webhook only.

This is in order to split #960, because it can't pass test before a change in CI that depends in the new app (dead loop).

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
closing and re-opening to release caches

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
