### PR TITLE
Bump CNAO v0.42.0

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horacek <phoracek@redhat.com>

**Release note**:

```release-note
Bump CNAO v0.42.0
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Review by tiraboschi — APPROVED** [review]

**Comment by tiraboschi** [comment]
hco-e2e and hco-e2e-upgrade-prev already passed on AWS, no need to wait for the same lanes on azure.
/override ci/prow/hco-e2e-azure
/override ci/prow/hco-e2e-upgrade-prev-azure

**Pull request merged**
