### PR TITLE
Fix template files.

### PR DESCRIPTION
**Pull request by lveyde**
Due to the macro processing issue, an empty line was inserted as the very first line of CRB files.
This was causing issues with tools that use strict checking of the YAML file syntax.
Specifically it was causing the build using the latest origin-operator-registry image to fail.
This patch fixes the templates.

Signed-off-by: Lev Veyde <lveyde@redhat.com>

### CODE REVIEW

**Comment by lveyde** [comment]
OK, replaced by another set of patches.

Please see PR#155.

**Comment by lveyde** [comment]
Per request added re-based set of patches to this PR as well.

**Comment by rthallisey** [comment]
ci test please

**Comment by djzager** [comment]
Which PR is winning here, this or #155 ?

**Comment by rthallisey** [comment]
I think #155 can be closed.

**Pull request merged**
