### PR TITLE
Doc: Add a document explaining how to consume HCO metrics locally

### PR DESCRIPTION
**Pull request by jcanocan**
This PR adds a new entry in the documentation section explaining how to set Prometheus for consuming HCO metrics in a local cluster.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
In https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2226 we are providing better guidance for CRC.
Can you please mention that with CRC executing
```$ crc config set enable-cluster-monitoring true```
(and giving it much more RAM) will be enough?

**Comment by jcanocan** [comment]
> In #2226 we are providing better guidance for CRC. Can you please mention that with CRC executing `$ crc config set enable-cluster-monitoring true` (and giving it much more RAM) will be enough?

Done. We can also wait until #2226 is merged and reference the section in this document.

**Comment by machadovilaca** [comment]
@jcanocan @tiraboschi 

This makes sense, I already found myself having to do this to get metrics to work on `kubevirtci`, but personally, I think we should solve this another way.
Right now, HCO only provides support for monitoring in OpenShift clusters. In my opinion, I think we should, at least, create and reconcile the Service to expose metrics and the Prometheus ServiceMonitor on plain Kubernetes clusters too.

Then, the only thing needed to get metrics working on both `crc` and `kubevirtci` out of the box would be to make sure the Prometheus is running in each, with `$ crc config set enable-cluster-monitoring true` or `$ export KUBEVIRT_DEPLOY_PROMETHEUS=true`, respectively.

**Comment by jcanocan** [comment]
> @jcanocan @tiraboschi
> 
> This makes sense, I already found myself having to do this to get metrics to work on `kubevirtci`, but personally, I think we should solve this another way. Right now, HCO only provides support for monitoring in OpenShift clusters. In my opinion, I think we should, at least, create and reconcile the Service to expose metrics and the Prometheus ServiceMonitor on plain Kubernetes clusters too.
> 
> Then, the only thing needed to get metrics working on both `crc` and `kubevirtci` out of the box would be to make sure the Prometheus is running in each, with `$ crc config set enable-cluster-monitoring true` or `$ export KUBEVIRT_DEPLOY_PROMETHEUS=true`, respectively.

Hi! Many thanks for the feedback.

I agree. I would like to open this discussion to alerts. As far as I know, as it is now, alerts are not working on `kubevirtci` out-of-the-box. We can either document how to deploy them or to make HCO deploy them. This can be done either as part of Prometheus deploy, using the var `KUBEVIRT_DEPLOY_PROMETHEUS` or separately using another var like `KUBEVIRT_DEPLOY_PROMETHEUS_ALERTS=true`. What do you think?

**Comment by jcanocan** [comment]
>Right now, HCO only provides support for monitoring in OpenShift clusters. In my opinion, I think we should, at least, create and reconcile the Service to expose metrics and the Prometheus ServiceMonitor on plain Kubernetes clusters too.

Hi @machadovilaca @tiraboschi Do we have any plans to support this in the sort-term? If no, we can push this forward and drop it or updated it later. WDYT?

**Pull request closed without merging**
