### PR TITLE
Upgrade cert-manager to v1.14.4

### PR DESCRIPTION
**Pull request by inteon**
**What this PR does / why we need it**:

cert-manager v1.5.4 has been EOL for a long time: https://cert-manager.io/docs/releases/
It is important to upgrade to a supported version which contains a lot of bugfixes and CVE fixes.

v1.14.4 release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.14.4

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
> cert-manager v1.5.4 has been EOL for a long time: https://cert-manager.io/docs/releases/ It is important to upgrade to a supported version which contains a lot of bugfixes and CVE fixes.

thanks @inteon ,
is there any good reason to stick on v1.13.4 instead of the latest ( v1.14.3 ) ?

**Comment by inteon** [comment]
> > cert-manager v1.5.4 has been EOL for a long time: https://cert-manager.io/docs/releases/ It is important to upgrade to a supported version which contains a lot of bugfixes and CVE fixes.
> 
> thanks @inteon , is there any good reason to stick on v1.13.4 instead of the latest one ( v1.14.3 ) ?

There is a bug in v1.14.3 that we still have to fix (we will do this in one of the following days).

**Comment by nunnatsa** [comment]
Hi @inteon. e2e is failing (e.g. https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/2836/pull-hyperconverged-cluster-operator-e2e-k8s-1.27/1765723298781466624):

```
Error from server (NotFound): error when creating "_out/cert-manager.yaml": namespaces "cert-manager" not found
```

Could you please add the creation of the namespace to the deploy scrips, or maybe add a new namespace yaml?

**Comment by inteon** [comment]
> Hi @inteon. e2e is failing (e.g. https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/2836/pull-hyperconverged-cluster-operator-e2e-k8s-1.27/1765723298781466624):
> 
> ```
> Error from server (NotFound): error when creating "_out/cert-manager.yaml": namespaces "cert-manager" not found
> ```
> 
> Could you please add the creation of the namespace to the deploy scrips, or maybe add a new namespace yaml?

My mistake, I removed the namespace because I thought I did not see it in the existing yaml.
I updated the yaml, and it now 100% matches the upstream manifest.

**Comment by inteon** [comment]
The following error seems to occur:
```
/home/prow/go/src/github.com/kubevirt/hyperconverged-cluster-operator/_kubevirtci/cluster-up//cluster/k8s-provider-common.sh: line 181: kubectl: command not found
```
Do you know how this is related to this PR?

**Comment by tiraboschi** [comment]
> Do you know how this is related to this PR?

No, I think it was just a temporary outage introduced by one of our CI images.

**Comment by inteon** [comment]
> > cert-manager v1.5.4 has been EOL for a long time: https://cert-manager.io/docs/releases/ It is important to upgrade to a supported version which contains a lot of bugfixes and CVE fixes.
> 
> thanks @inteon , is there any good reason to stick on v1.13.4 instead of the latest one ( v1.14.3 ) ?

We just released v1.14.4. I updated the PR to point to that release.

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
