### PR TITLE
Run unit tests with a symlink to actual upgradePatches.json

### PR DESCRIPTION
**Pull request by tiraboschi**
upgradePatches.json used for unit test in the past
was a symlink to the actual file used in the
final image.
It probably got a real file in some refactor activity,
let's restore it as a symlink.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by orenc1** [comment]
> /rebase

Rebase-Bot can't rebase when there are merge conflicts.
Fixing the error reporting in #1959

**Comment by orenc1** [comment]
just testing the error reporting of rebase bot
/rebase

**Comment by nunnatsa** [comment]
just testing the error reporting of rebase bot
/rebase

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
