### PR TITLE
Bump KUBEVIRT to v0.36.0

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
Bump KubeVirt to v0.36.0
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by orenc1** [comment]
I added waiting for the webhook pod to be ready before the HCO CR creation, to avoid failing on the webhook.

**Review by orenc1 — APPROVED** [review]

**Pull request merged**
