### PR TITLE
Update the default hardcodedObsoleteCPUModels

### PR DESCRIPTION
**Pull request by Barakmor1**
**What this PR does / why we need it**:
The default ObsoleteCPUModels has changed in kv:
https://github.com/kubevirt/kubevirt/pull/11671/commits/0f4f837deb6fde6ca258da642ec3495acdc5fcb7

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket

```

**Release note**:

```release-note
Adding Opteron_G1 AND Opteron_G2 to the default ObsoleteCPUModels
```

### CODE REVIEW

**Review by nunnatsa — COMMENTED** [review]
/lgtm
/approve
/cherry-pick release-1.12 release-1.11 release-1.10

**Comment by Barakmor1** [comment]
@nunnatsa Can we back-port it for 4.14 as well?

**Comment by nunnatsa** [comment]
@Barakmor1 see #2935

**Pull request merged**
