### PR TITLE
[release-1.8]: Kubevirt: Enforce limits & requests by a configurable ratio

### PR DESCRIPTION
**Pull request by iholder101**
Manual backport of https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2206

**Release note**:

```release-note
Kubevirt: Enforce limits & requests by a configurable ratio
```

### CODE REVIEW

**Comment by iholder101** [comment]
/cc @nunnatsa @orenc1 @tiraboschi 

Can you please take a look?

**Comment by tiraboschi** [comment]
Bumping version first to preparare bundle image for upgrade lanes.
CI will be enabled merging https://github.com/openshift/release/pull/37169

/override ci/prow/hco-e2e-image-index-aws
/override ci/prow/hco-e2e-image-index-azure
/override ci/prow/hco-e2e-image-index-gcp
/override ci/prow/hco-e2e-image-index-sno-aws
/override ci/prow/hco-e2e-image-index-sno-azure
/override ci/prow/hco-e2e-kv-smoke-azure
/override ci/prow/hco-e2e-kv-smoke-gcp
/override ci/prow/hco-e2e-upgrade-index-aws
/override ci/prow/hco-e2e-upgrade-index-azure
/override ci/prow/hco-e2e-upgrade-index-sno-aws
/override ci/prow/hco-e2e-upgrade-index-sno-azure
/override ci/prow/hco-e2e-upgrade-prev-index-aws
/override ci/prow/hco-e2e-upgrade-prev-index-azure
/override ci/prow/hco-e2e-upgrade-prev-index-sno-aws
/override ci/prow/hco-e2e-upgrade-prev-index-sno-azure
/override ci/prow/okd-hco-e2e-image-index-aws
/override ci/prow/okd-hco-e2e-image-index-gcp
/override ci/prow/okd-hco-e2e-upgrade-index-aws
/override ci/prow/okd-hco-e2e-upgrade-index-gcp

**Comment by tiraboschi** [comment]
sorry, wrong comment

**Comment by iholder101** [comment]
Blocked because of: https://github.com/kubevirt/kubevirt/issues/9434.

**Comment by iholder101** [comment]
can you PTAL? @tiraboschi

**Comment by tiraboschi** [comment]
ignoring roundings on coverage
/override coverage/coveralls

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
