### PR TITLE
SSP: update manifests to v1.0.3

### PR DESCRIPTION
**Pull request by fromanirh**
Changes after 1.0.1 are only in manifests, not in the pkg/API.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by rthallisey** [comment]
Will need to be backported to release-2.0 branch

**Comment by rthallisey** [comment]
@fromanirh ping me if you need any help with the backport

**Comment by fromanirh** [comment]
@rthallisey sure, on it

**Pull request merged**
