### PR TITLE
Consume latest kubevirt nightly waiting for v0.40.0

### PR DESCRIPTION
**Pull request by tiraboschi**
Consume latest kubevirt nightly waiting for v0.40.0

pinning to kubevirt 20210331_4987c1102
until we get a tagged build for v0.40.0
to unlock future work.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
@davidvossel 
all of our upgrade lanes are failing on:
```
virt-handler-92wp7                                    0/1     CrashLoopBackOff   9          28m
virt-handler-xn5w8                                    0/1     CrashLoopBackOff   9          28m
virt-handler-zr4z9                                    0/1     CrashLoopBackOff   9          28m
```
due to 
```
{"component":"virt-handler","level":"error","msg":"node-labeller could not load cpu info: open /var/lib/kubevirt-node-labeller/cpu_map: no such file or directory","pos":"node_labeller.go:74","timestamp":"2021-03-31T12:47:44.926047Z"}
panic: open /var/lib/kubevirt-node-labeller/cpu_map: no such file or directory

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc0000a9680)
	cmd/virt-handler/virt-handler.go:356 +0x2968
main.main()
	cmd/virt-handler/virt-handler.go:534 +0x6e
```

Any hint?

**Comment by davidvossel** [comment]
@ksimon1 The node labeller changes are causing virt-handler to crash on the HCO's CI, can you take a look?

**Comment by tiraboschi** [comment]
Still reproducible with 20210331_4987c1102 (although not systematic on all the nodes):
```
virt-handler-6rkkz                                    0/1     CrashLoopBackOff   6          12m
virt-handler-k8vd9                                    0/1     CrashLoopBackOff   6          14m
virt-handler-tjnwh                                    1/1     Running            0          19m
```

and where it fails we get:
```
{"component":"virt-handler","level":"error","msg":"node-labeller could not load cpu info: open /var/lib/kubevirt-node-labeller/cpu_map: no such file or directory","pos":"node_labeller.go:74","timestamp":"2021-03-31T15:31:33.587454Z"}
panic: open /var/lib/kubevirt-node-labeller/cpu_map: no such file or directory

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000001b00)
	cmd/virt-handler/virt-handler.go:356 +0x2968
main.main()
	cmd/virt-handler/virt-handler.go:534 +0x6e
```

see https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/1220/pull-ci-kubevirt-hyperconverged-cluster-operator-master-hco-e2e-upgrade-prev-aws/1377261662561636352/artifacts/hco-e2e-upgrade-prev-aws/gather-extra/artifacts/pods/kubevirt-hyperconverged_virt-handler-6rkkz_virt-handler.log

**Comment by tiraboschi** [comment]
I just filed https://github.com/kubevirt/kubevirt/issues/5364

**Comment by ksimon1** [comment]
This should fix the labeller, when it doesn't have access to kvm https://github.com/kubevirt/kubevirt/pull/5368

**Comment by tiraboschi** [comment]
https://github.com/kubevirt/kubevirt/pull/5368 got merged, now we can rebase this

**Comment by tiraboschi** [comment]
Closing for #1243

**Pull request closed without merging**
