### PR TITLE
[release-1.9] Expose defaultRuntimeClass

### PR DESCRIPTION
**Pull request by tiraboschi**
Expose a knob to let the cluster admin
set a default RuntimeClass for all the VMIs pods.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2217910

This is a manual cherry-pick of #2370

**What this PR does / why we need it**:

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-30333
```

**Release note**:

```release-note
expose defaultRuntimeClass to let the cluster admin set a default RuntimeClass for VMIs pods
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
ignore coverage roundings
/override coverage/coveralls

**Review by nunnatsa — APPROVED** [review]

**Pull request merged**
