### PR TITLE
Update DataImportCron of Fedora to latest tag

### PR DESCRIPTION
**Pull request by 0xFelix**
A latest tag for the Fedora containerdisk was added in [1]. Use that
instead of explicitly specifying a version tag to be always up to date.

[1] https://github.com/kubevirt/containerdisks/commit/db30dfc6f9cf190cda17ef5488be965433ab1e42

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by ifireball** [comment]
@tiraboschi for future reference: to enable bug tracking, please attach bug information for PRs like this in the future by either pasting the full bug URL to the PR description or using this syntax: RHBZ#2088464.

**Pull request merged**
