### PR TITLE
move KV and CDI to the new operand pkg

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

This is the 2nd (2/10) commit of the reconcile refactoring. 

It introduces the `Operand` interface, and uses it to handle KubeVirt and CDI CRs.

The current `ensure` methods of KV and CDI are left, but their content was move to the new `operand` package.

The reconciler holds a temporary map of handlers, currently only with KV and CDI handlers. This will be removed later.

Some code in the PR is an intrastructure for all the operands, so it's larger than the following PRs, that will only deal with a single operand.

The new `commonTestUtis` package also added, to serve unit test both in the `hyperconvereged` and the `operands` packages.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
This is the first commit out of 10. The final covarage was +3.5%

/override coverage/coveralls

**Comment by nunnatsa** [comment]
/hold

waiting for #823

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by nunnatsa** [comment]
rebased with #823. 

/unhold

**Comment by nunnatsa** [comment]
This is the second commit out of 10. The final covarage was +3.5%

/override coverage/coveralls

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
