### PR TITLE
Move v2vvmware CRD under v2v.kubevirt.io API group

### PR DESCRIPTION
**Pull request by mareklibra**
Former group: kubevirt.io

**Release note**:

```release-note
The v2vvmware CRD has been moved from the kubevirt.io API group to the v2v.kubevirt.io.
```

### CODE REVIEW

**Comment by mareklibra** [comment]
@tiraboschi , can you have a look at the failing CI tests here, please? Is it a flake? Thank you.

**Comment by tiraboschi** [comment]
> @tiraboschi , can you have a look at the failing CI tests here, please? Is it a flake? Thank you.

In order to be able to test this we have to merge https://github.com/kubevirt/hyperconverged-cluster-operator/pull/506 and then rebase this one

**Pull request merged**
