### PR TITLE
Update deploy.sh

### PR DESCRIPTION
**Pull request by CJCShadowsan**
Comment out missing node-maintenance entry that prevents deploy.sh completing.

Signed-off-by: Chris Coates <christopher.james.coates@gmail.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Removed a node-maintenance entry within this script that causes the remainder of the script to fail. Can be uncommented if node-maintenance is re-instated.

Signed-off-by: Chris Coates <christopher.james.coates@gmail.com>
```

### CODE REVIEW

**Review by nunnatsa — CHANGES_REQUESTED** [review]
Thank you @CJCShadowsan for your PR, and welcome to the community!

First, please sign your commit.
As for the change you made - good catch. Please remove the wrong line instead of commenting it out.

**Comment by CJCShadowsan** [comment]
> Thank you @CJCShadowsan for your PR, and welcome to the community!
> 
> First, please sign your commit. As for the change you made - good catch. Please remove the wrong line instead of commenting it out.

I'd love to sign my commit - but unsure how?

Happy to remove the line instead of commenting it, but didn't know whether it would be making it back in or not in future, hence commenting.

**Comment by tiraboschi** [comment]
> I'd love to sign my commit - but unsure how?

Please see: https://github.com/apps/dco

**Comment by orenc1** [comment]
> > Thank you @CJCShadowsan for your PR, and welcome to the community!
> > First, please sign your commit. As for the change you made - good catch. Please remove the wrong line instead of commenting it out.
> 
> I'd love to sign my commit - but unsure how?
> 
> Happy to remove the line instead of commenting it, but didn't know whether it would be making it back in or not in future, hence commenting.

Hi,
To sign-off you commit, use `git commit -s` and it will append `Signed-off-by:` to you commit.

Node Maintenance Operator is now a standalone operator that is no longer shipped within kubevirt-hyperconverged, it is available separately through OperatorHub.io at:
https://www.medik8s.io/maintenance-node/

So it is safe to remove it from `deploy.sh`.

In general, we are not commenting out code. If code is not needed, we remove it. That's why we have source control (git).

Thanks

**Comment by tiraboschi** [comment]
Can you please squash your commits?

**Comment by orenc1** [comment]
@CJCShadowsan , you need **all** of your commits in the PR to be signed-off.
Please rebase and squash your commits to a single commit, that is signed-off. thanks

**Comment by CJCShadowsan** [comment]
Y'know what? Let's start again. Lol!

One min.

**Comment by razo7** [comment]
FYI : NMO is recently available in OperatorHub.io: https://operatorhub.io/operator/node-maintenance-operator @orenc1

**Pull request closed without merging**
