### PR TITLE
Enable PSA FG on Kubevirt

### PR DESCRIPTION
**Pull request by tiraboschi**
Enable PSA FG on Kubevirt to be compatible with
k8s >= 1.24 and derivates with PSA in enforcing mode.

Once available also in older versions of Kubevirt, we will have also to backport it to release-1.6
and release-1.7.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Enable PSA FG on Kubevirt
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by oshoval** [comment]
Now it uses the right image, lets see it pass ;]

**Pull request merged**
