### PR TITLE
Override-bot: add missing \n to split multiple commands

### PR DESCRIPTION
**Pull request by tiraboschi**
Override-bot: add missing \n to split multiple commands

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Review by orenc1 — APPROVED** [review]

**Comment by ovirt-infra** [comment]
All tests passed

**Review by orenc1 — APPROVED** [review]

**Comment by orenc1** [comment]
/hold
already fixed in #822

**Comment by tiraboschi** [comment]
Closing

**Pull request closed without merging**
