### PR TITLE
Added oVirt v2v provider

### PR DESCRIPTION
**Pull request by jakub-dzon**
Signed-off-by: Jakub Dzon <jdzon@redhat.com>

**Release note**:
```release-note
- Added oVirt provider that is responsible for providing oVirt virtual machines information to the UI (for the purpose of importing those VMs to CNV).
```

### CODE REVIEW

**Comment by jakub-dzon** [comment]
@pkliczewski, @tiraboschi - please review

**Comment by pkliczewski** [comment]
:tada:

**Pull request merged**
