### PR TITLE
Revert "Enable PSA FG on Kubevirt (#2093)"

### PR DESCRIPTION
**Pull request by tiraboschi**
This reverts commit 4731026dec411bb0a0f5ce3153f41ff948390a34.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Revert PSA FG on Kubevirt
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-prev-index-sno-aws succeeded
/override ci/prow/hco-e2e-upgrade-prev-index-sno-azure

**Comment by tiraboschi** [comment]
hco-e2e-image-index-aws
/override ci/prow/hco-e2e-image-index-azure

hco-e2e-image-index-sno-aws succeeded
/override ci/prow/hco-e2e-image-index-sno-azure

hco-e2e-upgrade-index-aws succeeded
/override ci/prow/hco-e2e-upgrade-index-azure

hco-e2e-upgrade-index-sno-aws succeeded
/override ci/prow/hco-e2e-upgrade-index-sno-azure

hco-e2e-upgrade-prev-index-aws succeeded
/override ci/prow/hco-e2e-upgrade-prev-index-azure

**Comment by tiraboschi** [comment]
it failed a single test that is not strictly related to PSA:
```
• [FAILED] [279.174 seconds]
[rfe_id:151][crit:high][vendor:cnv-qe@redhat.com][level:component][sig-compute]CloudInit UserData [rfe_id:151][crit:medium][vendor:cnv-qe@redhat.com][level:component]A new VirtualMachineInstance with cloudInitConfigDrive networkData [It] [test_id:4622]should have cloud-init meta_data with tagged devices
tests/vmi_cloudinit_test.go:457
```

let's ignore it for now, we will eventually quarantine it to move forward.

/override ci/prow/hco-e2e-kv-smoke-azure
/override ci/prow/hco-e2e-kv-smoke-gcp

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
