### PR TITLE
Revert "Use predicates to prevent noisy reconcile (#318)"

### PR DESCRIPTION
**Pull request by tiraboschi**
This reverts commit f4db8ee.

Signed-off-by: Simone Tiraboschi stirabos@redhat.com

### CODE REVIEW

**Comment by tiraboschi** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci test please

**Comment by djzager** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci test please

**Pull request merged**
