### PR TITLE
bump cnao to 0.35.1

### PR DESCRIPTION
**Pull request by phoracek**
Make HCO in sync with latest master version of CNAO including the latest
fix of json schema validation of ClusterNetworkAddons CRD.

Signed-off-by: Petr Horacek <phoracek@redhat.com>

**Release note**:

```release-note
Bump CNAO to 0.35.1
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
I fear we can only merge this in a single PR with https://github.com/kubevirt/hyperconverged-cluster-operator/pull/536 if we want to see a fully green CI

**Comment by phoracek** [comment]
@tiraboschi should I push this commit to your PR then? (Not 100% sure I can)

**Comment by tiraboschi** [comment]
@phoracek I already did that

**Comment by tiraboschi** [comment]
@phoracek can you please on upstream/master?

**Comment by tiraboschi** [comment]
ci/prow/hco-e2e-upgrade-aws currently runs on OCP 4.5 and it's going to fail due to a side effect in the fix of https://bugzilla.redhat.com/1825330
It will be addressed on operator-framework/operator-lifecycle-manager#1470 on OLM side.
Temporary ignoring it
/override ci/prow/hco-e2e-upgrade-aws

**Pull request merged**
