### PR TITLE
Avoid hard-coding CI registry URL 

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
obsolete

**Pull request closed without merging**
