### PR TITLE
Remove cert rotation tests

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by orenc1** [comment]
@tiraboschi, needs rebase after merging #562 ?
(a new component has been added)

**Comment by tiraboschi** [comment]
Unfortunately we are completely stuck with flaky CI,
we have at lest 4 pending PRs:
- https://github.com/kubevirt/hyperconverged-cluster-operator/pull/592
- https://github.com/kubevirt/hyperconverged-cluster-operator/pull/590
- https://github.com/kubevirt/hyperconverged-cluster-operator/pull/584
- https://github.com/kubevirt/hyperconverged-cluster-operator/pull/580
stuck continously failing on this test.
Let's disable it until we find how to make it properly working.

**Pull request merged**
