### PR TITLE
Test node placement APIs

### PR DESCRIPTION
**Pull request by tiraboschi**
Test node placement APIs

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by nunnatsa** [comment]
@tiraboschi - I think we can close this PR, because we have working tests in #886

**Comment by tiraboschi** [comment]
Obsolete

**Pull request closed without merging**
