### PR TITLE
Bump KUBEVIRT_VMWARE v2.0.0-5

### PR DESCRIPTION
**Pull request by pkliczewski**
Bump KUBEVIRT_VMWARE to v2.0.0-5

**Release note**:
```release-note
Bump KUBEVIRT_VMWARE to v2.0.0-5
```

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by pkliczewski** [comment]
Please backport it to v2.4 branch. This version contains a fix for a blocker [bug](https://bugzilla.redhat.com/1851886)

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
> Please backport it to v2.4 branch. This version contains a fix for a blocker [bug](https://bugzilla.redhat.com/1851886)

After this change you have to explicitly run `hack/build-manifests.sh` to regenerate all the manifest files.

**Comment by pkliczewski** [comment]
> After this change you have to explicitly run `hack/build-manifests.sh` to regenerate all the manifest files.

@tiraboschi PR updates.

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by pkliczewski** [comment]
> Please backport it to v2.4 branch. This version contains a fix for a blocker [bug](https://bugzilla.redhat.com/1851886)

@orenc1 @nunnatsa was this backported?

**Comment by nunnatsa** [comment]
> > Please backport it to v2.4 branch. This version contains a fix for a blocker [bug](https://bugzilla.redhat.com/1851886)
> 
> @orenc1 @nunnatsa was this backported?

#689

**Pull request merged**
