### PR TITLE
Rename HCO alert names

### PR DESCRIPTION
**Pull request by machadovilaca**
**What this PR does / why we need it**:

HCO alerts have very extensive names which is causing issues in the docs. This PR renames these alerts.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-31133
```

**Release note**:

```release-note
Rename HCO alert names
```

### CODE REVIEW

**Comment by machadovilaca** [comment]
Please review the names of the alerts. Tests are failing because we also need to update the runbooks as in https://github.com/kubevirt/monitoring/pull/188, but I want to get your ack on the name changes before asking for a review there
@tiraboschi @nunnatsa

**Comment by sradco** [comment]
Please update the alerts names based on the changes in https://github.com/kubevirt/monitoring/pull/188

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
