### PR TITLE
Run smoke tests with cluster specific storage

### PR DESCRIPTION
**Pull request by tiraboschi**
Run smoke tests with cluster specific storage
classes.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]

**Comment by tiraboschi** [comment]
Passed on GCP where we see:
```
Configuring the test environment for a GCP cluster
```
in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/2080/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp/1570026544825372672/artifacts/hco-e2e-kv-smoke-gcp/e2e-test/build-log.txt

still failing to get a properly working Azure cluster

**Comment by tiraboschi** [comment]
/unhold
Smoke tests successfully completed on azure and GCP, see:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/2080/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure/1577194699372892160
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/2080/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-gcp/1577194699410640896

**Pull request merged**
