### PR TITLE
Avoid requiring python3 graphviz in Dockerfile.functest.ci

### PR DESCRIPTION
**Pull request by tiraboschi**
graphviz is executed only during the nightly job,
avoid requiring python3 and graphviz in
Dockerfile.functest.ci

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by orenc1** [comment]
failing due to a problem fixed in #1932 
(which contains also this PR changes)

**Comment by orenc1** [comment]
done in #1932, along with other fixes.

**Pull request closed without merging**
