### PR TITLE
bump cnao to 0.15.0

### PR DESCRIPTION
**Pull request by phoracek**
0.15.0:
* Contains KubeMacPool fixes and stability improvements.

0.14.0 https://github.com/kubevirt/hyperconverged-cluster-operator/pull/269
* add operator version to CSV generator
* reduce kubemacpool resource requirements
* drop Failing condition from pre-0.12.0 versions

### CODE REVIEW

**Comment by phoracek** [comment]
@djzager @rthallisey please take a look

**Comment by rthallisey** [comment]
ci failure is unrelated.  Created an [issue](https://github.com/kubevirt/hyperconverged-cluster-operator/issues/275) to track.

**Pull request merged**
