### PR TITLE
[CNV-40095] ConsolePlugin: prevent plugin entry assets from caching

### PR DESCRIPTION
**Pull request by orenc1**
**What this PR does / why we need it**:
Disabling the caching of `plugin-manifest.json` and `plugin-entry.js` should mitigate an issue in which the plugin could not be loaded due to an error like: `Unexpected end of JSON input`

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-40095
https://issues.redhat.com/browse/CNV-40164
```

**Release note**:

```release-note
Disable caching for kubevirt-console-plugin entry assets
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

Just idea: if the nginx config file is starting to be larger and more complex, we can embed it as a regular config file (go embed)

**Review by tiraboschi — APPROVED** [review]

**Comment by tiraboschi** [comment]
OKD CI is still out of order, let's ignore it
/override ci/prow/okd-hco-e2e-operator-sdk-aws
/override ci/prow/okd-hco-e2e-operator-sdk-gcp
/override ci/prow/okd-hco-e2e-upgrade-operator-sdk-aws
/override ci/prow/okd-hco-e2e-upgrade-operator-sdk-gcp

**Pull request merged**
