### PR TITLE
Fix error while checking if running in openshift

### LINKED ISSUE #806: CheckRunningInOpenshift fails on OCP/OKD 4.6
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
CheckRunningInOpenshift detects OCP 4.6 as plain Kubernetes:

```
[stirabos@t470s hyperconverged-cluster-operator]$ oc logs -n openshift-cnv hco-operator-7ddbff9d56-cprpm | grep "Cluster type ="
{"level":"info","ts":1600268141.242415,"logger":"cmd","msg":"Cluster type = kubernetes"}
```

**What you expected to happen**:
OCP/OKD 4.6 is detected as Openshift

**How to reproduce it (as minimally and precisely as possible)**:
Grep HCO logs for `Cluster type = `

**Anything else we need to know?**:
We copyed it from kubevirt/kubevirt maybe it's also affected 

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`): 2.5.0
- Kubernetes version (use `kubectl version`): OCP 4.6
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by nunnatsa**
Fix #806 - Use KV implementation directly instead of copying it.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Review by tiraboschi — APPROVED** [review]

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-prev-aws passed
/override ci/prow/hco-e2e-upgrade-prev-azure
hco-e2e-aws and hco-e2e-azure passed, hco-e2e-image-index-gcp fails only due to infra issues.
/override hco-e2e-image-index-gcp

**Pull request merged**
