### PR TITLE
Expose an enviromental value to virtio win image (#1222)

### PR DESCRIPTION
**Pull request by tiraboschi**
Expose an environmental value to consume at runtime
a virtio win image that should be propagated to
a config map consumed by the UI component
when the user tries to boot/import a Windows VM.

In the past the UI was using an hardcoded value
but due to that it wasn't properly working on
disconnected environments.

Fixes: https://bugzilla.redhat.com/1969756

This is just a manual cherry-pick of #1222

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Expose an environmental value for virtio win image
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by tiraboschi** [comment]
we don't care about readability related code smells that we already fixed on main and release-1.4 stabilization branches.
Ignoring sonar cloud warning.

**Pull request merged**
