### PR TITLE
Update kubevirt to v0.17.4

### PR DESCRIPTION
**Pull request by tiraboschi**
Fixes https://github.com/kubevirt/hyperconverged-cluster-operator/issues/143

### CODE REVIEW

**Comment by rthallisey** [comment]
@tiraboschi need to run `./hack/build-manifests.sh` in case there are any csv changes we need to pickup

**Comment by rthallisey** [comment]
ci test please

**Comment by tiraboschi** [comment]
> @tiraboschi need to run `./hack/build-manifests.sh` in case there are any csv changes we need to pickup

done

**Comment by tiraboschi** [comment]
ci test please

**Pull request merged**
