### PR TITLE
Expose DisableMDEVConfiguration feature gate on HCO API

### PR DESCRIPTION
**Pull request by orenc1**
**What this PR does / why we need it**:
Expose `DisableMDEVConfiguration` kubevirt feature gate through HyperConverged API: 
`.spec.featureGates.disableMDevConfiguration`
Default is `false`. When set to `true`, the `DisableMDEVConfiguration` is added to Kubevirt's CR `.spec.configuration.developerConfiguration.featureGates` list.

https://github.com/kubevirt/kubevirt/blob/e732c5c99ded56b08ccdcbd8a85301882561325a/pkg/virt-config/feature-gates.go#L63

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-27645
```

**Release note**:

```release-note
expose DisableMDEVConfiguration feature gate in HCO CR.
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by dharmit** [comment]
Failures are related to [timeout](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/2320/pull-hyperconverged-cluster-operator-e2e-k8s-1.24/1649106348136206336)

/test pull-hyperconverged-cluster-operator-e2e-k8s-1.24

**Comment by dharmit** [comment]
@orenc1 I noticed that you've added below YAML block in multiple files:
```yaml
disableMDevConfiguration:
    default: false
    description: Disable mediated devices handling on KubeVirt
    type: boolean
```
Did you do this manually everywhere, or is there a command in operator-sdk that helps one automatically add it to all relevant/required YAML files?

**Comment by orenc1** [comment]
> @orenc1 I noticed that you've added below YAML block in multiple files:
> 
> ```yaml
> disableMDevConfiguration:
>     default: false
>     description: Disable mediated devices handling on KubeVirt
>     type: boolean
> ```
> 
> Did you do this manually everywhere, or is there a command in operator-sdk that helps one automatically add it to all relevant/required YAML files?

It is auto-generated by operator-sdk / kubebuilder, from the types definition

**Pull request merged**
