### PR TITLE
Undo workaround to reduce bundle size

### PR DESCRIPTION
**Pull request by zcahana**
Following OLM support for bundle compression (operator-framework/operator-registry#685, operator-framework/operator-lifecycle-manager#2240), this PR removes the workaround introduced in #1396 to reduce the size of the HCO bundle so that it does not exceed 1MiB.

With the workaround removed, the 1.5.0 bundle size is 1.1M:
```sh
$ du -d0 -h deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/
1.1M    deploy/olm-catalog/community-kubevirt-hyperconverged/1.5.0/
```

Marking this as WIP for now, we should first see if this PR passes openshift-ci (which should be running with a compression-enabled OLM), and later on we can determine if this should be merged now or at some later point.

**Reviewer Checklist**

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by zcahana** [comment]
CI failures (e.g. [this](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/1445/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-image-index-aws/1417069149544255488/artifacts/hco-e2e-image-index-aws/gather-extra/artifacts/pods/kubevirt-hyperconverged_8ec6cc0db3b461211db69e07e387804fd32f6dc32e98501f1eace9b865244k2_extract.log)) indicate that OLM version on openshift-ci doesn't yet support compression:
```
time="2021-07-19T11:27:38Z" level=info msg="Using in-cluster kube client config"
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/cluster-network-addons00.crd.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/containerized-data-importer00.crd.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/hco00.crd.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/hco01.crd.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/hco02.crd.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/hostpath-provisioner00.crd.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/kubevirt-hyperconverged-operator.v1.5.0.clusterserviceversion.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/kubevirt00.crd.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/node-maintenance00.crd.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/scheduling-scale-performance00.crd.yaml
time="2021-07-19T11:27:38Z" level=info msg="Reading file" file=/bundle/manifests/vm-import-operator00.crd.yaml
time="2021-07-19T11:27:38Z" level=error msg="Bundle files exceeded 1048576 bytes limit" file=/bundle/manifests/vm-import-operator00.crd.yaml
```

However, the remainder of the error message indicates that the `opm` version used in the openshift-ci *does* support compression (see the new `--gzip` flag):
```
Error: error loading manifests from directory: bundle files exceeded 1048576 bytes limit
Usage:
  opm alpha bundle extract [flags]

Flags:
  -c, --configmapname string   name of configmap to write bundle data
  -l, --datalimit uint         maximum limit in bytes for total bundle data (default 1048576)
      --debug                  enable debug logging
  -z, --gzip                   enable gzip compression of configmap data
  -h, --help                   help for extract
  -k, --kubeconfig string      absolute path to kubeconfig file
  -m, --manifestsdir string    path to directory containing manifests (default "/")
  -n, --namespace string       namespace to write configmap data (default "openshift-operator-lifecycle-manager")

Global Flags:
      --skip-tls   skip TLS certificate verification for container image registries while pulling bundles or index
```

I assume this happens since operator-framework/operator-registry#685 has already been promoted to openshift-ci, whereas the recently merged  operator-framework/operator-lifecycle-manager#2240 hasn't yet.

**Comment by zcahana** [comment]
Tracking openshift/operator-framework-olm#122 which will downstream the gzip compression support into openshift.

**Comment by zcahana** [comment]
> Tracking openshift/operator-framework-olm#122 which will downstream the gzip compression support into openshift.

The referenced PR was replaced/superseded by openshift/operator-framework-olm#129, which is now merged.

/retest

**Comment by zcahana** [comment]
This now fail only on the OKD lanes (with the same errors about the 1MiB limit).

**Comment by tiraboschi** [comment]
I think we need https://github.com/openshift/release/pull/20727 to make this green on the OKD based lanes

**Comment by orenc1** [comment]
🎉

**Pull request merged**
