### PR TITLE
Use the revive linter and fix findings

### PR DESCRIPTION
**Pull request by nunnatsa**
**What this PR does / why we need it**:
This PR adds the [revive](https://revive.run/) linter and fix its findings. 

Also, it moves the github action step for the golangci-lint to a new job, and add linting the tests directory.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
@tiraboschi. Rebased to solve conflicts.

**Review by tiraboschi — APPROVED** [review]

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
