### PR TITLE
WIP: Remove STDCI

### PR DESCRIPTION
**Pull request by gbenhaim**
Since we add Prow jobs, we don't need STDCI anymore.

Signed-off-by: gbenhaim <galbh2@gmail.com>

### CODE REVIEW

**Comment by gbenhaim** [comment]
It looks like the ocp/okd providers have a bug, the pods in the cluster aren't ready.

```
waiting for pods to come online
+ sleep 10
++ oc get pods --all-namespaces --no-headers
++ grep -v Running
++ grep -v Completed
++ wc -l
+ [[ 8 -le 3 ]]
+ echo 'waiting for pods to come online'
waiting for pods to come online
+ sleep 10
```

@tiraboschi did you see this error on STDCI as well? just want to make sure it isn't caused by Prow

**Comment by tiraboschi** [comment]
> STDCI

It usually correctly works

**Comment by gbenhaim** [comment]
I'm going to send a new PR

**Pull request closed without merging**
