### PR TITLE
Update SSP operator 1.0.12

### PR DESCRIPTION
**Pull request by fromanirh**
we also make easier (or possible at all) to run node-labeller without access to `/dev/kvm` on CI

### CODE REVIEW

**Comment by fromanirh** [comment]
prow logs are too terse, I can't tell why it is still failing to deploy the node-labeller
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/276/pull-ci-kubevirt-hyperconverged-cluster-operator-master-hco-e2e-aws/269

**Comment by djzager** [comment]
@fromanirh does this need backport?

**Comment by fromanirh** [comment]
> @fromanirh does this need backport?

Let's see, to which branch?

**Comment by djzager** [comment]
`release-2.1`

**Comment by fromanirh** [comment]
> `release-2.1`

uhm, probably yes. But let me sort out this patch first.

**Comment by fromanirh** [comment]
Uhm, I don't understand why https://storage.googleapis.com/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/276/pull-ci-kubevirt-hyperconverged-cluster-operator-master-hco-e2e-aws/362/build-log.txt still fails. It should have been fixed by https://github.com/kubevirt/hyperconverged-cluster-operator/pull/276/commits/149a16142a4e8c774390fcdc78938c74e0653241

**Comment by fromanirh** [comment]
| /test hco-e2e-aw
-- | --

**Comment by fromanirh** [comment]
The issue here is on AWS there is no KVM device available (AFAICT). This patch adds code to deal with this fact, but we need a way to tell the HCO that we are running on CI. Just setting the `CI=1` env var on the HCO pod is sufficient. Otherwise, we need to improve the autodetection of CI envs: suggestions welcome :)

**Comment by rthallisey** [comment]
This is going to fail on any AWS deployment, even outside of CI, right?

**Comment by fromanirh** [comment]
> This is going to fail on any AWS deployment, even outside of CI, right?

Yes, if no KVM device is available. It always failed before this patch, we just reported incorrectly so it _seemed_ ok on CI, where noone really cares about labels (at least noone that I know about).

On node-labeller CI we have a workaround, which we replicated here on https://github.com/kubevirt/hyperconverged-cluster-operator/pull/276/commits/29d999c024e200912104e3e093653d7d536e508a

We just need a way to reliably detect CI-like envs (= no kvm device available). The current checks don't seem to work.

**Comment by rthallisey** [comment]
@fromanirh it might be better to move the auto detection out of the controller to the ci script `hack/deploy.sh`.

**Comment by fromanirh** [comment]
> @fromanirh it might be better to move the auto detection out of the controller to the ci script `hack/deploy.sh`.

ack, remixed the code

**Comment by fromanirh** [comment]
Ok, eventually I figured out. For some reasons, the CR is created *without* the `use_kvm` flag:
```yaml
apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: KubevirtNodeLabellerBundle
  metadata:
    creationTimestamp: "2019-10-14T08:36:15Z"
    generation: 1
    labels:
      app: hyperconverged-cluster
    name: node-labeller-hyperconverged-cluster
    namespace: kubevirt-hyperconverged
    ownerReferences:
    - apiVersion: hco.kubevirt.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: HyperConverged
      name: hyperconverged-cluster
      uid: 07496f92-f3b9-42f0-b034-4d194a736316
    resourceVersion: "19886"
    selfLink: /apis/kubevirt.io/v1/namespaces/kubevirt-hyperconverged/kubevirtnodelabellerbundles/node-labeller-hyperconverged-cluster
    uid: 48b11517-34c7-42b7-9d47-fba926de27d3
  spec: {}
  status:
    conditions:
    - lastTransitionTime: "2019-10-14T08:36:15Z"
      message: Running reconciliation
      reason: Running
      status: "True"
      type: Running
    - message: Node-labeller is progressing.
      reason: progressing
      status: "True"
      type: Progressing
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
And this explains the failure on AWS

Problem is: the hco tries to add and set the use_kvm flag:
```
{"level":"info","ts":1571042175.5686512,"logger":"controller_hyperconverged","msg":"Running with KVM emulation"}
{"level":"info","ts":1571042175.5686736,"logger":"controller_hyperconverged","msg":"Creating KubeVirt Node Labeller Bundle","Request.Namespace":"kubevirt-hyperconverged","Request.Name":"hyperconverged-cluster"}
```

**Comment by fromanirh** [comment]
OK, we had a quick chat to the HCO folks and it seems we don't really need the backward compat for the time being. We will re-add later if needed.

**Comment by fromanirh** [comment]
replaced by https://github.com/kubevirt/hyperconverged-cluster-operator/pull/321

**Pull request closed without merging**
