### PR TITLE
Manually Bump CDI to v1.60.1

### PR DESCRIPTION
**Pull request by nunnatsa**
Needed some code changes as result of CDI API changes (https://github.com/kubevirt/containerized-data-importer/pull/3172)

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
Bump CDI to v1.60.1
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
@tiraboschi it looks like there is a regretion in cdi v1.60.1. Smoke test is failing in test_id:7679

**Comment by nunnatsa** [comment]
Rebased because of git conflict

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
