### PR TITLE
Move the check_update_priority_class bash test to golang

### PR DESCRIPTION
**Pull request by nunnatsa**
Implement the hack/check_update_priority_class.sh script in golang.

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-26499
```

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-prev-operator-sdk-aws lane passed
/override ci/prow/hco-e2e-upgrade-prev-operator-sdk-azure

**Comment by avlitman** [comment]
@nunnatsa Is this file should be updated https://github.com/kubevirt/hyperconverged-cluster-operator/blob/4938da44791ed201115fa0fd7d99f6dd2303efdc/docs/tests.md?plain=1#L74?

**Comment by nunnatsa** [comment]
> Is this file should be updated?
> 
> https://github.com/kubevirt/hyperconverged-cluster-operator/blob/4938da44791ed201115fa0fd7d99f6dd2303efdc/docs/tests.md?plain=1#L77

@avlitman - good point. This file is way out of date. Let's update it in a separate PR.

**Comment by avlitman** [comment]
> > Is this file should be updated?
> > https://github.com/kubevirt/hyperconverged-cluster-operator/blob/4938da44791ed201115fa0fd7d99f6dd2303efdc/docs/tests.md?plain=1#L77
> 
> @avlitman - good point. This file is way out of date. Let's update it in a separate PR.

Should we open an issue?

**Comment by nunnatsa** [comment]
> Should we open an issue?

Please do. I'm not sure we need this list.

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
