### PR TITLE
Bump vm-import-operator to v0.2.0 and consume CRD v1beta1

### PR DESCRIPTION
**Pull request by tiraboschi**
Bump vm-import-operator to v0.2.0 and consume CRD v1beta1

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Bump vm-import-operator to v0.2.0 and consume CRD v1beta1
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by pkliczewski** [comment]
@tiraboschi Please rebase and run `make build-manifests`. I tried to refresh you branch but got: 

> ERROR: Permission to tiraboschi/hyperconverged-cluster-operator.git denied to pkliczewski.

The issue was fixed.

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
See:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/751/pull-ci-kubevirt-hyperconverged-cluster-operator-master-hco-e2e-aws/1297864716340695040/artifacts/hco-e2e-aws/pods/kubevirt-hyperconverged_vm-import-operator-574749d8bf-v6rfx_vm-import-operator.log

vm-import-operator got stuck in a loop on `E0824 12:50:25.142647       1 reflector.go:123] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kubevirt-hyperconverged:vm-import-operator" cannot list resource "services" in API group "" at the cluster scope` without never progressing

**Comment by pkliczewski** [comment]
> vm-import-operator got stuck in a loop on `E0824 12:50:25.142647 1 reflector.go:123] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kubevirt-hyperconverged:vm-import-operator" cannot list resource "services" in API group "" at the cluster scope` without never progressing

The issue should be fixed by https://github.com/kubevirt/vm-import-operator/pull/383

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by pkliczewski** [comment]
There is one more issue fixed by https://github.com/kubevirt/vm-import-operator/pull/384

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
Done in https://github.com/kubevirt/hyperconverged-cluster-operator/pull/765

**Pull request closed without merging**
