### PR TITLE
Add back v2v support on release-2.1 (reverts #306 and #310)

### PR DESCRIPTION
**Pull request by tiraboschi**
Reverts kubevirt/hyperconverged-cluster-operator#310

### CODE REVIEW

**Comment by tiraboschi** [comment]
Reverts #306

**Comment by rthallisey** [comment]
Does https://github.com/kubevirt/hyperconverged-cluster-operator/pull/322 already cover this?

**Comment by tiraboschi** [comment]
> Does #322 already cover this?

I'm going to deeply compare them but yes, it should be the same

**Comment by rthallisey** [comment]
I'm ok with either.  Let's see what passes ci first :)

**Comment by rthallisey** [comment]
ci test please

**Comment by rwsu** [comment]
ci test please

**Comment by rwsu** [comment]
ci test please

Upgrade test failed because it is missing an update that excludes terminating pods.

**Pull request merged**
