### PR TITLE
Fix wrong kubectl call

### PR DESCRIPTION
**Pull request by rmohr**
Calling kubectl.sh worked by accident in the testenvironment.
Replacing that call with ${_kubectl}.

### CODE REVIEW

**Comment by rmohr** [comment]
@tiraboschi looks like deploying HCO is broken on openshift CI.

**Comment by tiraboschi** [comment]
> @tiraboschi looks like deploying HCO is broken on openshift CI.

Plain deployment on `ci/prow/hco-e2e-aws` is green, it's something specific to `ci/prow/hco-e2e-upgrade-aws` which is the upgrade test job.

**Comment by rmohr** [comment]
@tiraboschi the CI issue is unrelated. Is someone working on fixing it? If not, is there a way forward to merge this? We still have coverage which guarantees that my changes don't add any regressions.

**Comment by tiraboschi** [comment]
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/375 should be enough to fix it.
Can you please rebase this one?

**Pull request merged**
