### PR TITLE
Fix Dependabot Alert - runc

### PR DESCRIPTION
**Pull request by orenc1**
https://github.com/advisories/GHSA-f3fp-gc8g-vw66
https://github.com/kubevirt/hyperconverged-cluster-operator/security/dependabot/7
Upgrade github.com/opencontainers/runc to v1.1.2

Signed-off-by: orenc1 <ocohen@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by orenc1** [comment]
handling in https://github.com/kubevirt/kubevirt/pull/8073 since it's a vendored code from kubevirt/kubevirt

**Comment by orenc1** [comment]
https://github.com/kubevirt/kubevirt/pull/8073 was merged.
waiting for a new kubevirt release that contains the runc bump.

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
