### PR TITLE
Call the sub-component webhooks in parallel

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
/hold

wip

**Comment by nunnatsa** [comment]
new tests are working

/unhold

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
ci/prow/hco-e2e-image-index-aws is stuck for 2:45 hours. ci/prow/hco-e2e-image-index-azure and ci/prow/hco-e2e-image-index-gcp passed.
/override ci/prow/hco-e2e-image-index-aws

**Pull request merged**
