### PR TITLE
Fix typo: oject -> Object

### PR DESCRIPTION
**Pull request by AaronDewes**
**What this PR does / why we need it**:

This fixes what I assume to be a typo?

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
NONE
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
> This fixes what I assume to be a typo?

Thanks, nice catch.

Can you please sign-off your commit?

**Comment by nunnatsa** [comment]
@AaronDewes - thanks for this PR! Please sign your commit and push it again; e.g.

```shell
$ git commit -s --amend
$ git push -f
```

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
