### PR TITLE
Bump components to get ready for 1.5.0

### PR DESCRIPTION
**Pull request by tiraboschi**
- NETWORK_ADDONS v0.58.0 -> v0.58.2
- SSP v0.11.2 -> v0.12.0
- NMO v0.9.0 -> v0.10.0
- VM_IMPORT v0.3.7 -> v0.4.0

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**
- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:
```release-note
Bump components to get ready for 1.5.0
```

### CODE REVIEW

**Comment by orenc1** [comment]
looks like `cdi-deployment` pods crashlooped both in aws and azure:
[aws](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/1549/pull-ci-kubevirt-hyperconverged-cluster-operator-release-1.5-hco-e2e-upgrade-prev-index-aws/1443959773157396480/artifacts/hco-e2e-upgrade-prev-index-aws/gather-extra/artifacts/pods/kubevirt-hyperconverged_cdi-deployment-7cdb7fd7b6-2lnf4_cdi-controller.log)
[azure](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/1549/pull-ci-kubevirt-hyperconverged-cluster-operator-release-1.5-hco-e2e-upgrade-prev-index-azure/1443959773916565504/artifacts/hco-e2e-upgrade-prev-index-azure/gather-extra/artifacts/pods/kubevirt-hyperconverged_cdi-deployment-7cdb7fd7b6-cgmzx_cdi-controller.log) 

due to:
```
E1001 16:27:52.617627       1 controller.go:185] Error running manager: [no matches for kind "Ingress" in version "extensions/v1beta1", failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]
```
But starting from kubernetes v1.22 `Ingress` resource is served at the apiversion of `networking.k8s.io/v1beta1`, not `extensions/v1beta1`

**Comment by tiraboschi** [comment]
> But starting from kubernetes v1.22 `Ingress` resource is served at the apiversion of `networking.k8s.io/v1beta1`, not `extensions/v1beta1`

I'm a bit confused: #1548 should address this on the release-1.4 branch letting us build 1.4.2 that is supposed to work also on OCP 4.9.
But if the issue is just there, it should fail before the upgrade, not on the upgrade to the current version.

**Comment by orenc1** [comment]
agree.
let's have one more retry to ensure it is not some kind of flakiness
/retry

**Comment by orenc1** [comment]
let's have one more retry to ensure it is not some kind of flakiness
/retest

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
