### PR TITLE
Bump CDI to v1.23.3

### PR DESCRIPTION
**Pull request by tiraboschi**
Bump CDI to v1.23.3

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Bump CDI to v1.23.3
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-prev-aws lane succeeded.
/override ci/prow/hco-e2e-upgrade-prev-azure

**Comment by ovirt-infra** [comment]
All tests passed

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
