### PR TITLE
Move to CRDv1 and generate it automatically from sources

### PR DESCRIPTION
**Pull request by tiraboschi**
Move to CRDv1 and generate it automatically from sources

Directly use sigs.k8s.io/controller-tools (as a library)
to generate HCO CRD directly from API code.

This let us easily migrate from
apiextensions.k8s.io/v1beta1 -> apiextensions.k8s.io/v1,
get full openAPIV3 validation and get a CRD which
is oc explain-able.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Move to CRDv1 and generate it automatically from sources
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
hco-e2e-upgrade passed on AWS, ignoring temporary failures on azure
/override hco-e2e-upgrade-azure

**Comment by tiraboschi** [comment]
hco-e2e-upgrade passed on AWS, ignoring temporary failures on azure
/override ci/prow/hco-e2e-upgrade-azure

**Pull request merged**
