### PR TITLE
[release-1.3] Update Images Digests

### PR DESCRIPTION
**Pull request by orenc1**
Signed-off-by: orenc1 <ocohen@redhat.com>

**Release note**:

```release-note
update image digests before release
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
@tiraboschi - this should be copied to `master` 1.3 directory, because it will break the upgrade-prev lanes.

**Comment by tiraboschi** [comment]
> @tiraboschi - this should be copied to `master` 1.3 directory, because it will break the upgrade-prev lanes.

Yes, I'll manually do it.
Then we should find a mechanism to automate this.

**Comment by orenc1** [comment]
> > @tiraboschi - this should be copied to `master` 1.3 directory, because it will break the upgrade-prev lanes.
> 
> Yes, I'll manually do it.
> Then we should find a mechanism to automate this.

We can have a workflow that mirrors the contents of the manifests version folder of a release branch, to it's respective version folder in master, which can be triggered by a special keyword we define in the PR (for example).
Anyway it must go through a PR to master...

**Pull request merged**
