### PR TITLE
[release-1.3] Bump SSP to v0.1.3

### PR DESCRIPTION
**Pull request by orenc1**
**Release note**:

```release-note
Bump SSP to v0.1.3 for release-1.3
```

### CODE REVIEW

**Review by nunnatsa — COMMENTED** [review]
We're usually starts from master and cherry picking. Why change directlly in release-1.3? We need this change in master anyway.

**Comment by orenc1** [comment]
> We're usually start from master and cherry picking. Why change directlly in release-1.3? We need this change in master anyway.

Right. The change for master is in #1090

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
