### PR TITLE
Build also functest image for kubevirtci

### PR DESCRIPTION
**Pull request by tiraboschi**
Build also the functest image and push
it to the local registry on kubevirtci
as part of `make cluster-sync`
so then later on it can be directly consumed
with:
`JOB_TYPE=stdci make functest`

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
ignoring false positive on coverage
/override coverage/coveralls

**Review by nunnatsa — APPROVED** [review]

**Pull request merged**
