### PR TITLE
disable by default SerialConsoleLog

### PR DESCRIPTION
**Pull request by tiraboschi**
**What this PR does / why we need it**:
Disable, by default, the serialConsoleLog
feature since we got report about the
sidecar container used to stream out guest
console logs to potentially cause
some race conditions in recent CRI-O.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [X] PR Message
- [X] Commit Messages
- [X] How to test
- [X] Unit Tests
- [X] Functional Tests
- [X] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-37610
```

**Release note**:

```release-note
Disable by default the serialConsoleLog feature
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
hco-e2e-kv-smoke-gcp lane succeeded.
/override ci/prow/hco-e2e-kv-smoke-azure

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by akalenyu** [comment]
@tiraboschi Think we can reconsider this for main?

**Pull request merged**
