### PR TITLE
bump CNAO to 0.39.3

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horacek <phoracek@redhat.com>

**Release note**:

This release brings a fix for version labeling bug:

https://bugzilla.redhat.com/1856438

```release-note
Use CNAO 0.39.3
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by nunnatsa** [comment]
> /cherry-pick release-2.4

Need to be done manually.

**Pull request merged**
