### PR TITLE
Partially reconcile IMS ConfigMap

### PR DESCRIPTION
**Pull request by tiraboschi**
v2v-vmware is created and managed by HCO operator;
with #832 we started properly reconciling it.
Unfortunately, due to a bad design, v2v-vmware is
also abused by other components that injects other
values there.
A proper design consist in splitting it into two distinct
config-maps. As a quick but dirty fix let's start
reconciling only a few values from HCO.

Fixes: https://bugzilla.redhat.com/1884538

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Partially reconcile IMS ConfigMap
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Review by fdupont-redhat — APPROVED** [review]
LGTM

**Pull request merged**
