### PR TITLE
Bump golang and its dependencies

### PR DESCRIPTION
**Pull request by tiraboschi**
**What this PR does / why we need it**:
Bump golang dependencies

- golang 1.21 => 1.22
- github.com/kubevirt/monitoring/pkg/metrics/parser v0.0.0-20240408121652-bb3835ce94d8 => v0.0.0-20240505100225-e29dee0bb12b
- github.com/machadovilaca/operator-observability v0.0.19 => v0.0.20
- github.com/onsi/ginkgo/v2 v2.17.1 => v2.17.2
- github.com/onsi/gomega v1.32.0 => v1.33.1
- github.com/openshift/library-go v0.0.0-20240410140155-0045765c004e => v0.0.0-20240506162756-6301addeda88
- github.com/operator-framework/api v0.23.0 => v0.24.0
- github.com/operator-framework/operator-lib v0.12.0 => v0.13.0
- github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring v0.73.0 => v0.73.2
- golang.org/x/tools v0.20.0 => v0.21.0
- k8s.io/* v0.29.3 => v0.30.0
- k8s.io/kube-openapi v0.0.0-20240403164606-bc84c2ddaf99 => v0.0.0-20240430033511-f0e62f92d13f
- k8s.io/utils v0.0.0-20240310230437-4693a0247e57 => v0.0.0-20240502163921-fe8a2dddb1d0
- sigs.k8s.io/controller-runtime v0.17.3 => v0.18.2
- sigs.k8s.io/controller-tools v0.14.0 => v0.15.0

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
NONE
```

**Release note**:

```release-note
Bump to controller-runtime v0.18.2 and k8s.io/* v0.30.0
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
nit: [1.22.3 released](https://go.dev/doc/devel/release#go1.22.3) with some security fixes to the go command and the net package.

Other than that
/lgtm

**Comment by tiraboschi** [comment]
> nit: [1.22.3 released](https://go.dev/doc/devel/release#go1.22.3) with some security fixes to the go command and the net package.

let's keep this for a separate PR

**Pull request merged**
