### PR TITLE
Bump components to get ready for 1.4.2

### PR DESCRIPTION
**Pull request by tiraboschi**
Bump components to get ready for 1.4.2

- CDI v1.34.1 -> v1.34.2
- NETWORK_ADDONS v0.53.6 -> v0.53.7
- SSP v0.11.2 -> v0.11.4
- HPP v0.8.0 -> v0.9.0
- VM_IMPORT v0.3.6 -> v0.4.0

Fixes: #1545 

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**
- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:
```release-note
Bump components to get ready for 1.4.2
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-aws  got dropped with https://github.com/openshift/release/pull/22464
/override ci/prow/hco-e2e-upgrade-aws

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by tiraboschi** [comment]
Manually merging to bypass sonarcloud false positive.

**Pull request merged**
