### PR TITLE
Adding SuggestedNamespace annotation in HCO CSV for OLM

### PR DESCRIPTION
**Pull request by orenc1**
By this annotation, UI would suggest the relevant namespace for kubevirt/CNV deployment, i.e. `kubevirt-hyperconverged` or `openshfit-cnv`

https://bugzilla.redhat.com/show_bug.cgi?id=1799055

### CODE REVIEW

**Comment by djzager** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci test please

**Comment by orenc1** [comment]
ci test please

**Comment by orenc1** [comment]
ci test please

**Comment by orenc1** [comment]
now that the STDCI has gone:
/retest

**Comment by tiraboschi** [comment]
@orenc1 I think you have to rebase it in order to consume the new CI configuration

**Comment by orenc1** [comment]
test failed due to aws bootstrapping error.
/retest

**Comment by tiraboschi** [comment]
Closing because we already merged https://github.com/kubevirt/hyperconverged-cluster-operator/pull/461

**Pull request closed without merging**
