### PR TITLE
Revert "[release-1.8] Enable PSA FG on Kubevirt (#2093)"

### PR DESCRIPTION
**Pull request by tiraboschi**
This reverts commit 4731026dec411bb0a0f5ce3153f41ff948390a34.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Revert PSA FG on Kubevirt
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
hco-e2e-image-index-aws succeeded
/override ci/prow/hco-e2e-image-index-azure

hco-e2e-image-index-sno-aws succeeded
ci/prow/hco-e2e-image-index-sno-azure

hco-e2e-upgrade-index-aws succeeded
ci/prow/hco-e2e-upgrade-index-azure

hco-e2e-upgrade-index-sno-aws
ci/prow/hco-e2e-upgrade-index-sno-azure

**Comment by tiraboschi** [comment]
hco-e2e-image-index-sno-aws succeeded
/override ci/prow/hco-e2e-image-index-sno-azure

hco-e2e-upgrade-index-aws succeeded
/override ci/prow/hco-e2e-upgrade-index-azure

hco-e2e-upgrade-index-sno-aws
/override ci/prow/hco-e2e-upgrade-index-sno-azure

**Comment by tiraboschi** [comment]
hco-e2e-image-index-aws succeeded:
/override ci/prow/hco-e2e-image-index-azure
/override ci/prow/hco-e2e-image-index-gcp

hco-e2e-image-index-sno-aws succeeded:
/override ci/prow/hco-e2e-image-index-sno-azure

hco-e2e-kv-smoke-gcp succeeded:
/override ci/prow/hco-e2e-kv-smoke-azure

hco-e2e-upgrade-index-aws succeeded:
/override ci/prow/hco-e2e-upgrade-index-azure

hco-e2e-upgrade-index-sno-aws succeeded:
/override ci/prow/hco-e2e-upgrade-index-sno-azure

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
