### PR TITLE
Bump vmimport v0.2.0

### PR DESCRIPTION
**Pull request by pkliczewski**
Bump vm-import-operator to v0.2.0 and consume CRD v1beta1

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

**Release note:**
```release-note
Bump vm-import-operator to v0.2.0 and consume CRD v1beta1
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
Azure cluster is not working due to a quota issue but the same tests got successfully executed on AWS and it's enough
/override ci/prow/hco-e2e-upgrade-azure
/override ci/prow/hco-e2e-upgrade-prev-azure

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
