### PR TITLE
[release-1.11] Avoid removing user labels (#2743)

### PR DESCRIPTION
**Pull request by tiraboschi**
**What this PR does / why we need it**:
Reconcile managed labels on operands without
removing user added ones.
Add unit and func tests.

This is a manual cherry-pick of #2743 and #2820

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-36231
```

**Release note**:

```release-note
Avoid removing user labels
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by nunnatsa** [comment]
hco-e2e-operator-sdk-aws and hco-e2e-operator-sdk-gcp lanes suceeded
/override ci/prow/hco-e2e-operator-sdk-azure

hco-e2e-upgrade-prev-operator-sdk-sno-aws lane succeeded 
/override ci/prow/hco-e2e-upgrade-prev-operator-sdk-sno-azure

**Comment by tiraboschi** [comment]
hco-e2e-operator-sdk-aws lane succeeded
/override ci/prow/hco-e2e-operator-sdk-azure

**Comment by tiraboschi** [comment]
it looks ready
/unhold

**Pull request merged**
