### PR TITLE
Avoid directly using client-go kubevirt.io to bump k8s deps.

### PR DESCRIPTION
**Pull request by tiraboschi**
Directly using kubevirt.io/client-io was forcing us to stay on
k8s v0.16.4.
With this PR we are limiting us to consume only the API definition
from kubevirt.io/client-io with the dynamic client from
sigs.k8s.io/controller-runtime.

This let's us finally move to sigs.k8s.io/controller-runtime v0.6.z
and sigs.k8s.io/controller-tools v0.4.0.

This PR rewrites CheckRunningInOpenshift reading
the OpenShift ClusterVersion object if available,
plain k8s otherwise.

tests/func-tests is isntead built as a separate package
because it still requires kubevirt.io/client-io to
create a test VM.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Avoid directly using client-go kubevirt.io to bump k8s deps.
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by nunnatsa** [comment]
The new test is not stable yet

/override pull-hco-node-placement-k8s-1.17

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by nunnatsa** [comment]
The new test is not stable yet

/override pull-hco-node-placement-k8s-1.17

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
The new test is not stable yet

/override pull-hco-node-placement-k8s-1.17

**Pull request merged**
