### PR TITLE
Bump Go Dependencies to 1.18.1

### PR DESCRIPTION
**Pull request by orenc1**
Signed-off-by: orenc1 <ocohen@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
bump golang version in HCO to 1.18.1
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by orenc1** [comment]
`error: No package matches 'graphviz'` on almost all lanes.
however, this worked locally with `registry.access.redhat.com/ubi8/ubi-minimal:latest` image.

/retest

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
