### PR TITLE
storage class as parameter

### PR DESCRIPTION
**Pull request by ILpinto**
For certificate test, set storage class as parameter

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

I don't think that this is needed. Check the `storage-class-local` flag which I added in https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/tests/func-tests/utils.go#L27

**Comment by rmohr** [comment]
you should also see it when you run `--help` on the binary.

**Comment by rmohr** [comment]
can this be closed?

**Comment by ILpinto** [comment]
closing parameter exists

**Comment by ILpinto** [comment]
closing parameter exists

**Pull request closed without merging**
