### PR TITLE
Bump golang dependencies

### PR DESCRIPTION
**Pull request by tiraboschi**
**What this PR does / why we need it**:
Bump golang dependencies:
- github.com/kubevirt/monitoring/pkg/metrics/parser v0.0.0-20240125201600-b689e9c89409 => v0.0.0-20240408121652-bb3835ce94d8
- github.com/machadovilaca/operator-observability v0.0.16 => v0.0.19
- github.com/onsi/ginkgo/v2 v2.15.0 => v2.17.1
- github.com/onsi/gomega v1.31.1 => v1.32.0
- github.com/openshift/library-go v0.0.0-20240207105404-126b47137408 => v0.0.0-20240410140155-0045765c004e
- github.com/operator-framework/api v0.22.0 => v0.23.0
- github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring v0.71.2 => v0.73.0
- github.com/prometheus/client_golang v1.18.0 => v1.19.0
- github.com/prometheus/client_model v0.5.0 => v0.6.1
- github.com/prometheus/common v0.47.0 => v0.52.2
- golang.org/x/sync v0.6.0 => v0.7.0
- golang.org/x/tools v0.18.0 => v0.20.0
- k8s.io/* v0.29.2 => v0.29.3
- k8s.io/kube-openapi v0.0.0-20240209001042-7a0d5b415232 => v0.0.0-20240403164606-bc84c2ddaf99
- k8s.io/utils v0.0.0-20240102154912-e7106e64919e => v0.0.0-20240310230437-4693a0247e57
- sigs.k8s.io/controller-runtime v0.17.1 => v0.17.3
- github.com/onsi/ginkgo/v2 v2.15.0 => v2.17.1
- github.com/onsi/gomega v1.31.1 => v1.32.0

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
NONE
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
okd-hco-e2e-upgrade-operator-sdk-aws lane succeeded.
/override ci/prow/okd-hco-e2e-upgrade-operator-sdk-gcp

**Review by nunnatsa — APPROVED** [review]
/approve 
/lgtm

**Pull request merged**
