### PR TITLE
Support ApplyOptions on upgradePatches

### PR DESCRIPTION
**Pull request by tiraboschi**
**What this PR does / why we need it**:
Add support for optional ApplyOptions
(AllowMissingPathOnRemove/EnsurePathExistsOnAdd/...) on upgradePatches from github.com/evanphx/json-patch/v5. Bump it to v5 everywhere.

Add unit tests for allowMissingPathOnRemove and ensurePathExistsOnAdd.

Avoid trying to update featureGates/sriovLiveMigration since it got removed with #2067.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
NONE
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by enp0s3 — CHANGES_REQUESTED** [review]
@tiraboschi Hi! thanks for adding this option! 
Can you please checkout the project root `go.sum` file? it looks like `make sanity` reverts it and then the sanity lane failed

**Comment by tiraboschi** [comment]
> @tiraboschi Hi! thanks for adding this option! Can you please checkout the project root `go.sum` file? it looks like `make sanity` reverts it and then the sanity lane failed

done

**Review by enp0s3 — APPROVED** [review]

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-operator-sdk-aws lane passed
/override ci/prow/hco-e2e-upgrade-operator-sdk-azure

**Pull request merged**
