### PR TITLE
Regenerate the manifests to point to HCO 1.2.0 with a new hash

### PR DESCRIPTION
**Pull request by tiraboschi**
Regenerate the manifests to point to HCO 1.2.0 with a new hash

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by tiraboschi** [comment]
hco-e2e-aws sucesfully passed
/override ci/prow/hco-e2e-aws

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-aws and hco-e2e-upgrade-prev-aws successfully passed
/override ci/prow/hco-e2e-upgrade-azure
/override ci/prow/hco-e2e-upgrade-prev-azure

**Pull request merged**
