### PR TITLE
Fix multiple issues when building the CSV

### PR DESCRIPTION
**Pull request by nunnatsa**
## What this PR does / why we need it
1. add the virt-artifacts-server and the template validator images to the related images.
2. use digest instead of tags for the virt-artifacts-server and the template validator images
3. fix the community hub deployment test, by allowing HCO to be installed on the "community-kubevirt-hyperconverged" and "community-kubevirt-hyperconverged-target" namespaces.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
None fix multiple issues in the CSV
1. add the virt-artifacts-server and the template validator images to the related images.
2. use digest instead of tags for the virt-artifacts-server and the template validator images
3. fix the community hub deployment test, by allowing HCO to be installed on the "community-kubevirt-hyperconverged" and "community-kubevirt-hyperconverged-target" namespaces.
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-prev-operator-sdk-aws lane passed 
/override ci/prow/hco-e2e-upgrade-prev-operator-sdk-azure

**Pull request merged**
