### PR TITLE
[Release Bump Bot] Exit on Error

### PR DESCRIPTION
**Pull request by nunnatsa**
Fail the bump process if an error occurred; e.g. when an image is missing.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
@orenc1 - this is fixing the bot to fail on error; e.g. in #964 where the new CNAO image does not exist in the repository.

**Comment by orenc1** [comment]
> @orenc1 - this is fixing the bot to fail on error; e.g. in #964 where the new CNAO image does not exist in the repository.

@nunnatsa it won't solve the problem, because `build-manifests.sh` ran without errors. It is now using the cache prepared by the digester and doesn't try to pull the images itself. The digester job failed and didn't update CNAO's digest in images.csv.
A solution might be to run the digester bot before execution of the bump bot, and set a condition to run the bump bot only after a successful execution of the digester bot.

**Comment by nunnatsa** [comment]
> > @orenc1 - this is fixing the bot to fail on error; e.g. in #964 where the new CNAO image does not exist in the repository.
> 
> @nunnatsa it won't solve the problem, because `build-manifests.sh` ran without errors. It is now using the cache prepared by the digester and doesn't try to pull the images itself. The digester job failed and didn't update CNAO's digest in images.csv.
> A solution might be to run the digester bot before execution of the bump bot, and set a condition to run the bump bot only after a successful execution of the digester bot.

But the digester is running before build-manifests, and it will fail and will fail the action. I tested it.

**Comment by orenc1** [comment]
> > > @orenc1 - this is fixing the bot to fail on error; e.g. in #964 where the new CNAO image does not exist in the repository.
> > 
> > 
> > @nunnatsa it won't solve the problem, because `build-manifests.sh` ran without errors. It is now using the cache prepared by the digester and doesn't try to pull the images itself. The digester job failed and didn't update CNAO's digest in images.csv.
> > A solution might be to run the digester bot before execution of the bump bot, and set a condition to run the bump bot only after a successful execution of the digester bot.
> 
> But the digester is running before build-manifests, and it will fail and will fail the action. I tested it.

You right, my local code I looked at was not up to date.. :/
/approve
/lgtm

**Pull request merged**
