### PR TITLE
Consume ConsolePlugin API as v1

### PR DESCRIPTION
**Pull request by tiraboschi**
In OCP/OKD 4.12, the ConsolePlugin API got promoted from v1alpha1 to v1.
See: https://github.com/openshift/api/pull/1186

Consume the new version.

jira-Ticket: CNV-22726

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Consume ConsolePlugin API as v1
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
/hold
this is not going to work for OKD 4.11

**Comment by tiraboschi** [comment]
ignoring slightly decreased coverage
/override coverage/coveralls

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by nunnatsa** [comment]
:rocket: :partying_face:

**Pull request merged**
