### PR TITLE
Use integer values for CPU requests in prom-rules-tests

### PR DESCRIPTION
**Pull request by machadovilaca**
**What this PR does / why we need it**:

Sanity tests are sometimes failing due to floating point round errors in `prom-rules-tests`. This PR replaces floating point values for `kube_pod_container_resource_requests` with integer values.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
NONE
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
/lgtm

Thanks for this PR! It is annoyinh ci bug...

**Review by tiraboschi — APPROVED** [review]

**Comment by tiraboschi** [comment]
hco-e2e-image-index-aws lane succeeded.
/override ci/prow/hco-e2e-image-index-azure
hco-e2e-kv-smoke-gcp lane succeeded.
/override ci/prow/hco-e2e-kv-smoke-azure

**Pull request merged**
