### PR TITLE
Fix runbook_url test

### PR DESCRIPTION
**Pull request by assafad**
**What this PR does / why we need it**:
Fix runbook_url test to not expect the alert name as the URL suffix, as in some installations the alert name is not the URL suffix. 
e.g. in openshift the runbooks are in https://github.com/openshift/runbooks/tree/master/alerts/openshift-virtualization-operator, and the suffix is `<alert-name>.md`.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket

```

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by nunnatsa — COMMENTED** [review]
/lgtm

Please explain in the pr description why this change is needed

**Comment by assafad** [comment]
> /lgtm
> 
> Please explain in the pr description why this change is needed

done

**Review by nunnatsa — APPROVED** [review]
/approve 
/retest

**Pull request merged**
