### PR TITLE
[release-1.4] Bump NETWORK_ADDONS to v0.53.0

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:
```release-note
Bump NETWORK_ADDONS to v0.53.0
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
failing on:
```
INFO[2021-05-01T11:40:14Z] Waiting for namespace kubevirt-test-default1 to be removed, this can take a while ... 
INFO[2021-05-01T11:40:14Z] failed to dump entity named [sriovnetworknodestates]: the server could not find the requested resource 
INFO[2021-05-01T11:40:14Z] failed to dump entity named [sriovnetworknodepolicies]: the server could not find the requested resource 
INFO[2021-05-01T11:40:14Z] failed to dump entity named [sriovnetworks]: the server could not find the requested resource 
INFO[2021-05-01T11:40:14Z] failed to dump entity named [sriovoperatorconfigs]: the server could not find the requested resource 
INFO[2021-05-01T11:40:14Z]                                              
INFO[2021-05-01T11:40:14Z] ------------------------------               
INFO[2021-05-01T11:40:14Z] Failure [0.000 seconds]                      
INFO[2021-05-01T11:40:14Z] [AfterSuite] AfterSuite                      
INFO[2021-05-01T11:40:14Z] tests/tests_suite_test.go:71                 
INFO[2021-05-01T11:40:14Z]                                              
INFO[2021-05-01T11:40:14Z]   Timed out after 240.000s.                  
INFO[2021-05-01T11:40:14Z]   should successfully delete namespace 'kubevirt-test-default1' 
INFO[2021-05-01T11:40:14Z]   Expected an error to have occurred.  Got:  
INFO[2021-05-01T11:40:14Z]       <nil>: nil                             
INFO[2021-05-01T11:40:14Z]                                              
INFO[2021-05-01T11:40:14Z]   tests/utils.go:515                         
INFO[2021-05-01T11:40:14Z] ------------------------------               
INFO[2021-05-01T11:40:14Z]                                              
INFO[2021-05-01T11:40:14Z] JUnit report was created: /go/src/github.com/kubevirt/hyperconverged-cluster-operator/_out/junit_kv_smoke_tests.xml 
```
/hold

**Comment by tiraboschi** [comment]
waiting to get this in on main branch first

**Comment by orenc1** [comment]
> failing on:
> 
> ```
> INFO[2021-05-01T11:40:14Z] Waiting for namespace kubevirt-test-default1 to be removed, this can take a while ... 
> INFO[2021-05-01T11:40:14Z] failed to dump entity named [sriovnetworknodestates]: the server could not find the requested resource 
> INFO[2021-05-01T11:40:14Z] failed to dump entity named [sriovnetworknodepolicies]: the server could not find the requested resource 
> INFO[2021-05-01T11:40:14Z] failed to dump entity named [sriovnetworks]: the server could not find the requested resource 
> INFO[2021-05-01T11:40:14Z] failed to dump entity named [sriovoperatorconfigs]: the server could not find the requested resource 
> INFO[2021-05-01T11:40:14Z]                                              
> INFO[2021-05-01T11:40:14Z] ------------------------------               
> INFO[2021-05-01T11:40:14Z] Failure [0.000 seconds]                      
> INFO[2021-05-01T11:40:14Z] [AfterSuite] AfterSuite                      
> INFO[2021-05-01T11:40:14Z] tests/tests_suite_test.go:71                 
> INFO[2021-05-01T11:40:14Z]                                              
> INFO[2021-05-01T11:40:14Z]   Timed out after 240.000s.                  
> INFO[2021-05-01T11:40:14Z]   should successfully delete namespace 'kubevirt-test-default1' 
> INFO[2021-05-01T11:40:14Z]   Expected an error to have occurred.  Got:  
> INFO[2021-05-01T11:40:14Z]       <nil>: nil                             
> INFO[2021-05-01T11:40:14Z]                                              
> INFO[2021-05-01T11:40:14Z]   tests/utils.go:515                         
> INFO[2021-05-01T11:40:14Z] ------------------------------               
> INFO[2021-05-01T11:40:14Z]                                              
> INFO[2021-05-01T11:40:14Z] JUnit report was created: /go/src/github.com/kubevirt/hyperconverged-cluster-operator/_out/junit_kv_smoke_tests.xml 
> ```
> 
> /hold

FYI, We are failing on same test case in openshift-ci D/S:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-cnv-cnv-ci-release-4.8-e2e-upgrade/1388893312949161984#1:build-log.txt%3A489

What's preventing `kubevirt-test-default1` namespace to be deleted?

**Pull request closed without merging**
