### PR TITLE
Bump CNAO to version 0.39.0

### PR DESCRIPTION
**Pull request by phoracek**
**Release note**:

```release-note
Bump CNAO to 0.39.0
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by phoracek** [comment]
@nunnatsa the error on e2e is real. No need to retest

**Comment by phoracek** [comment]
The deployment is broken:

```
Degraded	True	NetworkAddonsConfig is degraded: could not apply (/v1, Kind=ConfigMap) kubevirt-hyperconverged/cluster-networks-addons-operator-applied-cluster: could not create (/v1, Kind=ConfigMap) kubevirt-hyperconverged/cluster-networks-addons-operator-applied-cluster: configmaps "cluster-networks-addons-operator-applied-cluster" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```

We need to fix it in a z-stream.

**Pull request closed without merging**
