### PR TITLE
Change the package name to 'community-kubevirt-hyperconverged'

### PR DESCRIPTION
**Pull request by orenc1**
This change is done to avoid conflicts between the community version and a productized operator with the same package name.

Signed-off-by: orenc1 <ocohen@redhat.com>

**Release note**:

```release-note
change HCO package name
```

### CODE REVIEW

**Comment by orenc1** [comment]
Retesting index image lanes after merging https://github.com/openshift/release/pull/15485
/test hco-e2e-image-index-aws
/test hco-e2e-image-index-azure

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by nunnatsa** [comment]
hco-e2e-image-index-aws lane succeeded.
/override ci/prow/hco-e2e-image-index-gcp

**Pull request merged**
