### PR TITLE
Rebuild the CSV due to kubevirt-ssp-operator v1.2.1

### PR DESCRIPTION
**Pull request by tiraboschi**
Rebuild the CSV due to kubevirt-ssp-operator v1.2.1

kubevirt-ssp-operator v1.2.1 has been rebuilt,
rebuilding also the CSV.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by nunnatsa** [comment]
SSP CSV generator is broken.

/hold

**Comment by nunnatsa** [comment]
SSP CSV generator is broken.

/hold

**Comment by ovirt-infra** [comment]
All tests passed

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by ovirt-infra** [comment]
All tests passed

**Pull request merged**
