### PR TITLE
Fix make sanity using an external diff tool

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
/hold
now it should fail on `make sanity` on Travis while it should pass once rebased on top of https://github.com/kubevirt/hyperconverged-cluster-operator/pull/778

**Comment by ovirt-infra** [comment]
All tests passed

**Review by nunnatsa — APPROVED** [review]

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-prev-aws failed due to
```
kubemacpool-mac-controller-manager-7f8d6b7f56-krnd5   0/1     Running   0          29m
kubemacpool-mac-controller-manager-7f8d6b7f56-npxlh   0/1     Running   0          29m
```
due to:
```
E0904 07:52:03.687895       1 server.go:147] failed parsing TLS key: data does not contain a valid RSA or ECDSA private key
```
while with the same set of images hco-e2e-upgrade-prev-azure (exactly the same test but executed on Azure and not on AWS) passed.

@phoracek in that upgrade test we start from quay.io/kubevirt/kubemacpool:v0.14.5 , is that issue supposed to be fixed there?

/override ci/prow/hco-e2e-upgrade-prev-aws

**Comment by phoracek** [comment]
Yeah, this should be fixed in v0.14.5.

This bug was not 100% reproducible, maybe the other lane was just lucky.

**Comment by tiraboschi** [comment]
> Yeah, this should be fixed in v0.14.5.
> 
> This bug was not 100% reproducible, maybe the other lane was just lucky.

Yes, unfortunately I can tell that here and there we still hit that issue so I fear it's still not 100% fixed in v0.14.5.

**Comment by phoracek** [comment]
Would you link me to the issue reproducing on v0.14.5?

For instance, I would not expect to see list of two KubeMacPool pods there, since we lowered the number of replicas to 1.

**Comment by tiraboschi** [comment]
> Would you link me to the issue reproducing on v0.14.5?

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/779/pull-ci-kubevirt-hyperconverged-cluster-operator-master-hco-e2e-upgrade-prev-aws/1301779463528255488/artifacts/hco-e2e-upgrade-prev-aws/pods/
 
> For instance, I would not expect to see list of two KubeMacPool pods there, since we lowered the number of replicas to 1.

in v1.1.0 CSV (prev upstream version) we are pointing to quay.io/kubevirt/cluster-network-addons-operator:0.39.3 and we still see two replicas

**Review by orenc1 — APPROVED** [review]

**Comment by phoracek** [comment]
@tiraboschi we should have CNAO 0.39.4 pinned there if it is for the z-stream.

**Comment by phoracek** [comment]
(If we don't lemme know, I'd fix it)

**Comment by orenc1** [comment]
The current HCO version contains CNAO 0.41.0 and KMP 0.19.0 and it's indeed creating just one KMP replicas.
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/754/pull-ci-kubevirt-hyperconverged-cluster-operator-master-hco-e2e-upgrade-prev-aws/1302506415868350464/artifacts/hco-e2e-upgrade-prev-aws/container-logs/test.log

**Pull request merged**
