### PR TITLE
bump CNAO to 0.27.2

### PR DESCRIPTION
**Pull request by tiraboschi**
bump CNAO to 0.27.2

```release-note
bump CNAO to 0.27.2
```

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

### CODE REVIEW

**Comment by phoracek** [comment]
Simone, we are working on a 0.27.1 release with some bug-fixes, it should be available at the end of today

**Comment by phoracek** [comment]
https://github.com/kubevirt/cluster-network-addons-operator/releases/tag/0.27.1

**Comment by phoracek** [comment]
@tiraboschi are those failures caused by this PR or is the CI just unstable? Can we help you in any way?

**Comment by tiraboschi** [comment]
> @tiraboschi are those failures caused by this PR or is the CI just unstable? Can we help you in any way?

Thanks, I tried to consume it locally with `make cluster-up && make cluster-sync` and it worked for me so I tend to say that the PR is fine.
I just sent https://github.com/kubevirt/hyperconverged-cluster-operator/pull/469 to give it more time and eventually print more details on failures.

**Comment by tiraboschi** [comment]
Here we systematically fail on cert rotation script on kubemacpool.
The issue is reproducible also outside CI env:
```
STEP: verifying that the ceritificate indeed changed

• Failure [179.914 seconds]
Certificates
/go/src/github.com/kubevirt/hyperconverged-cluster-operator/tests/func-tests/certificates_test.go:28
  should rotate kubemacpool certificates [It]
  /go/src/github.com/kubevirt/hyperconverged-cluster-operator/tests/func-tests/certificates_test.go:42

  Expected
      <[]uint8 | len:769, cap:769>: [48, 130, 2, 253, 48, 130, 1, 229, 160, 3, 2, 1, 2, 2, 8, 119, 174, 190, 130, 232, 113, 117, 39, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 26, 49, 24, 48, 22, 6, 3, 85, 4, 3, 19, 15, 119, 101, 98, 104, 111, 111, 107, 45, 99, 101, 114, 116, 45, 99, 97, 48, 30, 23, 13, 50, 48, 48, 50, 50, 52, 49, 55, 51, 55, 51, 55, 90, 23, 13, 50, 49, 48, 50, 50, 51, 49, 55, 51, 55, 51, 56, 90, 48, 58, 49, 56, 48, 54, 6, 3, 85, 4, 3, 19, 47, 107, 117, 98, 101, 109, 97, 99, 112, 111, 111, 108, 45, 115, 101, 114, 118, 105, 99, 101, 46, 107, 117, 98, 101, 118, 105, 114, 116, 45, 104, 121, 112, 101, 114, 99, 111, 110, 118, 101, 114, 103, 101, 100, 46, 115, 118, 99, 48, 130, 1, 34, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 1, 5, 0, 3, 130, 1, 15, 0, 48, 130, 1, 10, 2, 130, 1, 1, 0, 166, 160, 20, 143, 254, 210, 38, 253, 64, 21, 44, 168, 59, 138, 44, 7, 115, 129, 131, 196, 109, 38, 244, 109, 216, 18, 214, 168, 245, 79, 209, 200, 91, 81, 253, 121, 26, 238, 67, 221, 9, 221, 218, 29, 5, 218, 247, 85, 184, 231, 203, 236, 95, 115, 60, 238, 193, 24, 142, 190, 233, 39, 115, 107, 203, 229, 11, 160, 72, 206, 89, 112, 202, 46, 17, 232, 101, 204, 160, 129, 224, 59, 47, 253, 172, 61, 223, 246, 193, 68, 47, 253, 82, 226, 2, 235, 29, 90, 47, 14, 96, 234, 111, 237, 83, 113, 87, 19, 12, 61, 173, 57, 213, 217, 232, 64, 127, 37, 68, 212, 212, 98, 246, 169, 142, 185, 187, 188, 98, 95, 53, 114, 45, 208, 114, 2, 51, 156, 102, 193, 190, 133, 100, 207, 129, 14, 55, 222, 236, 207, 153, 85, 138, 148, 242, 180, 26, 156, 164, 55, 243, 173, 82, 85, 133, 159, 98, 187, 29, 224, 141, 109, 64, 76, 217, 13, 143, 219, 151, 146, 246, 137, 57, 191, 98, 78, 5, 201, 56, 145, 239, 240, 152, 157, 233, 234, 11, 82, 206, 152, 161, 227, 253, 233, 11, 75, 23, 243, 159, 255, 130, 65, 162, 245, 103, 61, 123, 140, 139, 39, 58, 166, 58, 74, 29, 94, 85, 251, 111, 211, 115, 124, 37, 192, 123, 15, 245, 167, 0, 55, 141, 110, 205, 222, 137, 98, 137, 23, 124, 129, 67, 11, 88, 173, 76, 113, 2, 3, 1, 0, 1, 163, 39, 48, 37, 48, 14, 6, 3, 85, 29, 15, 1, 1, 255, 4, 4, 3, 2, 5, 160, 48, 19, 6, 3, 85, 29, 37, 4, 12, 48, 10, 6, 8, 43, 6, 1, 5, 5, 7, 3, 1, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 3, 130, 1, 1, 0, 108, 55, 204, 201, 27, 53, 156, 147, 126, 151, 243, 116, 49, 176, 207, 48, 60, 62, 226, 38, 7, 60, 137, 254, 209, 227, 233, 191, 153, 177, 240, 4, 236, 24, 134, 151, 95, 52, 233, 152, 118, 52, 150, 32, 144, 65, 1, 79, 64, 142, 24, 236, 187, 106, 215, 100, 111, 242, 49, 177, 204, 189, 40, 187, 242, 155, 131, 185, 134, 151, 24, 207, 154, 242, 177, 56, 92, 21, 64, 242, 233, 117, 102, 126, 227, 47, 218, 216, 39, 54, 128, 149, 212, 216, 69, 148, 153, 254, 234, 109, 46, 15, 152, 255, 232, 149, 156, 34, 224, 193, 75, 31, 52, 141, 186, 255, 15, 205, 199, 242, 140, 33, 253, 206, 227, 57, 63, 151, 38, 62, 134, 109, 64, 64, 196, 12, 47, 57, 198, 180, 25, 225, 228, 203, 95, 169, 7, 55, 209, 44, 199, 136, 27, 209, 174, 71, 126, 112, 59, 49, 116, 192, 101, 164, 47, 202, 91, 187, 157, 154, 187, 75, 141, 41, 95, 254, 135, 235, 220, 244, 40, 95, 112, 29, 8, 153, 86, 244, 1, 203, 70, 160, 66, 158, 225, 222, 191, 43, 113, 27, 225, 102, 202, 0, 130, 146, 91, 7, 7, 31, 180, 223, 115, 152, 193, 13, 203, 142, 68, 174, 102, 68, 228, 181, 180, 202, 13, 250, 82, 159, 250, 223, 238, 248, 75, 106, 192, 56, 15, 80, 148, 11, 174, 160, 190, 66, 221, 210, 125, 116, 154, 96, 54, 45, 101, 101]
  not to equal
      <[]uint8 | len:769, cap:769>: [48, 130, 2, 253, 48, 130, 1, 229, 160, 3, 2, 1, 2, 2, 8, 119, 174, 190, 130, 232, 113, 117, 39, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 26, 49, 24, 48, 22, 6, 3, 85, 4, 3, 19, 15, 119, 101, 98, 104, 111, 111, 107, 45, 99, 101, 114, 116, 45, 99, 97, 48, 30, 23, 13, 50, 48, 48, 50, 50, 52, 49, 55, 51, 55, 51, 55, 90, 23, 13, 50, 49, 48, 50, 50, 51, 49, 55, 51, 55, 51, 56, 90, 48, 58, 49, 56, 48, 54, 6, 3, 85, 4, 3, 19, 47, 107, 117, 98, 101, 109, 97, 99, 112, 111, 111, 108, 45, 115, 101, 114, 118, 105, 99, 101, 46, 107, 117, 98, 101, 118, 105, 114, 116, 45, 104, 121, 112, 101, 114, 99, 111, 110, 118, 101, 114, 103, 101, 100, 46, 115, 118, 99, 48, 130, 1, 34, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 1, 5, 0, 3, 130, 1, 15, 0, 48, 130, 1, 10, 2, 130, 1, 1, 0, 166, 160, 20, 143, 254, 210, 38, 253, 64, 21, 44, 168, 59, 138, 44, 7, 115, 129, 131, 196, 109, 38, 244, 109, 216, 18, 214, 168, 245, 79, 209, 200, 91, 81, 253, 121, 26, 238, 67, 221, 9, 221, 218, 29, 5, 218, 247, 85, 184, 231, 203, 236, 95, 115, 60, 238, 193, 24, 142, 190, 233, 39, 115, 107, 203, 229, 11, 160, 72, 206, 89, 112, 202, 46, 17, 232, 101, 204, 160, 129, 224, 59, 47, 253, 172, 61, 223, 246, 193, 68, 47, 253, 82, 226, 2, 235, 29, 90, 47, 14, 96, 234, 111, 237, 83, 113, 87, 19, 12, 61, 173, 57, 213, 217, 232, 64, 127, 37, 68, 212, 212, 98, 246, 169, 142, 185, 187, 188, 98, 95, 53, 114, 45, 208, 114, 2, 51, 156, 102, 193, 190, 133, 100, 207, 129, 14, 55, 222, 236, 207, 153, 85, 138, 148, 242, 180, 26, 156, 164, 55, 243, 173, 82, 85, 133, 159, 98, 187, 29, 224, 141, 109, 64, 76, 217, 13, 143, 219, 151, 146, 246, 137, 57, 191, 98, 78, 5, 201, 56, 145, 239, 240, 152, 157, 233, 234, 11, 82, 206, 152, 161, 227, 253, 233, 11, 75, 23, 243, 159, 255, 130, 65, 162, 245, 103, 61, 123, 140, 139, 39, 58, 166, 58, 74, 29, 94, 85, 251, 111, 211, 115, 124, 37, 192, 123, 15, 245, 167, 0, 55, 141, 110, 205, 222, 137, 98, 137, 23, 124, 129, 67, 11, 88, 173, 76, 113, 2, 3, 1, 0, 1, 163, 39, 48, 37, 48, 14, 6, 3, 85, 29, 15, 1, 1, 255, 4, 4, 3, 2, 5, 160, 48, 19, 6, 3, 85, 29, 37, 4, 12, 48, 10, 6, 8, 43, 6, 1, 5, 5, 7, 3, 1, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 3, 130, 1, 1, 0, 108, 55, 204, 201, 27, 53, 156, 147, 126, 151, 243, 116, 49, 176, 207, 48, 60, 62, 226, 38, 7, 60, 137, 254, 209, 227, 233, 191, 153, 177, 240, 4, 236, 24, 134, 151, 95, 52, 233, 152, 118, 52, 150, 32, 144, 65, 1, 79, 64, 142, 24, 236, 187, 106, 215, 100, 111, 242, 49, 177, 204, 189, 40, 187, 242, 155, 131, 185, 134, 151, 24, 207, 154, 242, 177, 56, 92, 21, 64, 242, 233, 117, 102, 126, 227, 47, 218, 216, 39, 54, 128, 149, 212, 216, 69, 148, 153, 254, 234, 109, 46, 15, 152, 255, 232, 149, 156, 34, 224, 193, 75, 31, 52, 141, 186, 255, 15, 205, 199, 242, 140, 33, 253, 206, 227, 57, 63, 151, 38, 62, 134, 109, 64, 64, 196, 12, 47, 57, 198, 180, 25, 225, 228, 203, 95, 169, 7, 55, 209, 44, 199, 136, 27, 209, 174, 71, 126, 112, 59, 49, 116, 192, 101, 164, 47, 202, 91, 187, 157, 154, 187, 75, 141, 41, 95, 254, 135, 235, 220, 244, 40, 95, 112, 29, 8, 153, 86, 244, 1, 203, 70, 160, 66, 158, 225, 222, 191, 43, 113, 27, 225, 102, 202, 0, 130, 146, 91, 7, 7, 31, 180, 223, 115, 152, 193, 13, 203, 142, 68, 174, 102, 68, 228, 181, 180, 202, 13, 250, 82, 159, 250, 223, 238, 248, 75, 106, 192, 56, 15, 80, 148, 11, 174, 160, 190, 66, 221, 210, 125, 116, 154, 96, 54, 45, 101, 101]

  /go/src/github.com/kubevirt/hyperconverged-cluster-operator/tests/func-tests/certificates_test.go:58
```

**Comment by phoracek** [comment]
@RamLavi could you take a look? Run the rotation webhook manually.

**Comment by tiraboschi** [comment]
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/tools/rotate-certs.sh#L39
@phoracek the cert rotation script is trying to identify kubemacpool pods with `-l app=kubemacpool` but I see that we don't have it anymore.
Is this intended?

**Comment by tiraboschi** [comment]
I think that the issue comes from here: https://github.com/kubevirt/cluster-network-addons-operator/pull/282
In data/kubemacpool/003-deployment.yaml there was `app: kubemacpool` that got lost moving its content to data/kubemacpool/kubemacpool.yaml

**Comment by phoracek** [comment]
@tiraboschi thanks for the analysis. We changed the method of fetching menifests from KubeMacPool and lost the added label in the process. Will fix it today.

**Comment by phoracek** [comment]
@tiraboschi the label should be fixed in https://github.com/kubevirt/cluster-network-addons-operator/releases/tag/0.27.2

**Comment by orenc1** [comment]
/lgtm

As a side note, I wonder if on "bump version" PRs we could only specify the master component version (in this case, CNAO), and its sub-components versions (e.g. nmstate, kubemacpool, ovs-cni etc.) would be provided by the master component.
Currently we need to update each one of them in the environment variable section of the CSV.

/cc @RamLavi

**Comment by tiraboschi** [comment]
> As a side note, I wonder if on "bump version" PRs we could only specify the master component version (in this case, CNAO), and its sub-components versions (e.g. nmstate, kubemacpool, ovs-cni etc.) would be provided by the master component.
> Currently we need to update each one of them in the environment variable section of the CSV.

We are already doing that: 
we point to the new version of CNAO in hack/build-manifests.sh and then the rest is autogenerated

**Comment by phoracek** [comment]
@tiraboschi it passed tests, whaaat

**Comment by tiraboschi** [comment]
> @tiraboschi it passed tests, whaaat

unbelievable :-)
@phoracek do we have also to backport it to release-2.3 branch?

**Comment by phoracek** [comment]
@tiraboschi yes, this should be on 2.3.

**Pull request merged**
