### PR TITLE
drop crs from deploy.sh

### PR DESCRIPTION
**Pull request by phoracek**
CRs should be created by HCO, not via the deploy script.

### CODE REVIEW

**Comment by phoracek** [comment]
@rthallisey @djzager please take a look

**Comment by phoracek** [comment]
@rthallisey maybe there is a misunderstanding on my side. How I understand it is, that we install operators (KubeVirt, cdi, cna, ...) by creating their respective deployment, CRD, RBAC etc. Them HCO is installed, HyperConverged object created and HCO controller creates KubeVirt, NetworkAddonsConfiguration and all the other CRs. in reality however, we create some Cars as a part of this script, that deploys network components before HCO is even started.

This is not a matter of OLM, the script is doing something (creating Cars) that should be done by running HCO.

**Comment by rthallisey** [comment]
@phoracek I read the title a little to quickly, so I thought it said 'crds'.  Can you rebase?

**Comment by phoracek** [comment]
@rthallisey @djzager what is the reason to have download and create CRs in `hack/operator-test.sh`? CRs should be created by HCO, so it tests everything but HCO's functionality. Can we drop it (now when we test using combination of `hack/deploy.sh` and `tests/test.sh`)?

**Comment by rthallisey** [comment]
@phoracek I dropped it in another PR https://github.com/kubevirt/hyperconverged-cluster-operator/pull/180.  I forgot to circle back and close this.

**Comment by phoracek** [comment]
Cool, thanks :)

**Pull request closed without merging**
