### PR TITLE
Revert "[release-1.7] Enable PSA FG on Kubevirt (#2104)"

### PR DESCRIPTION
**Pull request by tiraboschi**
This reverts commit 4492325a0e661fad063199e0676347836dc37b76.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Revert PSA FG on Kubevirt
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
ignoring roundings on coverage
/override coverage/coveralls

**Comment by stu-gott** [comment]
@tiraboschi is this on hold pending merge to main?

**Comment by tiraboschi** [comment]
> @tiraboschi is this on hold pending merge to main?

Yes, just that. We are facing some issue getting it merged on main and on the stabilization branch for 4.12 since PSA is still enforcing restricted by default in OCP/OKD 4.12 and so we have to add some workaround to get it passing our CI.

**Comment by tiraboschi** [comment]
hco-e2e-image-index-aws passed
/override ci/prow/hco-e2e-image-index-azure

hco-e2e-upgrade-prev-index-aws passed
/override ci/prow/hco-e2e-upgrade-prev-index-azure

hco-e2e-upgrade-prev-index-sno-aws passed
/override ci/prow/hco-e2e-upgrade-prev-index-sno-azure

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
