### PR TITLE
Bump CNAO to 0.39.4

### PR DESCRIPTION
**Pull request by phoracek**
With this change, KubeMacPool replicas are reduced to a single one and
with that, leadership election is dropped. This should fix stability
issues that we have repeatedly faced due to the use of 2 replicas
running as active-backup.

Signed-off-by: Petr Horacek <phoracek@redhat.com>

**Release note**:

```release-note
Bump CNAO to 0.39.4
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by orenc1** [comment]
@phoracek , please open this PR against `release-1.1` branch.
`release-2.4` is retired.

**Pull request closed without merging**
