### PR TITLE
Avoid InstallModeTypeMultiNamespace and InstallModeTypeAllNamespaces

### PR DESCRIPTION
**Pull request by tiraboschi**
```release-note
Avoid InstallModeTypeMultiNamespace and InstallModeTypeAllNamespaces to gray out all namespaces option in OLM subscription dialog
```

See:
https://github.com/operator-framework/olm-book/blob/master/docs/operator-scoping.md

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

### CODE REVIEW

**Comment by nunnatsa** [comment]
lgtm

**Comment by tiraboschi** [comment]
Works as expected, I can only select a single namespace, see: https://pasteboard.co/IWQfcER.png
CI is green on all the lanes

**Pull request merged**
