### PR TITLE
[release-1.9] Expose DisableMDEVConfiguration feature gate on HCO API

### PR DESCRIPTION
**Pull request by tiraboschi**
**What this PR does / why we need it**:
* Expose DisableMDEVConfiguration feature gate on HCO API

This is a manual cherry pick of https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2320
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2184439

Signed-off-by: Oren Cohen <ocohen@redhat.com>
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-27889
```

**Release note**:

```release-note
expose DisableMDEVConfiguration feature gate in HCO CR.
```

### CODE REVIEW

**Comment by orenc1** [comment]
to be able to merge this, we need to consume a kubevirt release on `release-0.59` that includes this fix:
https://github.com/kubevirt/kubevirt/pull/9856

@acardace , is there an ETA for tagging/releasing kubevirt v0.59.2 ?

**Comment by davidvossel** [comment]
> @acardace , is there an ETA for tagging/releasing kubevirt v0.59.2 ?

it's out now

**Comment by orenc1** [comment]
> > @acardace , is there an ETA for tagging/releasing kubevirt v0.59.2 ?
> 
> it's out now

Thanks.
I saw, we bumped kubevirt on #2392 and I rebased this PR to use kubevirt 0.59.2.
Now CI has passed and we can merge.
/override coverage/coveralls
/lgtm

**Review by orenc1 — APPROVED** [review]

**Pull request merged**
