### PR TITLE
Remove prom-linter container after test

### PR DESCRIPTION
**Pull request by dharmit**
**What this PR does / why we need it**:
Running sanity check locally leads to dangling containers staying around.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
NONE
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
@dharmit - you'll need to rebase. The MTQ image digest was changed, and so the test could not find the images.

**Comment by dharmit** [comment]
> @dharmit - you'll need to rebase. The MTQ image digest was changed, and so the test could not find the images.

Thanks, @nunnatsa. I've rebased.

**Comment by dharmit** [comment]
Seeing timeouts in three tests and SKU failure in one (Azure).

```
time="2023-08-17T08:27:07Z" level=fatal msg="Failed to run bundle: error waiting for CSV to install: csv failed: reason: \"InstallCheckFailed\", message: \"install timeout\"\n"
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-08-17T08:27:07Z"}
error: failed to execute wrapped command: exit status 1
```

/retest

**Comment by nunnatsa** [comment]
@avlitman @assafad @sradco  - FYI. We should make sure this fix is applied for other components too.

**Comment by avlitman** [comment]
> @avlitman @assafad @sradco - FYI. We should make sure this fix is applied for other components too.

@sradco Can we open a ticket for that?

**Pull request merged**
