### PR TITLE
Bump google.golang.org/protobuf to v1.33.0

### PR DESCRIPTION
**Pull request by nunnatsa**
Manual gathering of #2838, #2839, #2840 and #2841

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-operator-sdk-sno-aws lane succeeded 
/override ci/prow/hco-e2e-upgrade-operator-sdk-sno-azure

**Review by tiraboschi — APPROVED** [review]

**Review by orenc1 — APPROVED** [review]

**Pull request merged**
