### PR TITLE
Fetch junit.xml of func tests into artifacts

### PR DESCRIPTION
**Pull request by erkanerol**
We need junit.xml file in prow artifacts to be able to track flakiness of tests

Signed-off-by: Erkan Erol <eerol@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by erkanerol** [comment]
you can find the junit file here https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/1580/pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws/1455871628234723328/artifacts/hco-e2e-image-index-aws/e2e-test/artifacts/junit.xml

@tiraboschi  is it ok or should it stand here https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/1580/pull-ci-kubevirt-hyperconverged-cluster-operator-main-okd-hco-e2e-image-index-aws/1455871628234723328/artifacts/

**Pull request merged**
