### PR TITLE
hco, Fix CSV image links of nightly builds

### PR DESCRIPTION
**Pull request by oshoval**
Since we pointing to quay, also CSV should be aware of that.
Update the image link to include also the IMAGE_REGISTRY.

Signed-off-by: Or Shoval <oshoval@redhat.com>

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
digester fails without it
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-hco-push-nightly-build-master/1376354117395419136#1:build-log.txt%3A526

**Review by nunnatsa — APPROVED** [review]
/approve

@oshoval - thanks for taking care of this.

**Comment by oshoval** [comment]
@tiraboschi i don't think hco-e2e-kv-smoke-azure is affected by this PR ?

**Comment by nunnatsa** [comment]
> @tiraboschi i don't think hco-e2e-kv-smoke-azure is affected by this PR ?

yes, and now we also configured the test not to run in these cases, but it will work only for new PRs. Overriding.

/override ci/prow/hco-e2e-kv-smoke-azure
/override ci/prow/hco-e2e-kv-smoke-gcp

**Comment by oshoval** [comment]
Thanks @nunnatsa 

@fgimenez can you please run `periodic-hco-push-nightly-build-master` ?

**Comment by fgimenez** [comment]
> @fgimenez can you please run `periodic-hco-push-nightly-build-master` ?

Running here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-hco-push-nightly-build-master/1376452517071687680

**Comment by oshoval** [comment]
Thanks

**Comment by oshoval** [comment]
Passed
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-hco-push-nightly-build-master/1376452517071687680
Thanks all

in case there is any problem / action item please let me know

**Pull request merged**
