### PR TITLE
Refactor digeser to fix sonarClaud issue

### PR DESCRIPTION
**Pull request by nunnatsa**
In order to reduce the number of the "critical" sonarClaud warning, the PR fixes the following warning:

In `tools/digester/main.go`: Refactor this method to reduce its Cognitive Complexity from 26 to the 15 allowed.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zcahana** [comment]
@nunnatsa see the above [comment](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1080#issuecomment-764693443) about invalid commit message preventing this from being merged.

**Comment by nunnatsa** [comment]
> @nunnatsa see the above [comment](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1080#issuecomment-764693443) about invalid commit message preventing this from being merged.

Done. Please check again.

**Pull request merged**
