### PR TITLE
[release-1.8] Bump fedora image (#2233)

### PR DESCRIPTION
**Pull request by tiraboschi**
Bump fedora image used for various internal
images to fedora:37

This is a manual cherry-pick of #2233

Signed-off-by: stirabos <stirabos@redhat.com>

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
ignoring obsolete k8s-1.23
/override pull-hyperconverged-cluster-operator-e2e-k8s-1.23

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
