### PR TITLE
[release-1.7] test: get authorization token with TokenRequest API

### PR DESCRIPTION
**Pull request by tiraboschi**
test: get authorization token with TokenRequest API

Fix CI getting authorization token for prometheus
with TokenRequest API.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
hco-e2e-image-index-azure passed
/override hco-e2e-image-index-aws

**Comment by tiraboschi** [comment]
hco-e2e-image-index-azure passed
/override ci/prow/hco-e2e-image-index-aws

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
