### PR TITLE
Consume Kubevirt nightly from 20230125 while waiting for v0.59.0

### PR DESCRIPTION
**Pull request by tiraboschi**
This is needed to consume the new seccompConfiguration API that was not available in v0.59.0-alpha.2 (see: https://github.com/kubevirt/kubevirt/pull/8917 ) and duie to some internal reasons v0.59.0-alpha.3 tag ca not be created on kubevirt/kubevirt side.

TODO: revert to the regular flow as soon as the next tagged kv v0.59.0 is available.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by acardace — APPROVED** [review]

**Review by acardace — APPROVED** [review]

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
