### PR TITLE
Simplify the introduction to HCO

### PR DESCRIPTION
**Pull request by maya-r**

### CODE REVIEW

**Comment by djzager** [comment]
You will need to `git commit --amend --signoff` before this can be merged.

**Comment by djzager** [comment]
@maya-r you will need to do `git commit --amend --signoff` before this can go in.

**Comment by rthallisey** [comment]
ci test please

**Comment by rthallisey** [comment]
ci test please

**Comment by maya-r** [comment]
ping

**Comment by rwsu** [comment]
ci test please

**Pull request merged**
