### PR TITLE
Remove a CI hack

### PR DESCRIPTION
**Pull request by tiraboschi**
Remove a small hack introduced only to be able
to easily test #898 on CI

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by ovirt-infra** [comment]
All tests passed

**Review by orenc1 — APPROVED** [review]

**Comment by nunnatsa** [comment]
hco-e2e-aws passed.
/override ci/prow/hco-e2e-azure

**Pull request merged**
