### PR TITLE
chore: bump ssp-operator to v0.18.0

### PR DESCRIPTION
**Pull request by codingben**
**What this PR does / why we need it**:

Bump ssp-operator to v0.18.0.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [✓] PR Message
- [✓] Commit Messages
- [✓] How to test
- [✓] Unit Tests
- [✓] Functional Tests
- [✓] User Documentation
- [✓] Developer Documentation
- [✓] Upgrade Scenario
- [✓] Uninstallation Scenario
- [✓] Backward Compatibility
- [✓] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-30049
```

**Release note**:

```release-note
Bump ssp-operator to v0.18.0.
```

### CODE REVIEW

**Comment by lyarwood** [comment]
Can you close this out in favour of https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2390 ?

Also I thought we had automation for pulling in SSP Operator releases?

**Comment by codingben** [comment]
As discussed, seems like the automation didn't work because we had a new API introduced.

This PR is replaced by #2398.

**Pull request closed without merging**
