### PR TITLE
Fix Dependabot Alert in github.com/docker/distribution

### PR DESCRIPTION
**Pull request by orenc1**
Details:
https://github.com/kubevirt/hyperconverged-cluster-operator/security/dependabot/2
https://deps.dev/advisory/GHSA/GHSA-qq97-vm5h-rrhg

Signed-off-by: orenc1 <ocohen@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by machadovilaca** [comment]
I don't have permission to access the link in the description. Can you provide a quick overview or a print of the problem in the PR description so that everyone is able to see it?

**Comment by orenc1** [comment]
> I don't have permission to access the link in the description. Can you provide a quick overview or a print of the problem in the PR description so that everyone is able to see it?

Yes, here it is:
image

https://deps.dev/advisory/GHSA/GHSA-qq97-vm5h-rrhg

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
