### PR TITLE
Fix readme to contain $ before the bash commands

### PR DESCRIPTION
**Pull request by avlitman**
**What this PR does / why we need it**:
Fix to align with the rest of the readme file.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```
none

```

**Release note**:

```
none

```

### CODE REVIEW

**Comment by nunnatsa** [comment]
@avlitman, I think the sanity fails because this PR needs rebase. Also, please fix the PR title and description to reflect the actual chnage.

**Comment by avlitman** [comment]
Thanks Nahshon, just why it’s not reflecting the actual change?

Aviv Litman

BI Software Engineer

Red Hat <https://www.redhat.com/>

***@***.***
<https://www.redhat.com/>

**Comment by avlitman** [comment]
> why it’s not reflecting the actual change?
> Because the PR adds the `$` sign, not removing it.

Sorry got confused with other pr I have, fixed

**Comment by avlitman** [comment]
@nunnatsa Strange that sanity is still faring I did a rebase

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
