### PR TITLE
Handle two todo comments to reduce sonarCloud warnings

### PR DESCRIPTION
**Pull request by nunnatsa**
The "TODO" in tools/csv-merger/csv-merger.go line 365 was removed because the OLM bug was fixed. Removed also the relevant temporary code.

The "TODO" in pkg/components/components.go line 285 was removed because it became wrong. We do want a separate API (webhook) pod, and it's here to stay.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by erkanerol** [comment]
@nunnatsa could you please add some details into PR description about why you deleted the TODO statements. One of them is clear (bug is fixed) but the other one is not clear.

**Comment by nunnatsa** [comment]
> @nunnatsa could you please add some details into PR description about why you deleted the TODO statements. One of them is clear (bug is fixed) but the other one is not clear.

Done

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
