### PR TITLE
fix wrong mkdir flag in upgrade-test-operator-sdk.sh

### PR DESCRIPTION
**Pull request by nunnatsa**
## What this PR does / why we need it
Fix several issues with the upgrade-test-operator-sdk script, including:
* `mkdir -f` ==> `mkdir -p`
* restore the compare_scc script, and use the shared dir for the output files.

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
hco-e2e-kv-smoke-gcp lane passed
/override ci/prow/hco-e2e-kv-smoke-azure
hco-e2e-upgrade-index-azure lane passed
/override ci/prow/hco-e2e-upgrade-index-aws

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-prev-index-sno-aws lane passed
/override ci/prow/hco-e2e-upgrade-prev-index-sno-azure
okd-hco-e2e-upgrade-index-aws lane passed
/override ci/prow/okd-hco-e2e-upgrade-index-gcp

**Pull request merged**
