### PR TITLE
Remove the KubevirtHyperconvergedClusterOperatorInstallationNotCompletedAlert alert

### PR DESCRIPTION
**Pull request by nunnatsa**
This is postponed to the next version.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
trying to trigger the CI
closing and reopening.

**Comment by nunnatsa** [comment]
Ignore tiny cpverage reduction 
/override coverage/coveralls

**Review by orenc1 — APPROVED** [review]
/approved

**Pull request merged**
