### PR TITLE
[release 1.11] Bump AAQ to v1.1.4, and rename the component name

### PR DESCRIPTION
**Pull request by nunnatsa**
## What this PR does / why we need it
AAQ now called "application-aware-quota". One of the configuration field name also renamed.

This PR changes the import path of AAQ to the new path, bumps it to v1.1.4, and rename the component and the
`enableClusterAppsResourceQuota` field to
`allowApplicationAwareClusterResourceQuota`, to match the rename in AAQ.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-37898
```

**Release note**:

```release-note
Bump AAQ to v1.1.4
```

### CODE REVIEW

**Comment by dominikholler** [comment]
@nunnatsa can you please add
```
Jira-Ticket: https://issues.redhat.com/browse/CNV-37898
```
to the description of the PR?

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
hco-e2e-kv-smoke-gcp lane passed
/override ci/prow/hco-e2e-kv-smoke-azure

hco-e2e-upgrade-prev-operator-sdk-sno-aws lane passed
/override ci/prow/hco-e2e-upgrade-prev-operator-sdk-sno-azure

**Comment by nunnatsa** [comment]
closed in favor of #2790

**Pull request closed without merging**
