### PR TITLE
Bump kubevirt.io/kubevirt to 0.26.0

### PR DESCRIPTION
**Pull request by tiraboschi**
Bump kubevirt.io/kubevirt to 0.26.0 and cascade
update all the dependencies pinning to
kubernetes-1.16.4 as for kubevirt.io/kubevirt to 0.26.0

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

### CODE REVIEW

**Comment by tiraboschi** [comment]
ci test please

**Comment by rmohr** [comment]
@tiraboschi I think that the CDI rotate test may fail because CDI changed cert code recently.

/cc @mhenriks

**Pull request merged**
