### PR TITLE
[release 1.10] Fix community CSV

### PR DESCRIPTION
**Pull request by nunnatsa**
## What this PR does / why we need it
The community index image is failing at community-operators-prod (https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3946)

This PR fixes several issue in the community bundle:
* allow installing the HCO operator on the "community-kubevirt-hyperconverged" and "community-kubevirt-hyperconverged-target" namespaces.
* add the template-validator image to the related images field in the CSV, and use digest instead of image tag.
* Add missing feature annotations to the CSV

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-prev-operator-sdk-sno-aws lane succeeded 
/override ci/prow/hco-e2e-upgrade-prev-operator-sdk-sno-azure

**Comment by nunnatsa** [comment]
hco-e2e-kv-smoke-gcp lane succeeded
/override ci/prow/hco-e2e-kv-smoke-azure

**Pull request merged**
