### PR TITLE
[release-1.10] Manually upgrade components

### PR DESCRIPTION
**Pull request by nunnatsa**
CDI: v1.57.0-rc1 ==> v1.57.0
MTQ: v1.1.0 ==> v1.1.1
KUBEVIRT_CONSOLE_PROXY v0.0.5 ==> v0.0.6

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
Bump CDI to v1.57.0
Bump MTQ to v1.1.1
Bump KUBEVIRT_CONSOLE_PROXY to v0.0.6
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-operator-sdk-azure lane passed
/override ci/prow/hco-e2e-upgrade-operator-sdk-aws
hco-e2e-upgrade-prev-operator-sdk-sno-azure lane passed
/override ci/prow/hco-e2e-upgrade-prev-operator-sdk-sno-aws

**Review by avlitman — APPROVED** [review]

**Pull request merged**
