### PR TITLE
Revert "consider NMO as an external operator (#737)"

### PR DESCRIPTION
**Pull request by tiraboschi**
This reverts commit c667368c2794d6b4592ea55a46db211f31d18a01.

Bug-Url: https://bugzilla.redhat.com/1874822
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Directly ship NMO
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
all the lanes passed on AWS, the same lanes fails on Azure just due to quota issues. No need to wait for them.
/override ci/prow/hco-e2e-azure
/override ci/prow/hco-e2e-upgrade-azure
/override ci/prow/hco-e2e-upgrade-prev-azure

**Comment by orenc1** [comment]
/hold
Reverting is currently not required, as it was discovered that the issue was 4.5/4.6 olm build tools compatibility:
https://bugzilla.redhat.com/show_bug.cgi?id=1866861

**Comment by tiraboschi** [comment]
/unhold
Now we need this as for: https://bugzilla.redhat.com/1874822

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
hco-e2e-aws passed and it's exactly the same test
/override ci/prow/hco-e2e-azure

**Pull request merged**
