### PR TITLE
[Release 1.6] Set the CDI version to v1.43.2

### PR DESCRIPTION
**Pull request by nunnatsa**
The CDI version for release 1.6 should be v1.43.x

This version should contain a fix to a golden images issue.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Set the CDI version to v1.43.2
```

### CODE REVIEW

**Review by orenc1 — APPROVED** [review]

**Comment by nunnatsa** [comment]
/override ci/prow/hco-e2e-upgrade-index-aws
/ovrride ci/prow/hco-e2e-upgrade-index-azure

upgrade test can't work because CDI can't update the version to older one.

**Pull request merged**
