### PR TITLE
Revert "Use predicates to prevent noisy reconcile (#318)"

### PR DESCRIPTION
**Pull request by djzager**
This reverts commit f4db8ee2827708eb140f8b1c61f93423f82c3ab7.

Signed-off-by: David Zager <dzager@redhat.com>

### CODE REVIEW

**Comment by rthallisey** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci please test

**Comment by tiraboschi** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci test please

**Pull request merged**
