### PR TITLE
Bump VM_IMPORT to v0.2.4

### PR DESCRIPTION
**Pull request by pkliczewski**
Bump VM_IMPORT to v0.2.4

**Release note**:
```release-note
Bump VM_IMPORT to v0.2.4
```

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by pkliczewski** [comment]
@tiraboschi This version bump contain bug fixes which should be backported to 2.5

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by pkliczewski** [comment]
placement job failed with:

> error: 'node-role.kubernetes.io/worker' already has a value (), and --overwrite is false

**Comment by pkliczewski** [comment]
@tiraboschi I am not able to `retest` failed job. Please advice what should I do

**Review by tiraboschi — APPROVED** [review]

**Comment by ovirt-infra** [comment]
All tests passed

**Pull request merged**
