### PR TITLE
Bump CDI to v1.13.1

### PR DESCRIPTION
**Pull request by tiraboschi**
```release-note
Bump CDI to v1.13.1
```

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

### CODE REVIEW

**Comment by orenc1** [comment]
@tiraboschi , could you please explain why in order to bump a version of cdi you need also to change CDI's go code under `vendor` ?
Thanks
/cc @nunnatsa

**Comment by tiraboschi** [comment]
> @tiraboschi , could you please explain why in order to bump a version of cdi you need also to change CDI's go code under `vendor` ?

because we consume CDI CRD definition as `cdiv1alpha1 "kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1"`, see:
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/pkg/controller/hyperconverged/hyperconverged_controller.go#L38
and we need its newer version

**Pull request merged**
