### PR TITLE
Move to go version 1.16.4 (latest)

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Reviewer Checklist**

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by orenc1 — COMMENTED** [review]
@nunnatsa , why in some places you've put just `1.16` (replacing `1.15.10` or `1.15.11`) and in others you included the z-stream (`1.16.4`)?

**Comment by nunnatsa** [comment]
> @nunnatsa , why in some places you've put just `1.16` (replacing `1.15.10` or `1.15.11`) and in others you included the z-stream (`1.16.4`)?

I set 1.16 on github actions because it takes the latest 1.6.x (currently 1.16.4)

**Comment by orenc1** [comment]
> > @nunnatsa , why in some places you've put just `1.16` (replacing `1.15.10` or `1.15.11`) and in others you included the z-stream (`1.16.4`)?
> 
> I set 1.16 on github actions because it takes the latest 1.6.x (currently 1.16.4)

if you pull `golang:1.16`, it will also pull the latest version in 1.6.z (currently 1.16.4)

**Comment by nunnatsa** [comment]
> if you pull `golang:1.16`, it will also pull the latest version in 1.6.z (currently 1.16.4)

Right, but when we are building an image, I think we want more control, and on the github action I think we can be more flexible and get the latest version.

**Comment by orenc1** [comment]
> > if you pull `golang:1.16`, it will also pull the latest version in 1.6.z (currently 1.16.4)
> 
> Right, but when we are building an image, I think we want more control, and on the github action I think we can be more flexible and get the latest version.

Makes sense.
/approve
/lgtm

**Pull request merged**
