### PR TITLE
use pre-prepared image for kubevirtci tests

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
/unhold

@tiraboschi, please review the [tests/README.md](tests/README.md) file

**Comment by tiraboschi** [comment]
ci/prow/hco-e2e-upgrade-aws currently runs on OCP 4.5 and it's going to fail due to a side effect in the fix of https://bugzilla.redhat.com/1825330
It will be addressed on operator-framework/operator-lifecycle-manager#1470 on OLM side.
Temporary ignoring it
/override ci/prow/hco-e2e-upgrade-aws

**Pull request merged**
