### PR TITLE
Add api documentation with po-docgen

### PR DESCRIPTION
**Pull request by erkanerol**
Signed-off-by: Erkan Erol <eerol@redhat.com>

The docgen in this PR is based on https://github.com/prometheus-operator/prometheus-operator/blob/8497a67b735e65ad779ed19c95a17ffd1c8fbb64/cmd/po-docgen/api.go with small modifications. I added a warning into the top of the file like https://github.com/kubermatic/kubecarrier/blob/master/hack/docgen/main.go. 

Also, I added `default` column into tables by using `// +kubebuilder:default=` comments of fields.

**Release note**:
```release-note
Adds api.md for documenting HyperConverged custom resource.
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
The main relevant gap is a column with the default values.

**Comment by erkanerol** [comment]
@tiraboschi  I added the default column as well.

Now, we have no links/details about `sdkapi.NodePlacement` in our api doc.  We are capable of linking external docs for specific types but I  didn't find any doc in kubevirt side for it.

**Comment by tiraboschi** [comment]
> @tiraboschi I added the default column as well.
> 
> Now, we have no links/details about `sdkapi.NodePlacement` in our api doc. We are capable of linking external docs for specific types but I didn't find any doc in kubevirt side for it.

it comes from here:
https://github.com/kubevirt/controller-lifecycle-operator-sdk/blob/master/pkg/sdk/api/types.go#L47-L73

**Comment by erkanerol** [comment]
> it comes from here:
> https://github.com/kubevirt/controller-lifecycle-operator-sdk/blob/master/pkg/sdk/api/types.go#L47-L73

@tiraboschi I know that but I am not sure about adding a link to that code piece. Ideally, kubevirt should have a similar api.doc and we should give reference to it like https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1153/files?file-filters%5B%5D=.go&file-filters%5B%5D=No+extension#diff-2382062fe63633346f18b90b432fbb47253ed2d335afa748ddcc32dad693fd98R43

Do you think we should give a reference to code?

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
