### PR TITLE
Intercept delete in validating webhook

### PR DESCRIPTION
**Pull request by yuvalturg**
Previously, when trying to delete the HCO resource while VMs exist in
the cluster, the HCO would stay in Terminating state.  This patch
implements a webhook that intercepts delete requests for the HCO.
When validating a delete request, the webhook will try to remove the
KubeVirt and CDI resources in dry run mode, and reject the request in
case the removal of those resources fail.

Signed-off-by: Yuval Turgeman <yturgema@redhat.com>

**Release note**:

```release-note
Intercept delete requests in validating webhook
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by yuvalturg** [comment]
> I still think HyperConverged is the wrong place for the New resource methods. But if this is the only option, then all of the sub resource creation methods should be there, not only few of them.

True, they should all be there, but I only moved those that were on the way towards sharing the deletion code.  We can address them in a different patch.
As for the location, like we discussed previously, I really dont mind moving it to a HyperConvergedFactory, but it should be part of v1alpha1, otherwise we go into cyclic imports etc

**Pull request merged**
