### PR TITLE
Add Insecure Registries for Imported containerized Data Images

### PR DESCRIPTION
**Pull request by nunnatsa**
Added API to configure the insecure registries for imported containerized data images.

## API Changes
If there is a need to import data images from an insecure registry, these registries should be added to the `insecureRegistries` field under the `storageImport` field in the `HyperConverged`'s spec field.

### Insecure Registry Example

``` yaml
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
spec:
  insecureRegistries:
    storageImport:
      - "private-registry-example-1:5000"
      - "private-registry-example-2:5000"
      ...
```

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Reviewer Checklist**

- [x] PR Message
- [x] Commit Messages
- [ ] How to test
- [x] Unit Tests
- [ ] Functional Tests
- [x] User Documentation
- [x] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Added API to configure the insecure registries for imported containerized data images.

## API Changes
If there is a need to import data images from an insecure registry, these registries should be added to the `insecureRegistries` field under the `storageImport` field in the `HyperConverged`'s spec field.
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
This PR currently only contains the API, with no related implementation. The imp[lementation is blocked by https://github.com/kubevirt/containerized-data-importer/pull/1754 and a new CDI version.

/hold

**Comment by mhenriks** [comment]
👍

**Comment by tiraboschi** [comment]
The API looks fine to me.

**Comment by tiraboschi** [comment]
NEW MISSED LINES IN DIFF are only on generated code, ignoring them
/override coverage/coveralls

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
Closing and re-opening to release stuck test

**Comment by tiraboschi** [comment]
NEW MISSED LINES IN DIFF are only on generated code, ignoring them
/override coverage/coveralls

**Pull request merged**
