### PR TITLE
SSP: update manifests to v1.0.4

### PR DESCRIPTION
**Pull request by fromanirh**
Changes after 1.0.1 are only in manifests, not in the pkg/API.

Fixes: https://bugzilla.redhat.com/1719333
Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
@djzager @tiraboschi I tested this PR in the following way:
it affects only CSVs/ RBAC rules, so I downloaded deploy.sh (as per
https://github.com/kubevirt/hyperconverged-cluster-operator/#using-the-hco
)
and changed to use local, patched cluster_role.yaml and operator.yaml, the latter referring to an image built from master (should not be relevant)
deployed HCO, deployed SSP stuff, the template validator works. going to doublecheck node labels and templates in a short while.

**Comment by fromanirh** [comment]
labels and templates looks OK too

**Comment by fromanirh** [comment]
tested scratch build, looks good.

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by fromanirh** [comment]
and here's the backport to release-2.0: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/126

**Comment by rthallisey** [comment]
@fromanirh needs a backport.  Please cc @tiraboschi on the PR.

**Pull request merged**
