### PR TITLE
[release-2.1] Update MRO to v0.3.12 (#287)

### PR DESCRIPTION
**Pull request by cynepco3hahue**
* Update MRO to v0.3.12

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

* Update CSV manifest via build-manifest.sh

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@rthallisey cherry-pick to release-2.1

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by rthallisey** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by arachmani** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by arachmani** [comment]
ci test please

**Comment by djzager** [comment]
ci tests please

**Comment by cynepco3hahue** [comment]
mm it failed to get machineset
```
++ oc -n openshift-machine-api get machineset --no-headers
++ grep worker
++ awk '{print $1}'
Unable to connect to the server: EOF
```

**Comment by cynepco3hahue** [comment]
ci tests please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by djzager** [comment]
ci test please

**Comment by djzager** [comment]
@cynepco3hahue this lgtm. Let me know if you want to hold it. I'll merge when I get in tomorrow otherwise.

**Comment by cynepco3hahue** [comment]
@djzager you can merge it, I believe I will have the answer regarding MRO under the HCO in 1-2 days, in the worst case I will create the PR to remove all MRO stuff from the HCO and will cherry-pick it to release-2.1

**Pull request merged**
