### PR TITLE
Avoid deploying NodeLabellerBundle when running with KVM_EMULATION

### PR DESCRIPTION
**Pull request by tiraboschi**
Avoid deploying NodeLabellerBundle when running
with KVM_EMULATION because it will be completely useless

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Avoid deploying NodeLabellerBundle when running with KVM_EMULATION
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by dankenigsberg** [comment]
@tiraboschi  would you explain the motivation for this PR? What are its downsides?

**Comment by tiraboschi** [comment]
> @tiraboschi would you explain the motivation for this PR? What are its downsides?

We are already configuring KubevirtNodeLabellerBundle according to KVM_EMULATION env variable with a parameter in the spec section of its CR, see:
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/pkg/controller/hyperconverged/hyperconverged_controller.go#L1276

But I understood from @ksimon1 that this is just a waste of resources and deployment time because even in that case KubevirtNodeLabeller will be instantiated by SSP operator although completely useless.

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ksimon1** [comment]
> > @tiraboschi would you explain the motivation for this PR? What are its downsides?
> 
> We are already configuring KubevirtNodeLabellerBundle according to KVM_EMULATION env variable with a parameter in the spec section of its CR, see:
> https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/pkg/controller/hyperconverged/hyperconverged_controller.go#L1276
> 
> But I understood from @ksimon1 that this is just a waste of resources and deployment time because even in that case KubevirtNodeLabeller will be instantiated by SSP operator although completely useless.

Yes, that is correct. If labeller doesn't have access to kvm, it is useless, because it can report falsely usable cpu model / feature.

**Comment by tiraboschi** [comment]
ignoring sliglty decreased code coverage because we cannot really rely on real KVM support on upstream CI environments
/override coverage/coveralls

**Comment by tiraboschi** [comment]
obsolete

**Pull request closed without merging**
