### PR TITLE
Support KV's WithHostPassthroughCPU feature gate

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Release note**:

```release-note
Support KV's WithHostPassthroughCPU feature gate in th HyperConverged API
```

### CODE REVIEW

**Comment by dankenigsberg** [comment]
> Signed-off-by: Nahshon Unna-Tsameret [nunnatsa@redhat.com](mailto:nunnatsa@redhat.com)
> 
> **Release note**:
> 
> ```
> Support KV's WithHostPassthroughCPU feature gate in th HyperConverged API
> ```

Could you add a word about what is the suggested API and the background for it? What is its default?
Do we have an annotated example for the HCO CR where this case be added?

**Comment by nunnatsa** [comment]
Closed in favor of #1037

**Pull request closed without merging**
