### PR TITLE
manually bump KubeVirt to v0.56.0

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

```release-note
Bump Kubevirt to version v0.56.0
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-index-sno-aws lane succeeded.
/override ci/prow/hco-e2e-upgrade-index-sno-azure

**Review by orenc1 — APPROVED** [review]
/approve

**Comment by nunnatsa** [comment]
hco-e2e-upgrade-index-aws lane succeeded.
/override ci/prow/hco-e2e-upgrade-index-azure

**Pull request merged**
