### PR TITLE
Bump CDI to v1.23.0

### PR DESCRIPTION
**Pull request by tiraboschi**
Bump CDI to v1.23.0

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Bump CDI to v1.23.0
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
CSV generation on CDI image currently fails with:
```
+++ docker run --rm --entrypoint=/usr/bin/csv-generator docker.io/kubevirt/cdi-operator:v1.23.0 --namespace=kubevirt-hyperconverged --csv-version=1.2.0 --pull-policy=IfNotPresent --operator-image=docker.io/kubevirt/cdi-operator@sha256:4bda8ef08088109e3b32c43a1bbca6034d61377209f69b14de603a302e094b46 --controller-image=docker.io/kubevirt/cdi-controller@sha256:09490442032bf23071ec9b97575b205a4b89b79b28413c2fd18bf42a8700403b --apiserver-image=docker.io/kubevirt/cdi-apiserver@sha256:eef80737010f408579daab4912246cbbae7eb48697b88b0adec1144a47198238 --cloner-image=docker.io/kubevirt/cdi-cloner@sha256:ee7f77167ac7e971c32ac55d984e49f01838c0ce7917130e0768c7bdc1e22652 --importer-image=docker.io/kubevirt/cdi-importer@sha256:93752eb5183ff7ff200ab316cc118e61c8d7febbf921d438140637e607326ab8 --uploadproxy-image=docker.io/kubevirt/cdi-uploadproxy@sha256:4d59bdcd60514947b767e579ef0d5d7cd53ee78a41e056c1a74f6ea0c9ebf08f --uploadserver-image=docker.io/kubevirt/cdi-uploadserver@sha256:2d3fa226dffd85947d8ede1cd6e262dff9a2533becb214b64b59d6da51b0aac3 --operator-version=v1.23.0 --dump-crds
panic: 'go list' driver requires 'go', but executable file not found in $PATH
 
goroutine 1 [running]:
kubevirt.io/containerized-data-importer/pkg/operator/resources/operator.createCDIListCRD(0x1f0ec60)
        pkg/operator/resources/operator/operator.go:307 +0x71e
kubevirt.io/containerized-data-importer/pkg/operator/resources/operator.NewCdiCrd(...)
        pkg/operator/resources/operator/factory.go:102
main.main()
        tools/csv-generator/csv-generator.go:73 +0x296
```

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
Closing for https://github.com/kubevirt/hyperconverged-cluster-operator/pull/803

**Pull request closed without merging**
