### PR TITLE
Expose VirtualMachineOptions.DisableSerialConsoleLog API

### PR DESCRIPTION
**Pull request by tiraboschi**
**What this PR does / why we need it**:
Expose VirtualMachineOptions.DisableSerialConsoleLog API to let the cluster admin enable/disable
collecting serial console logs for VMs at cluster level. The value can be individually overridden for each VM, not relevant if AutoattachSerialConsole is disabled for the VM.

Rework #2508 for consistency with other defaults.

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
https://issues.redhat.com/browse/CNV-35035
```

**Release note**:

```release-note
Expose VirtualMachineOptions.DisableSerialConsoleLog API
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
/hold
let's wait for https://github.com/kubevirt/cluster-network-addons-operator/pull/1695

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
