### PR TITLE
Reconcile IMS ConfigMap

### PR DESCRIPTION
**Pull request by tiraboschi**
IMS ConfigMap should be reconciled to HCO opinionated values.

Fixes: https://bugzilla.redhat.com/1879993

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Reconcile IMS ConfigMap
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
WIP: missing unit tests
/hold

**Comment by ovirt-infra** [comment]
All tests passed

**Review by nunnatsa — APPROVED** [review]

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
Ignoring slightly reduced coverage tests 
/override coverage/coveralls

**Review by nunnatsa — APPROVED** [review]
/approve

**Pull request merged**
