### PR TITLE
[release-1.7]: Kubevirt: Enforce limits & requests by a configurable ratio

### PR DESCRIPTION
**Pull request by iholder101**
Manual backport of https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2206

**Release note**:

```release-note
Kubevirt: Enforce limits & requests by a configurable ratio
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
Can you please start form release-1.8 first?

**Comment by fabiand** [comment]
/hold

just to clarify the scope

**Comment by tiraboschi** [comment]
k8s-1.23 provider is now unmaintained
/override pull-hyperconverged-cluster-operator-e2e-k8s-1.23

**Comment by tiraboschi** [comment]
ignoring roundings on coverage
/override coverage/coveralls

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-prev-index-aws lane succeeded.
/override ci/prow/hco-e2e-upgrade-prev-index-azure
hco-e2e-upgrade-index-azure lane succeeded.
/override ci/prow/hco-e2e-upgrade-index-aws

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
