### PR TITLE
Reduce the memory footprint using cache selectors

### PR DESCRIPTION
**Pull request by tiraboschi**
Move to controller-runtime 0.9.0
that let us set SelectorsByObject on its cache
to reduce the memory usage selecting a subset
of the objects (still tbd here).

Used a different go.mod for tests/ because
controller-runtime 0.9.0 requires k8s.io/api v0.21.0
while kubevirt.io/client-go is not compatible
with them.

Setting filters on cached PriorityClass, ConfigMap,
Service, ServiceMonitor, PrometheusRule.

Now that we have filters, start watching also ConfigMaps.

Fixes: https://bugzilla.redhat.com/1935219

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Reviewer Checklist**

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
Reduce the memory footprint using cache selectors
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

/hold
Wait for #1384

**Comment by tiraboschi** [comment]
ready
/unhold

**Pull request merged**
