### PR TITLE
KubeVirt: always set the feature gate that disables the custom SELinux policy

### PR DESCRIPTION
**Pull request by jean-edouard**
**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
All VMIs now run under the same SELinux domain as regular pods.
```

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by jean-edouard** [comment]
Just force-pushed rebase on top of main to include the kubevirt bump.

**Review by tiraboschi — APPROVED** [review]

**Comment by tiraboschi** [comment]
ignoring slightly decreased coverage
/override coverage/coveralls

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-index-sno-aws succeeded.
/override hco-e2e-upgrade-index-sno-azure

**Comment by tiraboschi** [comment]
hco-e2e-upgrade-index-sno-aws succeeded.
/override ci/prow/hco-e2e-upgrade-index-sno-azure

**Pull request merged**
