### PR TITLE
Add golangci-lint into project and solve existing issues

### PR DESCRIPTION
**Pull request by erkanerol**
This PR adds [golangci-lint](https://golangci-lint.run/) into the sanity checks and fixes the existing issues. 

The installation of the linter is explained here: https://golangci-lint.run/usage/install/#local-installation

Reasons behind the decisions in this PR:

- I didn't put the linter into `make sanity` since we are calling it different places and to install `golangci-lint` into everywhere is a burden. I put another make target and add the github action of the linter for pipeline. Therefore, you can run `make lint` in your local environment to see the results and we will have the results per PR via Github Actions.

-  The places I used `panicOnError` are used by only tools, not the production code. When there is a problem, it will panic on our CI and we need to fix them, which is the same path we follow at the moment. 

- For the [issue](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1229/files#diff-da260dc44899001213de724418b4aa355f6cc7cec09867aa2e37d4420fccea3cL323) in `hyperconverged_controller.go`, I put `TODO`. We will solve it with a dedicated PR.

- I removed unused `findApi` function which requires openshift security api. When I removed the func, we don't need to have the vendored codes. 

- The `validate` method in `vmImport.go ` was unused. The logic exists in the `NewIMSConfigForCR` function.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by tiraboschi** [comment]
/hold

this PR is breaking KV smoke tests:
```
INFO[2021-04-07T15:08:45Z] + /go/src/github.com/kubevirt/hyperconverged-cluster-operator/_out/kv_smoke_tests.test -cdi-namespace=*********************** -config=hack/test-config.json -installed-namespace=*********************** -junit-output=/go/src/github.com/kubevirt/hyperconverged-cluster-operator/_out/junit_kv_smoke_tests.xml -kubeconfig=/tmp/kubeconfig-246992338 '-ginkgo.focus=(rfe_id:1177)|(rfe_id:273)|(rfe_id:151)' -ginkgo.noColor -ginkgo.seed=0 '-ginkgo.skip=(Slirp Networking)|(with CPU spec)|(with TX offload disabled)|(with cni flannel and ptp plugin interface)|(with ovs-cni plugin)|(test_id:1752)|(SRIOV)|(with EFI)|(Operator)|(GPU)|(DataVolume Integration)|(when virt-handler is not responsive)|(with default cpu model)|(should set the default MachineType when created without explicit value)|(should fail to start when a volume is backed by PVC created by DataVolume instead of the DataVolume itself)|(test_id:3468)|(test_id:3466)|(test_id:1015)|(rfe_id:393)' -ginkgo.slowSpecThreshold=60 -ginkgo.succinct -oc-path=/usr/bin/oc -kubectl-path=/usr/bin/oc -utility-container-prefix=quay.io/kubevirt -test.timeout=2h 
INFO[2021-04-07T15:08:45Z] /go/src/github.com/kubevirt/hyperconverged-cluster-operator/_out/kv_smoke_tests.test: line 1: Not: command not found 
```

**Comment by erkanerol** [comment]
@tiraboschi  There is no problem in this PR but kubevirt 0.39.1 is deleted by kubevirt team because of some other issues. Therefore, the test binary doesn't exist anymore. We need to revert this PR https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1221/files

**Comment by erkanerol** [comment]
@tiraboschi  I created #1233. After it, we will need to rebase all PRs.

**Review by tiraboschi — APPROVED** [review]

**Comment by tiraboschi** [comment]
hco-e2e-image-index-aws lane succeeded.
/override ci/prow/hco-e2e-image-index-gcp

**Pull request merged**
