### PR TITLE
Bump golang to 1.21.7

### PR DESCRIPTION
**Pull request by nunnatsa**
## What this PR does / why we need it
Bump golang to go1.21.6

**Jira Ticket**:

```jira-ticket
None
```

**Release note**:

```release-note
Bump golang to 1.21.6
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
/hold

Needs https://github.com/openshift/release/pull/48414

**Review by tiraboschi — APPROVED** [review]

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
hco-e2e-operator-sdk-sno-aws lane passed
/override ci/prow/hco-e2e-operator-sdk-sno-azure

 lane hco-e2e-upgrade-operator-sdk-aws passed
/override ci/prow/hco-e2e-upgrade-operator-sdk-azure

**Comment by nunnatsa** [comment]
hco-e2e-operator-sdk-sno-aws lane passed
/override ci/prow/hco-e2e-operator-sdk-sno-azure

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
