### PR TITLE
temporary hack to unlock CI

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
Still failing because the image gets replaced even if pinned to a specific digest:
```
Pulling image "docker-registry.default.svc:5000/ci-op-bswrb8hy/pipeline@sha256:d20f072d633668dc903031aeee70d6c440a3148bede77df3166134b660f89e81" ...
Replaced Dockerfile FROM image quay.io/openshift/origin-operator-registry@sha256:6e86ed8cd31ede37e3fec917a9b0686f75a9ad90cc646d92e58456553fcefcfa
```

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by tiraboschi** [comment]
done with https://github.com/openshift/release/pull/11343

**Pull request closed without merging**
