### PR TITLE
Fix kubevirt-storage-class-defaults ConfigMap name

### PR DESCRIPTION
**Pull request by mareklibra**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1751183

### CODE REVIEW

**Comment by mareklibra** [comment]
@rthallisey , please advise which branch this patch should be backported to.

**Comment by mareklibra** [comment]
Failing CI is unrelated:
```
07:36:43  deployment.extensions/packageserver condition met
07:36:44  deployment.extensions/catalog-operator condition met
07:36:44  -- Upgrade Step 3/8: create catalogsource and subscription to install HCO
07:36:44  Error from server (AlreadyExists): namespaces "kubevirt-hyperconverged" already exists

...

07:40:34  ./cluster-up/kubectl.sh get pods -n openshift-operator-lifecycle-manager | grep hco-catalogsource
07:40:34  hco-catalogsource-example-4xjmz     1/1     Running   0          3m50s
07:40:35  error: resource(s) were provided, but no name, label selector, or --all flag specified
```

**Comment by danielerez** [comment]
LGTM

**Comment by rthallisey** [comment]
ci test please

**Comment by rthallisey** [comment]
ci test please

**Comment by fabiand** [comment]
Is there anything blocking this PR from getting merged?
What needs to be done to get it merged?

**Comment by fabiand** [comment]
ci test please

**Pull request merged**
