### PR TITLE
change the default branch to main

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Reviewer Checklist**

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by orenc1** [comment]
please update master references also in workflow files:

- digester_bot
- pr-sanity
- publish-community-operators
- release-bumper

**Comment by nunnatsa** [comment]
.אקדא okd-hco-e2e-image-index-azure

**Comment by orenc1** [comment]
`quay.io/kubevirt/hyperconverged-cluster-index:1.4.0-unstable` has been fixed.
/retest

**Comment by nunnatsa** [comment]
/test hco-e2e-upgrade-prev-index-aws — Job failed.                     BaseSHA:d6f5f6ffbd968bb9af968df2b42d658b36dc13ce
Details

**Review by orenc1 — APPROVED** [review]
/approve

**Pull request merged**
