### PR TITLE
Bump VM_IMPORT to v0.2.0

### PR DESCRIPTION
**Pull request by pkliczewski**
Bump VM_IMPORT to v0.2.0

```release-note
Bump VM_IMPORT to v0.2.0
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by tiraboschi** [comment]
Doing it on https://github.com/kubevirt/hyperconverged-cluster-operator/pull/751

**Pull request closed without merging**
