### PR TITLE
Include HPP in the CSV

### PR DESCRIPTION
**Pull request by tiraboschi**
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

### CODE REVIEW

**Comment by tiraboschi** [comment]
ci test please

**Comment by tiraboschi** [comment]
ci test please

**Comment by tiraboschi** [comment]
@awels 
hostpath-provisioner-operator:v0.2.9 fails with:
```
  Normal   Pulled          108s                kubelet, node02    Successfully pulled image "quay.io/kubevirt/hostpath-provisioner-operator:v0.2.9"
  Normal   SandboxChanged  108s                kubelet, node02    Pod sandbox changed, it will be killed and re-created.
  Warning  Failed          7s (x11 over 108s)  kubelet, node02    Error: container has runAsNonRoot and image will run as root
```
can you please take a look?

**Comment by awels** [comment]
Do you have the yaml of the operator in the HCO? I have not set the operator to run as root at all. So I don't understand why it is attempting to do so.

**Comment by tiraboschi** [comment]
> Do you have the yaml of the operator in the HCO? I have not set the operator to run as root at all. So I don't understand why it is attempting to do so.

We are extracting it with this command line:
`docker run --rm --entrypoint=/usr/bin/csv-generator quay.io/kubevirt/hostpath-provisioner-operator:v0.2.9 --csv-version=1.0.0 --operator-image-name=quay.io/kubevirt/hostpath-provisioner-operator:v0.2.9 --provisioner-image-name=quay.io/kubevirt/hostpath-provisioner:v0.2.2 --namespace=kubevirt-hyperconverged --pull-policy=IfNotPresent --dump-crds`

which gives back to us: https://gist.github.com/tiraboschi/9b54fd360cbff8cc61084d19229e839f

which lead to https://github.com/kubevirt/hyperconverged-cluster-operator/pull/373/files#diff-596cc2d310f34838c070d591142f411c in this PR.

**Comment by tiraboschi** [comment]
ci test please

**Comment by orenc1** [comment]
@tiraboschi I think we can close that one.
HPP is in the CSV.

**Comment by tiraboschi** [comment]
Right, abandoning this

**Pull request closed without merging**
