### PR TITLE
consider NMO as an external operator

### PR DESCRIPTION
**Pull request by tiraboschi**
We are going to consume NMO as an external operator
just as a dependency at OLM level.

TODO: get NMO in CI from https://quay.io/repository/kubevirt/node-maintenance-operator-index:latest index image

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

**Release note**:
```release-note
Consider NMO as an external operator
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by slintes** [comment]
there it goes... thanks! :+1:

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by orenc1** [comment]
maybe also remove NMO from the list of components HCO is deploying & controlling, in the main readme file?
https://github.com/kubevirt/hyperconverged-cluster-operator/blame/master/README.md#L12

**Comment by tiraboschi** [comment]
> maybe also remove NMO from the list of components HCO is deploying & controlling, in the main readme file?
> https://github.com/kubevirt/hyperconverged-cluster-operator/blame/master/README.md#L12

I'm moving it to a new section called dependencies.

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by orenc1** [comment]
> > maybe also remove NMO from the list of components HCO is deploying & controlling, in the main readme file?
> > https://github.com/kubevirt/hyperconverged-cluster-operator/blame/master/README.md#L12
> 
> I'm moving it to a new section called dependencies.

will it be on this PR, or on a subsequent one?

**Pull request merged**
