### PR TITLE
Bump various golang dependencies

### PR DESCRIPTION
**Pull request by tiraboschi**
**What this PR does / why we need it**:
Bump various golang dependencies:
- github.com/evanphx/json-patch/v5 v5.7.0 => v5.9.0
- github.com/go-logr/logr v1.3.0 => v1.4.1
- github.com/google/uuid v1.3.1 => v1.6.0
- github.com/kubevirt/monitoring/pkg/metrics/parser v0.0.0-20231024120544-6a3ba1a680b4 => v0.0.0-20240125201600-b689e9c89409
- github.com/machadovilaca/operator-observability v0.0.8 => v0.0.11
- github.com/onsi/ginkgo/v2 v2.13.0 => v2.15.0
- github.com/onsi/gomega v1.29.0 => v1.31.1
- github.com/openshift/library-go v0.0.0-20231003133513-3a0c1fc00519 => v0.0.0-20240126142105-b5320774c6c4
- github.com/operator-framework/api v0.17.7 => v0.21.0
- github.com/operator-framework/operator-lib v0.11.1-0.20230306195046-28cadc6b6055 => v0.12.0
- github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring v0.68.0 => v0.71.2
- github.com/samber/lo v1.38.1 => v1.39.0
- golang.org/x/sync v0.3.0 => v0.6.0
- golang.org/x/tools v0.13.0 => v0.17.0
- k8s.io/* v0.28.3 => v0.29.1
- k8s.io/kube-openapi v0.0.0-20230928205116-a78145627833 => v0.0.0-20240126223410-2919ad4fcfec
- k8s.io/utils v0.0.0-20230726121419-3b25d923346b => v0.0.0-20240102154912-e7106e64919e
- sigs.k8s.io/controller-tools v0.13.0 => v0.14.0

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly

**Jira Ticket**:

```jira-ticket
NONE
```

**Release note**:

```release-note
NONE 
```

### CODE REVIEW

**Comment by tiraboschi** [comment]
github.com/kubernetes-sigs/controller-runtime v0.17.0 is breaking some of our unit tests and it will be addressed in a separate PR.

**Comment by tiraboschi** [comment]
hco-e2e-operator-sdk-gcp, hco-e2e-operator-sdk-aws lanes succeeded.
/override ci/prow/hco-e2e-operator-sdk-azure

**Review by nunnatsa — APPROVED** [review]
/approve

**Comment by tiraboschi** [comment]
hco-e2e-consecutive-operator-sdk-upgrades-azure lane succeeded.
/override ci/prow/hco-e2e-consecutive-operator-sdk-upgrades-aws

**Pull request merged**
