### PR TITLE
Create ImageStreams if they defined in the dataImportCronTemplate yaml files

### PR DESCRIPTION
**Pull request by nunnatsa**
If the dataImportCronTemplate yaml files contain a temaplate with both URL and ImageStream, HCO will create the ImageStream if not exist, and will update SSP with the template without the URL but only with the imageStream.

Specific implementation for updating existing imageStreams (from the unit tests):
1. should create the ImageStream resource if not exists
2. should update the ImageStream resource if the docker image was changed
3. should remove tags if they are not required
4. should not update the imageStream if the tag name and the from.name fields are the same
5. should not update the imageStream if the it not controlled by HCO (even if the details are not the same)

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**Reviewer Checklist**

> Reviewers are supposed to review the PR for every aspect below one by one. To check an item means the PR is either "OK" or "Not Applicable" in terms of that item. All items are supposed to be checked before merging a PR. 

- [ ] PR Message
- [ ] Commit Messages
- [ ] How to test
- [ ] Unit Tests
- [ ] Functional Tests
- [ ] User Documentation
- [ ] Developer Documentation
- [ ] Upgrade Scenario
- [ ] Uninstallation Scenario
- [ ] Backward Compatibility
- [ ] Troubleshooting Friendly
  
**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
/hold

Need to redesign this

**Review by tiraboschi — APPROVED** [review]

**Pull request merged**
